### ISSUE TITLE
MimeTypes in converters not working for Asciidoc Transformer

### ISSUE THREAD

**Issue by henriette-einstein** [gridsome/gridsome#1009]
## Description

I want to write a transformer that converts Asciidoc files.

### Steps to reproduce

I created a transformer @henriette-einstein/gridsome-transformer-asciidoc that returns the following mime types:

`
static mimeTypes () {
    return ['application/asciidoc', 'application/x-asciidoc', 'application/adoc', 'application/x-adoc'];

  }
`

The complete transformer can be found on npm.

I used the Transformer with the following gridsome.config.js in a different project:

`
module.exports = {
  siteName: 'Henriettes Testapp',
  plugins: [
    {
      use: '@gridsome/source-filesystem',
      options: {
        path: 'content/adoc/*.adoc',
        typeName: 'AsciidocBlog'
      }

    }
  ],
  templates: {
    AsciidocBlog: '/blog/:slug'
  },
  transformers: {
    asciidoc: {}
  }
};
`

Package.json references the transformer as follows:

`  
"devDependencies": {
    "@gridsome/source-filesystem": "^0.6.2",
    "@henriette-einstein/gridsome-transformer-asciidoc": "^0.9.3",
   ...

`

### Expected result
I expected the transformer would be invoked for files with the extension adoc, e.g for
content/adoc/test.adoc

### Actual result

Instead I got the following error message when invoking `Gridsome develop`:

`
Gridsome v0.7.13

Initializing plugins...
Error: No transformer for 'application/x-adoc' is installed.
    at transformNodeContent (/Users/arpablo/newgit/gridsome-starter-henriette/node_modules/gridsome/lib/store/transformNodeContent.js:12:13)
    at SyncBailWaterfallHook.eval [as call] (eval at create (/Users/arpablo/newgit/gridsome-starter-henriette/node_modules/gridsome/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at SyncBailWaterfallHook.lazyCompileHook (/Users/arpablo/newgit/gridsome-starter-henriette/node_modules/gridsome/node_modules/tapable/lib/Hook.js:156:20)
    at Collection.addNode (/Users/arpablo/newgit/gridsome-starter-henriette/node_modules/gridsome/lib/store/Collection.js:72:50)
    at /Users/arpablo/newgit/gridsome-starter-henriette/node_modules/@gridsome/source-filesystem/index.js:67:36
    at async Promise.all (index 0)
    at async FilesystemSource.createNodes (/Users/arpablo/newgit/gridsome-starter-henriette/node_modules/@gridsome/source-filesystem/index.js:65:5)
    at async /Users/arpablo/newgit/gridsome-starter-henriette/node_modules/@gridsome/source-filesystem/index.js:33:7
    at async Plugins.run (/Users/arpablo/newgit/gridsome-starter-henriette/node_modules/gridsome/lib/app/Plugins.js:141:11)

`

### Environment

I'm running on a Mac with the latest OS.

**Comment by osvaldoM** [comment]
@henriette-einstein , did you have any success with this? I'm facing a similar issue, and I have no idea what the problem could be.
