### ISSUE TITLE
Collection.updateNode( ) does not work

### ISSUE THREAD

**Issue by Edmund1645** [gridsome/gridsome#1019]
## Description
I'm trying to build a plugin which does have some async processes running, so I could not use the `api.onCreateNode()` hook, I'm using the `api.loadSource()` and now getting all nodes from a specifc collection, I'm trying to modify each node and update it using `collection.updateNode()` but that doesn't seem to be working.

I tried duplicating the original node then deleting it, modifying the new copy and adding back to the collection but I get an error: 

```
TypeError: fun is not a function
    at Resultset.find (/Users/edmund/projects/open-source/blog-cover-sandbox/node_modules/lokijs/src/lokijs.js:3526:17)
    at Resultset.findAnd (/Users/edmund/projects/open-source/blog-cover-sandbox/node_modules/lokijs/src/lokijs.js:3365:14)
    at Resultset.find (/Users/edmund/projects/open-source/blog-cover-sandbox/node_modules/lokijs/src/lokijs.js:3438:23)
    at Resultset.find (/Users/edmund/projects/open-source/blog-cover-sandbox/node_modules/lokijs/src/lokijs.js:3418:23)
    at Collection.findOne (/Users/edmund/projects/open-source/blog-cover-sandbox/node_modules/lokijs/src/lokijs.js:6807:33)
    at Collection.removeNode (/Users/edmund/projects/open-source/blog-cover-sandbox/node_modules/gridsome/lib/store/Collection.js:105:35)
    at /Users/edmund/projects/open-source/gridsome-plugin-blog-cover/gridsome.server.js:91:18
    at Array.forEach (<anonymous>)
    at /Users/edmund/projects/open-source/gridsome-plugin-blog-cover/gridsome.server.js:65:23
    at Plugins.run (/Users/edmund/projects/open-source/blog-cover-sandbox/node_modules/gridsome/lib/app/Plugins.js:141:17)
```
logging the original node, or clone shows the modification I've made.

### Steps to reproduce
add this to the `gridsome.server.js` file to test
```js
  api.loadSource(async actions => {
    const collection = actions.getCollection(options.typeName); // any typeName you have is fine


      node.title += '_updated';

      collection.updateNode(node); // doesn't update
      console.log(clone);
    });
```

### Expected result

I should see nodes with the title `*_updated` in the graphQL playground when I make queries to test

### Actual result

The nodes remain the same, nothing gets updated.

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.0 - ~/.nvm/versions/node/v12.13.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Safari: 13.0.5
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.5.0 => 0.5.0 
    gridsome: ^0.7.12 => 0.7.12 
    gridsome-plugin-blog-cover: file:../gridsome-plugin-blog-cover => 0.0.4-alpha.1 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

**Comment by hacknug** [comment]
Not sure how this works but did you try ``collection.updateNode({ title: `${node.title} _updated` })``? Looks like you only need to pass an object with the new data.

Also, can't see where `node` comes from on your code but I guess you just removed the part where you loop over nodes or something similar.

You can find the example I looked at here: https://github.com/gridsome/gridsome/blob/beb9084a686a52d239bb6b438ea86ca2c311d184/gridsome/lib/store/__tests__/PluginStore.spec.js#L109-L116
https://github.com/gridsome/gridsome/blob/beb9084a686a52d239bb6b438ea86ca2c311d184/gridsome/lib/store/__tests__/PluginStore.spec.js#L147

**Comment by Edmund1645** [comment]
It works now, THANKS!

**Comment by Edmund1645** [comment]
It seems I have to add all other properties from the old node as well, it doesn't just update the new properties, it replaces them, so old properties are now null. They no longer exist.

**Comment by hacknug** [comment]
No idea how to solve it then. The `null` issue might be related to #562 (or not 🤷‍♂)

**Comment by orblazer** [comment]
Hello,
You could try with my PR #1252 if that is fixed ?

Thanks.

**Comment by johanvergeer** [comment]
I just tried to use the `updateNode()` function and ran into some issues as well. (Gridsome version 0.7.19)

This is my function in `gridsome.server.js` 

```js
module.exports = function (api, options) {
  api.loadSource(store => {
    const posts = store.getCollection('Post')

    posts.data().forEach((post) => {
      // Set updateDate to latest git commit of the file
      exec(`git log -1 --pretty="format:%ci" ${post.internal.origin}`, (err, stdout, stderr) => {
        if (err) {
          console.error(err)
        } else {
          posts.updateNode({
            $uid: post.$uid,
            updateDate: stdout
          })
        }
      });
    })
  })
}
```

After debugging I figured out the issue occurs in the `@gridsome/vue-remark` plugin. What I cannot figure out why `@gridsome/vue-remark` is called.

```sh
/usr/local/bin/node /usr/local/Cellar/yarn/1.19.2/libexec/bin/yarn.js run develop
Debugger listening on ws://127.0.0.1:50631/703e4ec8-2bef-4669-a19e-e453c021b1ae
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
yarn run v1.19.2
$ gridsome develop
Debugger listening on ws://127.0.0.1:50635/56904aef-92c9-4c09-bb38-21cf79e643dd
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Gridsome v0.7.19

Initializing plugins...
Load sources - 0.14s
Create GraphQL schema - 0.14s
Waiting for the debugger to disconnect...
/Users/johanvergeer/workspace/coding-with-johan/node_modules/gray-matter/lib/utils.js:42
    throw new TypeError('expected input to be a string or buffer');
    ^

TypeError: expected input to be a string or buffer
    at Object.exports.toString (/Users/johanvergeer/workspace/coding-with-johan/node_modules/gray-matter/lib/utils.js:42:11)
    at module.exports (/Users/johanvergeer/workspace/coding-with-johan/node_modules/gray-matter/lib/to-file.js:39:24)
    at matter (/Users/johanvergeer/workspace/coding-with-johan/node_modules/gray-matter/index.js:34:14)
    at RemarkTransformer.parse (/Users/johanvergeer/workspace/coding-with-johan/node_modules/@gridsome/transformer-remark/index.js:47:40)
    at /Users/johanvergeer/workspace/coding-with-johan/node_modules/@gridsome/vue-remark/index.js:212:36
    at SyncBailWaterfallHook.eval [as call] (eval at create (/Users/johanvergeer/workspace/coding-with-johan/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Collection.updateNode (/Users/johanvergeer/workspace/coding-with-johan/node_modules/gridsome/lib/store/Collection.js:127:50)
    at /Users/johanvergeer/workspace/coding-with-johan/gridsome.server.js:21:17
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:670:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Waiting for the debugger to disconnect...

Process finished with exit code 1
```

**Comment by Edmund1645** [comment]
I can't seem to find a workaround for this, if a field does not exist before running `api.loadSource()` none of the nodes get updated.

**Comment by songololo** [comment]
Does anyone have any updates on how to properly update a node from `api.loadSource()` and persist these across hot module reloading?

I've noticed that it is possible to directly modify the collection, and this will work when building and developing, except that it breaks with the hot module reload when modifying the source file for the affected template page (it will break for a specific template at a specific route but other pages continue to work unless their source files are likewise modified.)

**Comment by thetre97** [comment]
You could try using the `onBootstrap` hook - `loadSource` is run while Gridsome is sourcing data, so is not always that reliable, in that you may not always have the data you need yet. You should still be able to edit data inside the bootstrap hook - see https://github.com/noxify/gridsome-plugin-remote-image/blob/2297bd3f1edbef9390d626c3cf1cfc9e3372eba6/gridsome.server.js#L124 for an example.
