### ISSUE TITLE
Builds failing non-deterministically in internal graphql API

### ISSUE THREAD

**Issue by tobsch** [gridsome/gridsome#1026]
Hi there,

we have a problem with our production builds failing randomly when accessing the local graphql Datalayer with the error: "Error: Unexpected token < in JSON at position 0".
I assume that it tries to parse an HTML-Error ("< at position 0").
Is it possible that the GraphQL Datalyer returns such errors under special circumstances?

This is the full log if it works: ```

``Run yarn run build
yarn run v1.22.0
$ gridsome build
Gridsome v0.7.7

Initializing plugins...
Load sources - 0.11s
Create GraphQL schema - 1.72s
Create pages and templates - 25.85s
Generate temporary code - 1.85s
Bootstrap finish - 30.31s
Compiling assets...
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/events/events/src/.temp/routes.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/events/events/src/.temp/routes.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/events/events/src/components/omr20/Speakers.vue as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/events/events/src/components/omr20/Speakers.vue as it exceeds the max of 500KB.
Compile assets - 89.85s
Execute GraphQL (2322 queries) - 1.43s
Write out page data (2322 files) - 0.61s
Render HTML (2322 files) - 17.93s
Process files (2 files) - 0.01s
Processing images (189 images) - 0%Processing images (189 images) - 13%Processing images (189 images) - 25%Processing images (189 images) - 38%Processing images (189 images) - 50%Processing images (189 images) - 63%Processing images (189 images) - 75%Processing images (189 images) - 88%Processing images (189 images) - 100%Process images (189 images) - 19.24s```

This is the full log if it fails:
```
 gridsome build
Gridsome v0.7.7

Initializing plugins...
Load sources - 0.11s
Create GraphQL schema - 2.15s
Create pages and templates - 23.04s
Generate temporary code - 1.9s
Bootstrap finish - 27.98s
Compiling assets...
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/events/events/src/.temp/routes.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/events/events/src/.temp/routes.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/events/events/src/components/omr20/Speakers.vue as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/events/events/src/components/omr20/Speakers.vue as it exceeds the max of 500KB.
Error: Unexpected token < in JSON at position 0

GraphQL request:29:3
28 | query event  {
29 |   event (slug: "omr20") {
   |   ^
30 |     partnerCompanyListing {
    at Object.module.exports (/home/runner/work/events/events/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:58:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

**Comment by tobsch** [comment]
Please note: The GraphQL Error is the query it fails with, but the query is correct.
If you re-run the build it sometimes works. And that with same data & code.

**Comment by mtlynch** [comment]
@tobsch - Would it be possible to share a link to a public repo that has this behavior?

**Comment by thinkflo** [comment]
Just wanted to report that I'm running into this same issue.  The issue suddenly occurred yesterday.  I tried rolling back earlier in my repo but to no effect.

```
gridsome build
Gridsome v0.7.23

Initializing plugins...
Load sources - 0s
Create GraphQL schema - 3.47s
Create pages and templates - 6.77s
Generate temporary code - 0.88s
Bootstrap finish - 13.08s
Error: Unexpected token < in JSON at position 0

GraphQL request:145:5
144 |   craft {
145 |     enCA: entries( site: "en", section: "taxRates", orderBy: "title ASC") {
    |     ^
146 |       id
    at Object.module.exports ([redacted project folder]/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:58:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    ```
