### ISSUE TITLE
Dynamic page fail to load image with graphQL Query

### ISSUE THREAD

**Issue by braininteractive** [gridsome/gridsome#1029]
## Description
I got one error when I try to serve images from graphQL Query (or with !!assets-loader!) 
on a dynamic page template  jpeg, png, webp, always got this error

Any suggestion ?

<g-image :src="$page.services.picture.src" ></g-image>

<page-query>
query {
  services(path: "testpath"){
        id
        path
        picture (quality: 90)
        title
  }
}
</page-query>

Error: spawn 
/node_modules/mozjpeg/vendor/cjpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

### Environment

System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 10.8.0 
    npm: 6.9.0 
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 66.0.5
    Safari: 12.1.2
  npmPackages:
    gridsome: ^0.7.0 => 0.7.12 
    @gridsome/plugin-critical: ^0.1.2 => 0.1.6 
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.0 
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3 
    @gridsome/source-faker: ^0.3.0 => 0.3.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-json: ^0.2.1 => 0.2.1 
    gridsome-helper-json: ^1.0.3 => 1.0.3 
    gridsome-plugin-gtm: ^0.1.1 => 0.1.1 
    gridsome-plugin-htaccess: ^0.2.1 => 0.2.1 
    gridsome-plugin-robots-txt: ^1.0.2 => 1.0.2 
    gridsome-plugin-sentry: ^1.0.0 => 1.0.0 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1

**Comment by braininteractive** [comment]
Seems to be my npm problem,
this one works for me :

$ npm rebuild mozjpeg
$ npm rebuild gifsicle
$ npm rebuild optipng-bin
