### ISSUE TITLE
[🐛 Bug] 'gridsome build' Command Fails

### ISSUE THREAD

**Issue by RehanSaeed** [gridsome/gridsome#1031]
## Description

The `gridsome develop` and `gridsome build` commands randomly fail. This looks like a known issue:

- https://github.com/gridsome/gridsome.org/issues/356
- https://github.com/gridsome/gridsome-starter-blog/issues/8

### Steps to reproduce

Run `gridsome develop` and `gridsome build`. See my GitHub action which is failing:

https://github.com/RehanSaeed/rehansaeed.github.io/runs/500559420?check_suite_focus=true

### Actual result

```
Create pages and templates - 0.05s
Generate temporary code - 0.02s
Bootstrap finish - 1.88s
Compiling assets...
Compile assets - 9.34s
An error occurred while executing page-query for src\templates\Post.vue

Error: Unknown argument "width" on field "cover_image" of type "Post".

GraphQL request:71:18
70 |     content
71 |     cover_image (width: 860, blur: 10)
   |                  ^
72 |   }
    at throwError (D:\a\rehansaeed.github.io\rehansaeed.github.io\node_modules\gridsome\lib\app\build\executeQueries.js:21:13)
    at pMap.concurrency (D:\a\rehansaeed.github.io\rehansaeed.github.io\node_modules\gridsome\lib\app\build\executeQueries.js:41:11)
    at D:\a\rehansaeed.github.io\rehansaeed.github.io\node_modules\p-map\index.js:47:21
npm ERR! code ELIFECYCLE
```

### Environment

```
  System:
    OS: Windows 10 10.0.19569
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19569.1000.0
  npmPackages:
    gridsome: ^0.7.13 => 0.7.13
```

**Comment by preetamslot** [comment]
Got the same Issue when the image field is an empty string.

**Comment by RehanSaeed** [comment]
@hjvedvik This bug is pretty debilitating. It means I can't use CI to deploy my site.

**Comment by hjvedvik** [comment]
@RehanSaeed Can it be that no posts have an image attached when the build fails?
