### ISSUE TITLE
TypeError: b.indexOf is not a function, Lokijs

### ISSUE THREAD

**Issue by darrylmorley** [gridsome/gridsome#1034]
## Description
My site works fine when developing but when attempting to build on Netlify the build fails.

Describe the issue that you're seeing.
The error as reported is:
```
2:49:44 PM: TypeError: b.indexOf is not a function
2:49:44 PM:     at $in (/opt/build/repo/node_modules/lokijs/src/lokijs.js:503:18)
2:49:44 PM:     at dotSubScan (/opt/build/repo/node_modules/lokijs/src/lokijs.js:393:22)
2:49:44 PM:     at dotSubScan (/opt/build/repo/node_modules/lokijs/src/lokijs.js:396:24)
2:49:44 PM:     at Resultset.find (/opt/build/repo/node_modules/lokijs/src/lokijs.js:3545:19)
2:49:44 PM:     at calcTotalPages (/opt/build/repo/node_modules/gridsome/lib/app/build/createRenderQueue.js:54:32)
2:49:44 PM:     at createRenderQueue (/opt/build/repo/node_modules/gridsome/lib/app/build/createRenderQueue.js:20:28)
2:49:44 PM:     at module.exports (/opt/build/repo/node_modules/gridsome/lib/build.js:24:17)
2:49:44 PM: Skipping functions preparation step: no functions directory set
```

### Expected result

What should happen?

The site should build on Netlify

Any advice on where I should be looking to resolve this build issue would be much appreciated.

**Comment by zacnomore** [comment]
@darrylmorley Could you share the results of `gridsome info`? Do you have a repo where we could reproduce?

**Comment by darrylmorley** [comment]
Hi @zacnomore,
gridsome build offers:
```
 System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.14.1 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 73.0.1
    Safari: 13.0.5
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/source-wordpress: ^0.5.2 => 0.5.2 
    @gridsome/transformer-json: ^0.2.1 => 0.2.1 
    @gridsome/transformer-remark: ^0.5.0 => 0.5.0 
    gridsome: ^0.7.11 => 0.7.12 
    gridsome-plugin-flexsearch: ^0.1.6 => 0.1.9 
    gridsome-plugin-netlify-cms: ^1.0.9 => 1.0.9 
    gridsome-plugin-purgecss: ^1.0.12 => 1.0.12 
    gridsome-plugin-remark-youtube: ^1.0.1 => 1.0.1 
    gridsome-plugin-tailwindcss: ^2.2.27 => 2.2.27 
    gridsome-plugin-yandex-metrika: ^0.1.2 => 0.1.2 
    gridsome-transformer-docutils: ^0.2.3 => 0.2.3 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```
My repo is at https://github.com/darrylmorley/ss-gridsome

**Comment by darrylmorley** [comment]
Could it be an issue with the amount of data/pages?

**Comment by darrylmorley** [comment]
I have updated all packages, yarn outdated no longer shows anything outdated. I have removed node_modules and reinstalled. The build still fails with:
```
TypeError: b.indexOf is not a function
    at $in (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/lokijs/src/lokijs.js:503:18)
    at dotSubScan (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/lokijs/src/lokijs.js:393:22)
    at dotSubScan (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/lokijs/src/lokijs.js:396:24)
    at Resultset.find (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/lokijs/src/lokijs.js:3545:19)
    at calcTotalPages (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/gridsome/lib/app/build/createRenderQueue.js:54:32)
    at createRenderQueue (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/gridsome/lib/app/build/createRenderQueue.js:20:28)
    at module.exports (/Users/darryl/Projects/shooting-supplies/ss-gridsome/node_modules/gridsome/lib/build.js:24:17)
```
gridsome info now shows:
```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.14.1 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 74.0
    Safari: 13.0.5
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/source-wordpress: ^0.5.2 => 0.5.3 
    @gridsome/transformer-json: ^0.2.1 => 0.2.1 
    @gridsome/transformer-remark: ^0.5.0 => 0.5.0 
    gridsome: ^0.7.11 => 0.7.13 
    gridsome-plugin-flexsearch: ^0.1.6 => 0.1.13 
    gridsome-plugin-netlify-cms: ^1.0.9 => 1.0.9 
    gridsome-plugin-remark-youtube: ^1.0.1 => 1.0.1 
    gridsome-plugin-tailwindcss: ^2.2.27 => 2.2.41 
    gridsome-plugin-yandex-metrika: ^0.1.2 => 0.1.2 
    gridsome-transformer-docutils: ^0.2.3 => 0.2.3 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

Can anybody please advise how to go about resolving?

**Comment by darrylmorley** [comment]
I found that the cause of this issue was a filter in my graphql query. I'll leave this here in case anybody else comes across the same.

e.g.
Using (filter: {shoes: {id: {in: 217}}}) works in develop and playground but fails on build.
(filter: {shoes: {id: {eq: 217}}}) works on build.

'in:' can only be used when querying multiple id's on build.
i.e. (filter: {shoes: {id: {in: [215, 218]}}})
