### ISSUE TITLE
Pagination - Cyclic dependency

### ISSUE THREAD

**Issue by SteveEdson** [gridsome/gridsome#109]
## Description

Following the example at https://gridsome.org/docs/pagination/, I get an error of

<details>
<summary>
`Error: Cyclic dependency`
</summary>
<pre><code>
at visit (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/toposort/index.js:35:13)
    at visit (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/toposort/index.js:53:9)
    at visit (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/html-webpack-plugin/index.js:364:35)
    at /Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at Compiler.emitAssets (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/webpack/lib/Compiler.js:363:19)
    at onCompiled (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/webpack/lib/Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/webpack/lib/Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at compilation.seal.err (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/webpack/lib/Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/steveedson/repos/personal/steve-2019-gridsome/node_modules/webpack/lib/Compilation.js:1323:35)
</code></pre>
</details>

### Steps to reproduce

```js
<script>
import { Pager } from 'gridsome'

export default {
  components: {
    Pager
  }
}
</script>
```

I should add that I'm doing this with a component, rather than a layout or page, in case that makes a difference.

Tested on `v0.3.6` and `v0.4.2`

### Expected result

Pagination component should import without error.

**Comment by hjvedvik** [comment]
Just got the same issue myself. I have fixed it and will publish it within the next days :)
