### ISSUE TITLE
Error: Failed to install dependencies with yarn.

### ISSUE THREAD

**Issue by eduardomachuca** [gridsome/gridsome#1118]
## Description

`~/mydev$ gridsome create my-new-blog
❯ Clone https://github.com/gridsome/gridsome-starter-default.git 1.02s
❯ Update project package.json 0.01s
❯ Install dependencies
  • Building fresh packages (4 of 4)
Error: Failed to install dependencies with yarn. Please enter my-new-blog directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

    Exit code 1
    at ChildProcess.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@gridsome/cli/lib/commands/create.js:103:17)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
`

### Steps to reproduce

- Following "How to install" steps from https://gridsome.org/docs/, using Yarn.
- Same issue already reported at [issue 416](https://github.com/gridsome/gridsome/issues/416).
- Issue closed but solution does not applies to new gridsome version in package.json.

### Expected result

Create a new project.

### Actual result

Yarn error creating dependecies.

If I go to /my-new-blog (project directory) and run yarn command, I get:

`my-new-blog$ yarn
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning gridsome > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning gridsome > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning gridsome > probe-image-size > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning gridsome > webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning gridsome > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning gridsome > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
error /home/edu/mydev/my-new-blog/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/edu/mydev/my-new-blog/node_modules/sharp
Output:
info sharp Using cached /home/edu/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.0.0 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.0.0 | linux | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/edu/mydev/my-new-blog/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/edu/.cache/node-gyp/14.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/edu/.cache/node-gyp/14.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/edu/.cache/node-gyp/14.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/edu/mydev/my-new-blog/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:175:21)
gyp ERR! System Linux 4.19.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/edu/mydev/my-new-blog/node_modules/sharp
gyp ERR! node -v v14.0.0
`

### Environment

System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 AMD A10-7890K Radeon R7, 12 Compute Cores 4C+8G
  Binaries:
    Node: 14.0.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 68.7.0esr

### Same error with other starter
I get the same error (yarn can't build dependencies) if I use the Gridsome Blog Starter with the command:

gridsome create my-gridsome-site https://github.com/gridsome/gridsome-starter-blog.git

**Comment by Oudwins** [comment]
Rather than opening a new issue im just going to say that I am getting the exact same problem having installed gridsome cli with npm.
### enviroment
System:
OS: Windows 10
Node: 12.8.1 
npm: 6.14.5
