### ISSUE TITLE
Create command doesn't work if theres already a folder

### ISSUE THREAD

**Issue by nishantwrp** [gridsome/gridsome#1126]
## Description

Create command doesn't work if there's already a folder with same name

### Steps to reproduce

- Create a folder named `my-project`
- gridsome create my-project

### Expected result
Descriptive error message
```
Can't create `my-project` because there's already a non-empty directory `my-project`.
```

### Actual result

Weird Error
```
Error: Command failed: git clone https://github.com/gridsome/gridsome-starter-default.git /home/nishantwrp/Desktop/sample-project --single-branch
nullnull
    at Object.task (/home/nishantwrp/.nvm/versions/node/v12.1.0/lib/node_modules/@gridsome/cli/lib/commands/create.js:42:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by a-kriya** [comment]
Can you share your environment info as it suggests in the issue template? Run `gridsome info`.

Not reproducible on Mac 10.14 (notice that Vue CLI complains about a `temp/` existing in cwd, and then `gridsome create temp` succeeding):

```
Vue CLI v4.3.0
? Target directory /Users/[username]/Documents/gridsomeDev/temp already exists. Pick an action: Cancel

~/Documents/gridsomeDev> gridsome create temp
❯ Clone https://github.com/gridsome/gridsome-starter-default.git 2.02s
❯ Update project package.json 0s
❯ Install dependencies 50.04s

  - Enter directory cd temp
  - Run gridsome develop to start local development
  - Run gridsome build to build for production

~/Documents/gridsomeDev> ls temp/
total 40
0 drwxr-xr-x   10 [username]  713727123   320B Apr 30 xx:xx ./
0 drwxr-xr-x    4 [username]  713727123   128B Apr 30 xx:xx ../
8 -rw-r--r--    1 [username]  713727123    63B Apr 30 xx:xx .gitignore
8 -rw-r--r--    1 [username]  713727123   440B Apr 30 xx:xx README.md
8 -rw-r--r--    1 [username]  713727123   290B Apr 30 xx:xx gridsome.config.js
8 -rw-r--r--    1 [username]  713727123   576B Apr 30 xx:xx gridsome.server.js
0 drwxr-xr-x  877 [username]  713727123    27K Apr 30 xx:xx node_modules/
8 -rw-r--r--    1 [username]  713727123   209B Apr 30 xx:xx package.json
0 drwxr-xr-x    8 [username]  713727123   256B Apr 30 xx:xx src/
0 drwxr-xr-x    3 [username]  713727123    96B Apr 30 xx:xx static/
```

**Comment by nishantwrp** [comment]
Here is the info
```
 System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    Yarn: 1.21.0 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.1.0/bin/npm
  Browsers:
    Chrome: Linux
    Firefox: 71.0
  npmGlobalPackages:
    @gridsome/cli: 0.3.2
```

Actually it doesn't work if theres already an file inside that folder.

**Comment by a-kriya** [comment]
Well, in that case I'd say that Gridsome's handling of this is not really unexpected. It could be easy to tab in an existing directory by mistake and have a project initialized there. I suppose the user could be prompted to confirm if they want to create a project in case there's a conflict.

**Comment by nishantwrp** [comment]
Well its fine if gridsome doesn't allow this thing. But at least there could be a proper error message.

**Comment by a-kriya** [comment]
Can you please update your original post with that error message, and your suggested improvement to it? It'll make it straightforward to address this in a simple PR.

**Comment by nishantwrp** [comment]
@a-kriya Done!
