### ISSUE TITLE
source-wordpress getting 404 at build stage

### ISSUE THREAD

**Issue by kkalvaa** [gridsome/gridsome#1134]
## Description

I'm trying to spin up a site based on WordPress data, but the CLI is outputting a 404 error:
Error: 404 - wp/v2/menus
This error breaks the develop/build task and I get nothing.

I am fetching data from a local WordPress (hosted by Local by WP Engine), but I have also tried to fetch data from other WordPress sources with the same result. This worked up until recently when I updated WordPress to 5.4.

I have also tried from a fresh Gridsome install, with the same 404 result.

I also rumaged around the REST API looking for wp/v2/menus, it simply doesn't exsist.

### Steps to reproduce

1: Install Gridsome with @gridsome/source-wordpress
2: Navigate to Gridsome folder
3: Add WordPress source URL
4: Run gridsome develop (or build)

### Expected result

The build should run and spin up a working Gridsome site with data fetched from a WordPress install.

### Actual result

The build fails with the following error:

Gridsome v0.7.14

Initializing plugins...
Loading data from http://ensign.local
Error: 404 - wp/v2/menus
    at WordPressSource.fetch (/Users/[…]/Sites/ensign/node_modules/@gridsome/source-wordpress/index.js:197:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Once the error shows up the build fails and nothing else happens.

### Environment

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    @gridsome/source-wordpress: ^0.5.3 => 0.5.3 
    gridsome: ^0.7.14 => 0.7.14 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1

WordPress versions tested: 5.4, 5.4.1RC1(something), 5.5(nightly build)

**Comment by a-kriya** [comment]
Have you tried `curl`ing some data from the API?

**Comment by kkalvaa** [comment]
I haven't tried curl in particular, but I have used Insomnia (https://insomnia.rest/) to look at the REST API where I get access to all of the data, in other words the data is fully accible. I have also tried to use source-GraphQL instead of source-wordpress and I get data that way. I have also tried to ingest data with source-wordpress from an older version of WordPress, where it works.

The problem seems to be with source-wordpress and WordPress 5.4++.

**Comment by mario-neuhold** [comment]
> The problem seems to be with source-wordpress and WordPress 5.4++.

@kkalvaa Are you using the Gutenberg Plugin? I don't get the error with 5.4.1 but I get it with Gutenberg Plugin >= v7.8 since they added the menu endpoint:
> Add menus endpoints. https://github.com/WordPress/gutenberg/pull/20292

([Release Notes](https://github.com/WordPress/gutenberg/releases/tag/v7.8.0))

It adds the `/wp-json/wp/v2/menus` endpoint - but that route is only available for authenticated users with "edit menu" permission as mentioned here https://github.com/WP-API/menus-endpoints/pull/40

No clue why the route returns a `404` though instead of `403`.
Should we just add `404 `to the check on [index.js:193](https://github.com/gridsome/gridsome/blob/master/packages/source-wordpress/index.js#L193) or is there a proper solution?
```javascript
      if ([401, 403, 404].includes(response.status)) {
        console.warn(`Error: Status ${response.status} - ${config.url}`)
        return { ...response, data: fallbackData }
      } else {
        throw new Error(`${response.status} - ${config.url}`)
      }
```

**Comment by kkalvaa** [comment]
I am using the Gutenberg plugin. I did a test with Gutenberg disabled and the build seems to work.

**Comment by mario-neuhold** [comment]
Okay so it's the same problem as me and shouldn't occur with the Gutenberg Plugin Version below 7.8. 
If you need the latest Gutenberg, we have to go for a workaround.

@Sergix I could make a quick PR for my previous suggestion but I doubt it's the right way to do it.

**Comment by jxlstudio** [comment]
Any update here? Using this as part of an aggregator and don't have access to disable or downgrade plugins.
