### ISSUE TITLE
Gridsome develop command erro

### ISSUE THREAD

**Issue by Lucid-149** [gridsome/gridsome#1158]
## Description

Gridsome v0.7.14

Initializing plugins...
Error: Cannot find module '@vue/component-compiler-utils'
Require stack:
- /home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/plugins/vue-components/index.js
- /home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/app/Plugins.js
- /home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/app/App.js
- /home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/app/index.js
- /home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/develop.js
- /home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/index.js
- /usr/lib/node_modules/@gridsome/cli/bin/gridsome.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/plugins/vue-components/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Plugins.initialize (/home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/app/Plugins.js:45:11)
    at App.init (/home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/app/App.js:120:18)
    at App.bootstrap (/home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/app/App.js:49:16)
    at module.exports (/home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/app/index.js:12:18)
    at module.exports (/home/peter/Documents/Projects/Code/WebApp/vue/lucid/node_modules/gridsome/lib/develop.js:20:21)

### Steps to reproduce

I run gridsome develop and the error above appears.

**Comment by a-kriya** [comment]
@Lucid-149 Is this a new project that you initialized using `gridsome create`?
Do you have Vue's CLI installed globally?
What's your Node/NPM version? The issue template requests you to share the output of `gridsome info`, so can you please do that?
Try upgrading your global packages, removing/re-installing `node_modules` dir.
