### ISSUE TITLE
transformer-remark create anchor with accent

### ISSUE THREAD

**Issue by sebtiz13** [gridsome/gridsome#1203]
Hello

I don't know if it's an problem of plugin transformer-remark  or directly remark but

## Description

The plugin transformer remark create headings anchors with accent and that is not really practical because when you have an URL like `https://localhost/déboguez`

windows.location.hash it's `#d%C3%A9boguez`

Even if the basic navigation of the browser supports it. In javascript it need to use `decodeURI` function to get the right value, but I think that very few libraries support this.

In this case vue-router doesn't support this.

```
vue.esm.js?a026:1897 DOMException: Failed to execute 'querySelector' on 'Document': '#d%C3%A9boguez' is not a valid selector.
    at scrollToPosition (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1826:18)
    at Vue.eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1756:7)
    at Array.eval (webpack-internal:///./node_modules/vue/dist/vue.esm.js:1988:12)
    at flushCallbacks (webpack-internal:///./node_modules/vue/dist/vue.esm.js:1914:14)
```

I think it's better if ids of headings not have accent

### Steps to reproduce

In markdown file write an heading with accent in my case "Déboguez"

### Expected result

```json
{
  "value": "Deboguez",
  "depth": 2
}
```

### Actual result

```json
{
  "value": "Déboguez",
  "depth": 2
}
```

### Environment

>   System:
>     OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
>     CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
>   Binaries:
>     Node: 12.16.3 - /tmp/yarn--1590972752609-0.8892601746047626/node
>     Yarn: 1.21.1 - /tmp/yarn--1590972752609-0.8892601746047626/yarn
>     npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
>   npmPackages:
>     @gridsome/source-filesystem: ^0.6.2 => 0.6.2
>     @gridsome/transformer-remark: ^0.6.0 => 0.6.0
>     gridsome: ^0.7.15 => 0.7.15
>     gridsome-plugin-remark-shiki: ^0.3.1 => 0.3.1
>     gridsome-plugin-typescript: ^0.4.0 => 0.4.0

**Comment by sebtiz13** [comment]
Sorry i discovered that headings id it's generated by "remark-slug" and a similar issue have been opened:
https://github.com/remarkjs/remark-slug/issues/12
