### ISSUE TITLE
[Bug 🐛] @gridsome\source-filesystem Throws UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by RehanSaeed** [gridsome/gridsome#1223]
## Description

@gridsome\source-filesystem is erroring with:

```
code block or inline code language not specified in markdown. applying generic code block
(node:9620) UnhandledPromiseRejectionWarning: Error: Could not find node to update with id: e6b55649555e5f3c30d9f5478c3f6d6d
    at Collection.updateNode (C:\GitHub\rehansaeed.github.io\node_modules\gridsome\lib\store\Collection.js:124:13)
    at FSWatcher.<anonymous> (C:\GitHub\rehansaeed.github.io\node_modules\@gridsome\source-filesystem\index.js:117:36)
(node:9620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to reproduce

1. Install source-filesystem. I've configured mine like so:

```
{
      // Create posts from markdown files
      use: "@gridsome/source-filesystem",
      options: {
        typeName: "post",
        path: "content/posts/**/*.md",
        refs: {
          // Creates a GraphQL collection from 'tags' in front-matter and adds a reference.
          tags: {
            typeName: "tag",
            create: true
          }
        }
      }
    },
    {
      // Create posts from markdown files
      use: "@gridsome/source-filesystem",
      options: {
        typeName: "portfolio",
        path: "content/portfolio/**/*.md",
        refs: {
          // Creates a GraphQL collection from 'tags' in front-matter and adds a reference.
          tags: {
            typeName: "tag",
            create: true
          }
        }
      }
    },
```

2. Run `npm run develop` and then edit a markdown file.
### Environment

```
  System:
    OS: Windows 10 10.0.19603
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19603.1000.0
  npmPackages:
    @gridsome/plugin-critical: ^0.1.6 => 0.1.6
    @gridsome/plugin-google-analytics: ^0.1.1 => 0.1.1
    @gridsome/plugin-sitemap: ^0.3.0 => 0.3.0
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.0 => 0.6.0
    gridsome: ^0.7.17 => 0.7.17
    gridsome-plugin-brotli: ^0.1.3 => 0.1.3
    gridsome-plugin-feed: ^1.0.2 => 1.0.2
    gridsome-plugin-flexsearch: ^1.0.1 => 1.0.1
    gridsome-plugin-pwa: ^0.0.18 => 0.0.18
    gridsome-plugin-remark-prismjs-all: ^0.3.5 => 0.3.5
    gridsome-plugin-robots: ^0.2.1 => 0.2.1
    gridsome-remark-embed-snippet: ^1.0.2 => 1.0.2
    gridsome-source-static-meta: ^1.0.1 => 1.0.1
```

**Comment by Sergix** [comment]
Strange. I don't think it has to do with the first line of the error message, `code block or inline code language not specified in markdown. applying generic code block`...

**Comment by vjandrei** [comment]
I have this same issue here now. 
When trying to update .md file from content folder I get 
`(node:5586) UnhandledPromiseRejectionWarning: Error: Could not find node to update with id: 483c339463fcf17697a1f57676ff4a2b
    at Collection.updateNode (node_modules/gridsome/lib/store/Collection.js:124:13)
    at FSWatcher.<anonymous> (node_modules/@gridsome/source-filesystem/index.js:117:36)
(node:5586) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5586) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by hurnhu** [comment]
also having this issue, any fixes?

**Comment by justdoweb-be** [comment]
Same problem here : it seems to be related to gridsome-plugin-flexsearch : disabling it fix the error.

**Comment by thetre97** [comment]
@hurnhu @vjandrei @RehanSaeed Could you confirm if you use the FlexSearch plugin, and if disabling it fixes this issue?

**Comment by RehanSaeed** [comment]
I do indeed use `gridsome-plugin-flexsearch`. Looks like https://github.com/thetre97/gridsome-plugin-flexsearch/issues/61 needs to be fixed.

**Comment by vjandrei** [comment]
@thetre97 Yes I use "flexsearch": "^0.6.32"
But now I dont see the issue anymore. 🤷‍♂️

**Comment by thetre97** [comment]
Thanks for confirming - I'm afraid I'm not sure what the issue may be, as the plugin shouldn't update the store at all to cause this error. But I'll do some testing to see if I can find the issue.

I have actually recently made some changes to the plugin on the `graphql` branch - if you get the time, could any of you try that updated branch, and see if the issue still exists?
