### ISSUE TITLE
gridsome develop command fails

### ISSUE THREAD

**Issue by sriramgroot** [gridsome/gridsome#1271]
## Description

The `gridsome develop` commands fails

### Steps to reproduce

While running `gridsome develop` it is showing me below mentioned error

### Expected result

Gridsome based app should be displayed properly. but it wasn't working

### Actual result

```
error  in ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "cover_image" on type "Post".

GraphQL request:24:9
23 |         description
24 |         cover_image (width: 770, height: 380, blur: 10)
   |         ^
25 |         path
    at Object.module.exports (/Users/sk/Design/mine/vue-blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:33:23)

 @ ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query 1:0-331 1:347-350 1:352-680 1:352-680
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/Post.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "cover_image" on type "Post".

GraphQL request:71:5
70 |     content
71 |     cover_image (width: 860, blur: 10)
   |     ^
72 |   }
    at Object.module.exports (/Users/sk/Design/mine/vue-blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:33:23)

 @ ./src/templates/Post.vue?vue&type=custom&index=0&blockType=page-query 1:0-330 1:346-349 1:351-678 1:351-678
 @ ./src/templates/Post.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.
```

### Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Edge: 83.0.478.61
    Firefox: 78.0.2
    Safari: 13.1.1
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.1 
    @gridsome/remark-prismjs: ^0.2.0 => 0.2.0 
    @gridsome/source-filesystem: ^0.6.0 => 0.6.2 
    @gridsome/transformer-remark: ^0.3.0 => 0.3.4 
    gridsome: ^0.7.0 => 0.7.19 
  npmGlobalPackages:
    @gridsome/cli: 0.3.3
```

**Comment by Sergix** [comment]
Are you using Ghost as your source?

**Comment by noxify** [comment]
@sriramgroot can we close this issue here, since it's an issue in the starter kit?

**Comment by sriramgroot** [comment]
> Are you using Ghost as your source?

@Sergix No iam not using **Ghost**

**Comment by tnorthcutt** [comment]
@sriramgroot What is your source for the Post content type? If it's Markdown, can you confirm that you have `cover_image` in your frontmatter?
