### ISSUE TITLE
Error: You should provide GraphQLDirective to schemaComposer.addDirective()

### ISSUE THREAD

**Issue by stereokai** [gridsome/gridsome#1279]
## Description
```console
Gridsome v0.7.19

Initializing plugins...
Load sources - 0s
Error: You should provide GraphQLDirective to schemaComposer.addDirective(), but recieved:
  @infer
    at SchemaComposer.addDirective (project/node_modules/graphql-compose/lib/SchemaComposer.js:698:13)
    at addExtensionDirectives (project/node_modules/gridsome/lib/graphql/extensions/index.js:44:20)
    at addDirectives (project/node_modules/gridsome/lib/graphql/extensions/index.js:29:3)
    at createSchema (project/node_modules/gridsome/lib/graphql/createSchema.js:49:3)
    at Schema.buildSchema (project/node_modules/gridsome/lib/app/Schema.js:28:28)
    at Plugins.createSchema (project/node_modules/gridsome/lib/app/Plugins.js:94:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
### Steps to reproduce
```

In `gridsome.server.js`:
```js
module.exports = {
  plugins: [
    {
      use: 'gridsome-source-graphql',
      options: {
        url: 'http://localhost:8888/graphql',
        fieldName: 'gqlFieldName',
        typeName: 'gqlTypeName',
      },
    },
  ],
}
```
`url` is pointing to a local GraphQL server (verified to be working correctly and consumable)

### Expected result

Gridsome should consume the GraphQL properly and load the app

### Actual result

Gridsome throws the error above and exits, does not start app

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.2/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 77.0.1
    Safari: 13.1.2
  npmPackages:
    gridsome: ^0.7.0 => 0.7.19
    gridsome-source-graphql: ~1.0.2 => 1.0.2
```

**Comment by rauschmerscen** [comment]
Plugins are added in gridsome.config.js not gridsome.server.js, if you're actually using `gridsome-source-graphql` then don't use the code in the article I mentioned. I have `gridsome-source-graphql` only temporarily in my packages.json which I plan to remove later.

**Comment by stereokai** [comment]
You're right. Moving the setting to `gridsome.config.js`, however, brings me to this: https://github.com/gridsome/gridsome/issues/967

**Comment by stereokai** [comment]
I ended up solving this by removing all the package locks (yarn, npm, pnpm) and do a fresh reinstall using yarn with these dependencies:
```json
    "@gridsome/source-graphql": "~0.1.0",
    "graphql": "^14.0.0",
    "gridsome": "^0.7.0",
```

Yarn is the only package manager that seemed to work.

**Comment by JuroOravec** [comment]
Ran into same issue. Downgrading `graphql` from v15-something to v14 resolved this.
