### ISSUE TITLE
Schema error when backend adds fields but existing content not re-saved

### ISSUE THREAD

**Issue by tanc** [gridsome/gridsome#128]
## Description

I encountered an error today that confused me for a while, logging it here with the solution in case anyone else comes across it.

The error thrown is:
```
TypeError: Cannot read property 'includes' of undefined
    at fieldValue (/app/agilefront/node_modules/gridsome/lib/graphql/utils/mergeFields.js:36:27)
    at fieldValues (/app/agilefront/node_modules/gridsome/lib/graphql/utils/mergeFields.js:23:16)
    at mergeNodeFields (/app/agilefront/node_modules/gridsome/lib/graphql/utils/mergeFields.js:7:14)
    at module.exports.store (/app/agilefront/node_modules/gridsome/lib/graphql/schema/nodes/index.js:15:20)
    at module.exports (/app/agilefront/node_modules/gridsome/lib/graphql/createSchema.js:12:48)
    at App.createSchema (/app/agilefront/node_modules/gridsome/lib/app/App.js:111:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

My set up is a Drupal backend using JSON API for Gridsome to consume.

The error occurred when Gridsome tried to create the GraphQL schema and was choking on some existing content which had some new fields.

I had created a content type in Drupal, given it a couple of fields, then populated some content. This was working fine in Gridsome. Some time later I added some new fields to the content type and saved one of the existing Drupal nodes with some updated content. At this point Gridsome began to throw the error. Once I debugged and realised which Drupal content type it was having trouble with I tried re-saving all the existing Drupal nodes of that content type. This fixed the issue for me.

### Steps to reproduce

Create a Drupal content type with a single field. Add two Drupal nodes of that content type. Import into Gridsome. Add a new field (maybe with a reference, something like a media field). Update one of the nodes. Import into Gridsome and you should see the error. Note that I haven't tested these steps (Sorry!)

### Expected result

I would expect Gridsome to be able to import the content.

### Actual result

Gridsome threw the error noted above until I had re-saved all the nodes of the changed content type.

**Comment by tanc** [comment]
It appears the issue may be worse than I thought in that the error came back once I re-saved the node which had information in the newly added field while the other nodes did not. I had to add some dummy content in the new field to each of the other nodes for the error to go. I think this needs some more investigation...
