### ISSUE TITLE
ReferenceError: document is not defined when deploy at Vercel or Netlify

### ISSUE THREAD

**Issue by yanuaraditia** [gridsome/gridsome#1300]
Hello, when I try to deploy an my app to Vercel or Netlify. I had some error below: 
```
16:01:15.167  	Cloning github.com/yanuaraditia/imaka (Branch: master, Commit: da2d78a)
16:01:15.691  	Cloning completed in 524ms
16:01:15.692  	Analyzing source code...
16:01:18.129  	Installing build runtime...
16:01:18.499  	Build runtime installed: 370.377ms
16:01:18.889  	Looking up build cache...
16:01:18.924  	Build cache not found
16:01:19.320  	Installing dependencies...
16:01:19.538  	yarn install v1.22.4
16:01:19.610  	[1/4] Resolving packages...
16:01:20.027  	[2/4] Fetching packages...
16:01:21.174  	warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
16:01:21.761  	warning url-loader@1.1.2: Invalid bin field for "url-loader".
16:01:29.249  	info fsevents@1.2.13: The platform "linux" is incompatible with this module.
16:01:29.249  	info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
16:01:29.259  	info fsevents@2.1.3: The platform "linux" is incompatible with this module.
16:01:29.259  	info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
16:01:29.266  	[3/4] Linking dependencies...
16:01:29.278  	warning " > sass-loader@9.0.3" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
16:01:33.142  	[4/4] Building fresh packages...
16:01:36.109  	Done in 16.57s.
16:01:36.298  	Running "yarn run build"
16:01:36.460  	yarn run v1.22.4
16:01:36.483  	$ gridsome build
16:01:36.780  	Gridsome v0.7.19
16:01:37.109  	Initializing plugins...
16:01:37.161  	Load sources - 0s
16:01:37.184  	Create GraphQL schema - 0.02s
16:01:37.208  	Create pages and templates - 0.02s
16:01:37.229  	Generate temporary code - 0.02s
16:01:37.229  	Bootstrap finish - 0.45s
16:01:37.230  	Compiling assets...
16:01:48.769  	Compile assets - 11.54s
16:01:48.772  	Execute GraphQL (4 queries) - 0s
16:01:49.026  	Could not generate HTML for "/about/":
16:01:49.028  	ReferenceError: document is not defined
16:01:49.028  	    at assets/js/app.fd966610.js:18198:26
16:01:49.028  	    at assets/js/app.fd966610.js:18150:28
16:01:49.028  	    at Object.SHqN (node_modules/vue-infinite-scroll/vue-infinite-scroll.js:5:1)
16:01:49.028  	    at __webpack_require__ (webpack/bootstrap:25:0)
16:01:49.029  	    at Module.O/VM (assets/js/app.fd966610.js:16606:27)
16:01:49.029  	    at __webpack_require__ (webpack/bootstrap:25:0)
16:01:49.029  	    at Object.0 (assets/js/app.fd966610.js:263:18)
16:01:49.029  	    at __webpack_require__ (webpack/bootstrap:25:0)
16:01:49.029  	    at assets/js/app.fd966610.js:118:18
16:01:49.029  	    at Object.<anonymous> (assets/js/app.fd966610.js:121:10)
16:01:49.139  	error Command failed with exit code 1.
16:01:49.139  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
16:01:49.147  	Error: Command "yarn run build" exited with 1
16:01:51.315  	Done with "package.json"
```
Here is my package.json
```
{
  "name": "makaborn",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "axios": "^0.19.2",
    "buefy": "^0.8.20",
    "bulma": "^0.9.0",
    "gridsome": "^0.7.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^9.0.3",
    "vue": "^2.6.11",
    "vue-infinite-scroll": "^2.0.2"
  }
}
```
All my code are working well at local deployment

gridsome.config.js and gridsome.server.js are using default set. I've push the code at [my github](https://github.com/yanuaraditia/imaka)

Thanks for helping me

**Comment by yanuaraditia** [comment]
ReferenceError: document is not defined when deploy at Vercel or Netlify

**Comment by noxify** [comment]
Hi @yanuaraditia 

tested it quickly. Without `testEnvironment: 'node'` in the `gridsome.config.js` I was able to build your site locally without any errors.

With `testEnvironment: 'node'` I got the same error message.

Hope that helps.

If this solves your problem, please close the issue :) 

Regards,
Marcus

**Comment by yanuaraditia** [comment]
> Hi @yanuaraditia
> 
> tested it quickly. Without `testEnvironment: 'node'` in the `gridsome.config.js` I was able to build your site locally without any errors.
> 
> With `testEnvironment: 'node'` I got the same error message.
> 
> Hope that helps.
> 
> If this solves your problem, please close the issue :)
> 
> Regards,
> Marcus

Had some error too when `testEnvironment: 'node'` added 😌

**Comment by yanuaraditia** [comment]
I tried removing `vue-infinite-scroll` and the error was resolved. Thank you for helping me.
