### ISSUE TITLE
Adding @gridsome/source-contentful as plugin causes GraphQL error

### ISSUE THREAD

**Issue by tobiasger** [gridsome/gridsome#1304]
## Description

Adding @gridsome/source-contentful as plugin causes GraphQL error.

### Steps to reproduce

Run `gridsome create project-name` and then `yarn add @gridsome/source-contentful`. When running `gridsome develop`, there is an error in the terminal saying: _GraphQLError: Syntax Error: Unexpected Name "ContentfulModule"_.

### Expected result

Gridsome should complete the build and start watching the project.

### Actual result

Throws an error in the terminal:

```
gridsome develop
Gridsome v0.7.19

Initializing plugins...
Load sources - 0.08s
GraphQLError: Syntax Error: Unexpected Name "ContentfulModule"
    at syntaxError (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseDefinition (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql/language/parser.js:157:16)
    at Parser.many (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql/language/parser.js:111:25)
    at parse (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql/language/parser.js:36:17)
    at TypeMapper.convertSDLTypeDefinition (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql-compose/lib/TypeMapper.js:183:43)
    at Function.createTemp (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql-compose/lib/ObjectTypeComposer.js:91:28)
    at Function.create (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql-compose/lib/ObjectTypeComposer.js:68:21)
    at SchemaComposer.getOrCreateOTC (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/graphql-compose/lib/SchemaComposer.js:446:57)
    at createTypeComposers (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/gridsome/lib/graphql/nodes/index.js:81:41)
    at createNodesSchema (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/gridsome/lib/graphql/nodes/index.js:30:3)
    at createSchema (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/gridsome/lib/graphql/createSchema.js:59:3)
    at Schema.buildSchema (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/gridsome/lib/app/Schema.js:28:28)
    at Plugins.createSchema (/Users/tobeyg/Developer/_Gridsome/cirkelnio/node_modules/gridsome/lib/app/Plugins.js:94:22)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 70.0
    Safari: 12.1.2
  npmPackages:
    @gridsome/source-contentful: ^0.5.3 => 0.5.3 
    gridsome: ^0.7.0 => 0.7.19 
  npmGlobalPackages:
    @gridsome/cli: 0.3.3

**Comment by kylesnod** [comment]
I had this bug as well. Was able to track it down to removing a content type in Contentful. Reproduced by setting up content not changing anything and was able to use source-contentful plugin. Once I deleted a content type from Contentful I was unable to use the plugin further. Switched to source-graphql as a workaround for now. I wasn't able to resolve the issue with the source-contentful-plugin.

**Comment by thebakerdev** [comment]
I'm also getting this kind of error. I'm kinda new in using Gridsome and loving it but this error prevents me from using contentful as my cms. Is there a workaround for this bug?
