### ISSUE TITLE
Compressing html files when running when running the build command

### ISSUE THREAD

**Issue by khalyomede** [gridsome/gridsome#1310]
## Summary

I would like the output html files to be compressed at the maximum when running `gridsome build.

### Basic example

Nothing.

### Motivation

I noticed my CSS and JS files are correctly compressed. However, I still see my html files indented, rather than compressed. Optimizing these little spaces could make us win some more bytes no not download for our users.

**Comment by hjvedvik** [comment]
@khalyomede The default `index.html` file that is used to generate the markup does have some whitespace. But you can try to [override it](https://gridsome.org/docs/overriding-index/) with a custom one without whitespace and see if that will work for you.

But we should look into minifying the `index.html` in Gridsome by default. Plus set `whitespace: 'condense'` for `vue-loader` to only keep minimal whitespace in the rendered Vue markup.

**Comment by devunion** [comment]
@hjvedvik 
> But we should look into minifying the `index.html` in Gridsome by default. Plus set `whitespace: 'condense'` for `vue-loader` to only keep minimal whitespace in the rendered Vue markup.

Do you have any sample code how we can do that for Gridsome? I can't find a way to do that.

**Comment by noxify** [comment]
Hi @devunion 
 
> Plus set whitespace: 'condense' for vue-loader to only keep minimal whitespace in the rendered Vue markup.

You could use `api.configureWebpack` or `api.chainWebpack` to modify the existing webpack config for `vue-loader`.

Related docs:
* https://gridsome.org/docs/config/#configurewebpack
* https://gridsome.org/docs/config/#chainwebpack

Here an example how this can be done: https://github.com/gridsome/gridsome/blob/master/packages/vue-remark/index.js#L261

**Comment by devunion** [comment]
@hjvedvik finally, I'm trying to use the next code to change `vue-loader` options:
```    const loader = config.module
      .rule('compile')
      .use('vue')
      .loader('vue-loader');
    loader.options({ whitespace: 'condense' });
```

But when I'm trying to build the project, the next error occurs:

```    Compile assets - 1.66s
Execute GraphQL (14 queries) - 0.01s
Could not generate HTML for "/ru/privacy-policy":
Error: bundle export should be a function when using { runInNewContext: false }.
    at C:\work\vitya\my_projects\ContentMaster\site\node_modules\vue-server-renderer\build.prod.js:1:78173
    at new Promise (<anonymous>)
    at C:\work\vitya\my_projects\ContentMaster\site\node_modules\vue-server-renderer\build.prod.js:1:78018
    at Object.renderToString (C:\work\vitya\my_projects\ContentMaster\site\node_modules\vue-server-renderer\build.prod.js:1:81553)
    at render (C:\work\vitya\my_projects\ContentMaster\site\node_modules\gridsome\lib\server\createRenderFn.js:36:28)
    at Object.exports.render (C:\work\vitya\my_projects\ContentMaster\site\node_modules\gridsome\lib\workers\html-writer.js:37:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@ build: `gridsome build`
```

I've updated `postcss-loader` to the latest version because I saw that it can cause this error. But it is still here.

**Comment by noxify** [comment]
Hi @devunion 

- where did you added the code? 
- could you share the complete code snippet? 

Thanks

**Comment by devunion** [comment]
> Hi @devunion
> 
> * where did you added the code?
> * could you share the complete code snippet?
> 
> Thanks

@noxify 
I've added it in gridsome.config.js:
```
  chainWebpack: config => {
    config.resolve.alias.set('@customPageImage', '@/../static/images/pages');
    // config.resolve.alias.set('@customPageImage', '@/../content/pages');
    config.resolve.alias.set('@node', '@/../node_modules');
    config.module
      .rule('css')
      .oneOf('normal')
      .use('postcss-loader')
      .tap(options => {
        options.plugins.unshift(...[
          require('postcss-import'),
          require('postcss-nested'),
        ]);

        if (process.env.NODE_ENV === 'production') {
          options.plugins.push(...[
            require('@fullhuman/postcss-purgecss')({
              content: [
                'src/assets/**/*.css',
                'src/**/*.vue',
                'src/**/*.js'
              ],

              whitelist: ['svg-inline--fa'],
              whitelistPatterns: [/shiki/, /fa-$/]
            })
          ]);
        }
        return options;
      });

    // console.log('Getting loader...');

    const loader = config.module
      .rule('compile')
      .use('vue')
      .loader('vue-loader');

    loader.options({ whitespace: 'condense' });

    config
      .plugin('compress')
      .use(CompressionPlugin);
  }
```

**Comment by noxify** [comment]
Hey @devunion 

I have tested it quickly with the following:

```js
//gridsome.config.js 

const merge = require('webpack-merge')

module.exports = {
  siteName: 'Gridsome',
  plugins: [],
  chainWebpack(config) {
    config.module
      .rule('vue')
      .use('vue-loader')
      .tap(options => merge(options, {
        compilerOptions: {
          whitespace: 'condense'
        }
      }));
    
    return config
  }
}

```

Here the difference in the `index.html` after running `gridsome build`.

Left: without the `whitespace` definition ( which is the same as `whitespace: 'preserve'` )
Right: with `whitespace: 'condense'`

![image](https://user-images.githubusercontent.com/521777/103173989-c7bb5200-485e-11eb-8983-e4ee30ded54a.png)

**Comment by noxify** [comment]
I checked also, that the config was set as expected with the following code:

```js
//gridsome.config.js 

configureWebpack(config) {
    console.log(config.module.rules[0].use[1].options.compilerOptions);
  },
```

The result was the following:

```
{
  preserveWhitespace: false,
  modules: [
    { transformNode: [Function: transformNode] },
    { postTransformNode: [Function: postTransformNode] }
  ],
  whitespace: 'condense'
}
```

**Comment by noxify** [comment]
But tbh, i can't see any difference in the file size.
I have tested it with the default starter without any customizations.

**Comment by devunion** [comment]
@noxify thank you for the detailed response. I also tried to play with the different options, but was unable to get better compression. At the moment my output looks like this: 
![image](https://user-images.githubusercontent.com/1061496/103463652-eb8b0600-4d3e-11eb-9a51-6649556ab52f.png)

As you see, it can be minified much more effective. I'm trying to get the best possible compression result.

Another idea was to use weback-compression-plugin:

```
    config
      .plugin('compress')
      .use(CompressionPlugin);
```

But it also does not work. Do you have an idea how to improve compression rate?

**Comment by devunion** [comment]
@noxify I tried several ways to enable minification with Terser or `html-minimizer-webpack-plugin`. Something like this:

```
    config.optimization.minimize(true);

    config.optimization
      .minimizer('html')
      .use(HtmlMinimizerPlugin);
```

But both fails with the same error:
![image](https://user-images.githubusercontent.com/1061496/103464467-f052b880-4d44-11eb-89a9-d2858bd8136e.png)

I assume that the problem is related to Gridsome itself. Do you have any ideas how to enable better minification at least for HTML?
