### ISSUE TITLE
Error: Failed to install dependencies with npm. Please enter site directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

### ISSUE THREAD

**Issue by 010arya010** [gridsome/gridsome#1337]
hi. i install gridsome, when i want to create project with below command:
`gridsome create project`
i recive this error:
 Clone https://github.com/gridsome/gridsome-starter-default.git 1.74s
❯ Update project package.json 0.01s
❯ Install dependencies
  • Installing dependencies with npm...
Error: Failed to install dependencies with npm. Please enter newf directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

    Exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@gridsome/cli/lib/commands/create.js:106:17)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
 
arya@anonymous:~/tst$

-------------------------- 
what is problem?

ofcourse my OS is ubuntu!

**Comment by 010arya010** [comment]
solved it by my self.
use yarn instead npm.
