### ISSUE TITLE
Can not convert field to InputType when generating GraphQL Schema

### ISSUE THREAD

**Issue by dylanmcgowan** [gridsome/gridsome#1338]
## Description
When running `gridsome develop` the following error occurs:

This does not happen on v0.7.19... What changed?

```
Gridsome v0.7.20

Initializing plugins...
[sanity] Watch mode enabled, starting a listener
Load sources - 0.55s
Error: Can not convert field 'SanityHomepage.modules' to InputType
It should be ObjectType or InterfaceType, but got 
ListComposer({ ofType: UnionTypeComposer({ _gqcFallbackResolveType: null, schemaComposer: SchemaComposer, _gqType: SanityHeroBannerOrHeroColorOrHeroSquareOrImageTextOrOffsetModuleOrRecentPostsOrRichTextOrSideBySideOrSkewedModule, _gqcTypes: Set({  }), _gqcTypeResolvers: Map({  }), _gqcExtensions: Object({ isCustomType: true }) }) })
    at /Users/dylanmcgowan/projects/kiah/web/node_modules/graphql-compose/lib/utils/toInputType.js:99:15
    at Array.forEach (<anonymous>)
    at toInputObjectType (/Users/dylanmcgowan/projects/kiah/web/node_modules/graphql-compose/lib/utils/toInputType.js:89:14)
    at ObjectTypeComposer.getInputTypeComposer (/Users/dylanmcgowan/projects/kiah/web/node_modules/graphql-compose/lib/ObjectTypeComposer.js:889:71)
    at createFilterInput (/Users/dylanmcgowan/projects/kiah/web/node_modules/gridsome/lib/graphql/filters/input.js:19:42)
    at createNodesSchema (/Users/dylanmcgowan/projects/kiah/web/node_modules/gridsome/lib/graphql/nodes/index.js:38:5)
    at createSchema (/Users/dylanmcgowan/projects/kiah/web/node_modules/gridsome/lib/graphql/createSchema.js:59:3)
    at Schema.buildSchema (/Users/dylanmcgowan/projects/kiah/web/node_modules/gridsome/lib/app/Schema.js:28:28)
    at Plugins.createSchema (/Users/dylanmcgowan/projects/kiah/web/node_modules/gridsome/lib/app/Plugins.js:94:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Steps to reproduce

- Run gridsome v0.7.20 with the sanity source plugin

### Expected result

Gridsome should build like this,
```
Initializing plugins...
[sanity] Watch mode enabled, starting a listener
Load sources - 0.61s
Create GraphQL schema - 0.13s
Create pages and templates - 0.1s
Generate temporary code - 0.03s
Bootstrap finish - 2.94s
```

### Actual result

Full output above : `Error: Can not convert field to InputType, It should be ObjectType or InterfaceType, but got 
ListComposer`

### Environment

```
Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 75.0
    Safari: 13.1
  npmGlobalPackages:
    @gridsome/cli: 0.3.4
```

**Comment by hjvedvik** [comment]
Something changed in the latest version of `graphql-compose`, which Gridsome uses to create the GraphQL schema. I'll do some debugging to find out why it happens early next week. But in the meanwhile, you can downgrade the package if you use Yarn by doing this in `package.json`:

```json
{
  "resolutions": {
    "gridsome/graphql-compose": "7.20.1"
  }
}
```

**Comment by chrispreisler** [comment]
I also have the same error, but only when build the page in Netlify. Unfortunately your fix with the resolutions doesn't work. Did you have the time to look into that bug?

2:26:11 PM: Error: Can not convert field 'KirbyPage.components' to InputType
2:26:11 PM: It should be ObjectType or InterfaceType, but got

Thanks for your help.

**Comment by dylanmcgowan** [comment]
My project still does not build, the error points to graphql-compose:

```
Error: Type with name "SanityDocument" does not exists
2:47:30 PM:     at SchemaComposer.get (/opt/build/repo/web/node_modules/graphql-compose/lib/TypeStorage.js:44:13)
2:47:30 PM:     at ThunkComposer._ThunkComposer.ThunkComposer [as _thunk] (/opt/build/repo/web/node_modules/graphql-compose/lib/TypeMapper.js:585:34)
2:47:30 PM:     at ThunkComposer.get ofType [as ofType] (/opt/build/repo/web/node_modules/graphql-compose/lib/ThunkComposer.js:20:34)
2:47:30 PM:     at ThunkComposer.getType (/opt/build/repo/web/node_modules/graphql-compose/lib/ThunkComposer.js:46:17)
2:47:30 PM:     at ObjectTypeComposer.getFieldConfig (/opt/build/repo/web/node_modules/graphql-compose/lib/ObjectTypeComposer.js:343:18)
2:47:30 PM:     at processObjectTypeFields (/opt/build/repo/web/node_modules/gridsome/lib/graphql/createSchema.js:288:38)
2:47:30 PM:     at processTypes (/opt/build/repo/web/node_modules/gridsome/lib/graphql/createSchema.js:276:9)
2:47:30 PM:     at createSchema (/opt/build/repo/web/node_modules/gridsome/lib/graphql/createSchema.js:64:3)
2:47:30 PM:     at Schema.buildSchema (/opt/build/repo/web/node_modules/gridsome/lib/app/Schema.js:28:28)
2:47:30 PM:     at Plugins.createSchema (/opt/build/repo/web/node_modules/gridsome/lib/app/Plugins.js:94:22)
2:47:30 PM:     at process._tickCallback (internal/process/next_tick.js:68:7)
```
