### ISSUE TITLE
Gridsome Build fails due to TypeError: Url must be a string. Received undefined

### ISSUE THREAD

**Issue by tscole** [gridsome/gridsome#1358]
## Description

Running Gridsome Build fails while generating the sitemap with the following error:
`Generate /sitemap.xml (18622 pages)
TypeError: Url must be a string. Received undefined`

### Steps to reproduce

Run `gridsome build` with sitemap module installed... using mysql source. This may be specific to my data :)

### Expected result

Generate a site map

### Actual result

```
Load sources - 81.75s
Create GraphQL schema - 0.57s
Create pages and templates - 0.71s
Generate temporary code - 0.12s
Bootstrap finish - 94.11s
Compile assets - 25.08s
Execute GraphQL (18622 queries) - 89.88s
Render HTML (18622 files) - 175.43s
Process files (0 files) - 0s
Process images (244 images) - 17.99s
Generate /sitemap.xml (18622 pages)
TypeError: Url must be a string. Received undefined
    at normalize (/Users/timcole/Development/weareworship/waw-gridsome/node_modules/url-join/lib/url-join.js:32:15)
    at /Users/timcole/Development/weareworship/waw-gridsome/node_modules/url-join/lib/url-join.js:75:12
    at /Users/timcole/Development/weareworship/waw-gridsome/node_modules/sitemap/lib/sitemap.js:194:21
    at Array.forEach (<anonymous>)
    at Sitemap.toString (/Users/timcole/Development/weareworship/waw-gridsome/node_modules/sitemap/lib/sitemap.js:186:15)
    at /Users/timcole/Development/weareworship/waw-gridsome/node_modules/@gridsome/plugin-sitemap/index.js:60:43
    at Plugins.run (/Users/timcole/Development/weareworship/waw-gridsome/node_modules/gridsome/lib/app/Plugins.js:141:17)
    at async module.exports (/Users/timcole/Development/weareworship/waw-gridsome/node_modules/gridsome/lib/build.js:42:3)
```

### Environment

```

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 76.0.1
    Safari: 12.1.2
  npmPackages:
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0 
    gridsome: ^0.7.0 => 0.7.19 
    gridsome-source-mysql: ^1.5.4 => 1.5.4 
  npmGlobalPackages:
    @gridsome/cli: 0.3.3
```

It appears changing

if (component === '') { continue; }

in node_modules/url-join/lib/url-join.js to: 

if (component === '' || component === undefined) { continue; }

Allows the sitemap to be built.

**Comment by noxify** [comment]
Hey @tscole could you please post your `gridsome.config.js` ?

**Comment by tscole** [comment]
```
// This is where project configuration and plugin options are located.
// Learn more: https://gridsome.org/docs/config

// Changes here require a server restart.
// To restart press CTRL + C in terminal and run `gridsome develop`
const tailwindcss = require("tailwindcss");

module.exports = {
  siteName: 'Gridsome',
  siteUrl: process.env.SITE_URL,
  plugins: [
    {
      use: '@gridsome/plugin-sitemap', // see https://www.wavrin.com/adding-plugins-to-a-gridsome-site/
      options: {
        config: {
          "/*": {
            changefreq: "weekly",
            priority: 0.5,
          },
        },
        // include: [],
        options: {
          cacheTime: 600000, // default
        },
        staticUrls: [
          {}
        ]
      }
    },
    {
    use: 'gridsome-source-mysql',
    options: {
      connection: {
        // Do NOT adjust database settings here. Use a .env file!
        host: process.env.MYSQL_SERVER,
        port: process.env.MYSQL_PORT,
        user: process.env.MYSQL_USER,
        password: process.env.MYSQL_PASSWORD,
        database: process.env.MYSQL_DATABASE,
        connectionLimit: 10
      },
      ignoreImages: false, // Do not download any images
      imageDirectory: 'sql_images',
      regex: /()_\d(.(jpg|png|svg|jpeg))/i, // Default false
      queries: [ // required
        {
          name: 'Song',
          route: '/songs/:path',
          path: 'fullname',
          sql: `SELECT Song.ID AS id, Song.title as title, ccli, writerlist, sheetmusicpreview, slug, artist, SongBackground as about, SongArrangement.chords, OriginalKeyChords as chordsKey, OriginalKeySheetMusic as sheetmusicKey, SongArrangement.Tempo as tempo, copyrightyear, copyrightline, videos.video_ids, themes.theme_ids, bibleverses.verses as bibleverses, products.product_ids, CONCAT("https://www.weareworship.com/", filename) as image, ratings.votes as ratingVotes, ratings.val as ratingValue,
          IF((SELECT true FROM HomePage_SongOfTheWeek WHERE NOW() BETWEEN StartDate AND EndDate AND SongArrangementID = SongArrangement.ID), true, false) as freeSong,
          IF((SELECT true FROM HomePage_VintageSongOfTheWeek WHERE NOW() BETWEEN StartDate AND EndDate AND SongArrangementID = SongArrangement.ID), true, false) as freeVintageSong,
          IF((SELECT true FROM HomePage_HymnOfTheWeek WHERE NOW() BETWEEN StartDate AND EndDate AND SongArrangementID = SongArrangement.ID), true, false) as freeHymn,
          IF((SELECT true FROM HomePage_TrendingSongs WHERE SongArrangementID = SongArrangement.ID AND HomePageID = 984), true, false) as popular,
          IF((SELECT true FROM HomePage_NewSongs WHERE SongArrangementID = SongArrangement.ID AND HomePageID = 984), true, false) as new
          FROM Song JOIN SongLyric ON Song.ID = SongLyric.SongID
          JOIN SongArrangement ON SongArrangement.SongLyricID = SongLyric.ID
          LEFT JOIN (
            SELECT SongArrangementID, GROUP_CONCAT(ID) AS 'video_ids'
            FROM ExternalSongResource
            WHERE ExternalSongResourceTypeID IN (9,10,11,12,13,14,15,16)
            GROUP BY SongArrangementID
          ) videos
          ON videos.SongArrangementID = SongArrangement.ID
          LEFT JOIN (
            SELECT SongID, GROUP_CONCAT(SubThemeID) AS 'theme_ids'
            FROM Song_SubThemes
            GROUP BY SongID
          ) themes
          ON themes.SongID = Song.ID
          LEFT JOIN (
            SELECT Song_BibleVerses.SongID, GROUP_CONCAT(BibleBook.Name," ", Chapter, ":", Verse) as verses FROM Song_BibleVerses
            JOIN BibleVerse ON BibleVerse.ID = BibleVerseID
            JOIN BibleBook ON BibleBook.ID = BookID
            GROUP BY Song_BibleVerses.SongID
          ) bibleverses
          ON bibleverses.SongID = Song.ID
          LEFT JOIN (
            SELECT SongLyric.SongID, GROUP_CONCAT(DownloadableProduct.ID) 'product_ids'
            From SongLyric
            JOIN SongArrangement ON SongLyric.ID = SongLyricID
            JOIN DownloadableProduct ON DownloadableProduct.SongArrangementID = SongArrangement.ID
            WHERE ProductTypeID IN (37,38,39)
            GROUP BY SongID
          ) products
          ON products.SongID = Song.ID
        LEFT JOIN SongOfTheWeekImage ON SongArrangement.ID = SongOfTheWeekImage.SongArrangementID
        LEFT JOIN File ON File.ID = SongOfTheWeekImage.PromoImageID
        LEFT JOIN (
        	SELECT SongID, Count(ID) as votes, ROUND(AVG(Amount), 1) as val FROM SongRating GROUP BY SongID
        ) ratings
        ON ratings.SongID = Song.ID
        WHERE SongLyric.Locale = 'en_US' AND SongArrangement.DefaultForLocale = 1;`,
        images: ['image'] // Default []
        },
        {
          name: 'Product',
          sql: 'SELECT DownloadableProduct.ID as id, Title as title, SongArrangementID as arrangementId, DownloadableProduct.Locale as locale, Amount as price, CurrencyCode as currency, ProductTypeID as type FROM DownloadableProduct LEFT JOIN DownloadablePrice ON (DownloadablePrice.DownloadableProductTypeID = ProductTypeID AND DownloadableProduct.Locale = DownloadablePrice.Locale) WHERE ProductTypeID IN (37,38,39);'
        },
        {
          name: 'Video',
          sql: `SELECT ExternalSongResource.ID as id, ExternalResourceID as youtube, ExternalSongResourceTypeID as type, name
            FROM ExternalSongResource
            JOIN ExternalSongResourceType ON ExternalSongResourceTypeID = ExternalSongResourceType.ID
            JOIN SongArrangement ON ExternalSongResource.SongArrangementID = SongArrangement.ID
            JOIN SongLyric ON SongLyricID = SongLyric.ID
            WHERE ExternalSongResourceTypeID IN (9,10,11,12,13,14,15,16) AND Locale = "en_US"`
        },
        {
          name: 'Theme',
          sql: `SELECT SubTheme.id, SubTheme.title as name, Theme.Title as parent, Theme.ID as parentId, LOWER(REPLACE(REPLACE(REPLACE(REPLACE(SubTheme.Title,"&", "and"),"'",""),",","")," ","-")) as slug, song.song_ids FROM SubTheme LEFT JOIN Theme ON ThemeID = Theme.ID
          LEFT JOIN (
            SELECT SubThemeID, GROUP_CONCAT(SongID) AS 'song_ids'
            FROM Song_SubThemes
            GROUP BY SubThemeID
          ) song
          ON song.SubThemeID = SubTheme.ID`
        },
        {
          name: 'WorshipLeader',
          sql: `SELECT SiteTree_Live.ID as id, SiteTree_Live.title, SiteTree_Live.content, URLSegment as slug, CONCAT("https://www.weareworship.com/", filename) as image, songs.song_ids
          FROM ArtistPage_Live
          LEFT JOIN SiteTree_Live ON ArtistPage_Live.ID = SiteTree_Live.ID
          LEFT JOIN File ON File.ID = ThumbnailID
          LEFT JOIN (
            SELECT ArtistPageID, GROUP_CONCAT(SongLyric.SongID) AS 'song_ids'
            FROM ArtistPage_TopSongs
            LEFT JOIN SongArrangement ON SongArrangement.ID = ArtistPage_TopSongs.SongArrangementID
            LEFT JOIN SongLyric ON SongArrangement.SongLyricID = SongLyric.ID
            WHERE SongArrangementID > 0
            GROUP BY ArtistPageID
          ) songs
          ON songs.ArtistPageID = ArtistPage_Live.ID
          WHERE Locale = "en_US";`,
          images: ['image']
        },
        {
          name: 'Article',
          sql: `SELECT SiteTree_Live.ID as id, SiteTree_Live.title, REPLACE(SiteTree_Live.content,"assets/Uploads","https://www.weareworship.com/assets/Uploads") as content, URLSegment as slug, authornames, DATE_FORMAT(PublishDate, '%D %M %Y') as published, category.category_ids, tag.tag_ids
          FROM SiteTree_Live
          JOIN BlogPost_Live on SiteTree_Live.ID = BlogPost_Live.ID
          LEFT JOIN (
            SELECT BlogPostID, GROUP_CONCAT(BlogCategoryID) AS 'category_ids'
            FROM BlogPost_Categories
            GROUP BY BlogPostID
          ) category
          ON category.BlogPostID = BlogPost_Live.ID
          LEFT JOIN (
            SELECT BlogPostID, GROUP_CONCAT(BlogTagID) AS 'tag_ids'
            FROM BlogPost_Tags
            GROUP BY BlogPostID
          ) tag
          ON tag.BlogPostID = BlogPost_Live.ID
          WHERE ClassName = "BlogPost" AND Locale = "en_US"`,
          route: '/learning/articles/:path',
          path: 'URLSegment',
        },
        {
          name: 'Tag',
          sql: `SELECT id, title, URLSegment as slug FROM BlogTag`
        },
        {
          name: 'Category',
          sql: `SELECT id, title, URLSegment as slug FROM BlogCategory WHERE BlogID = 996`
        },
        {
          name: 'SongList',
          sql: `SELECT SiteTree_Live.ID as id, SiteTree_Live.title, IncludedContent as subheading, SidebarHTML as spotify, SiteTree_Live.content, URLSegment as slug, IF(albumCoverUrl IS NOT NULL,albumCoverUrl, IF(File.filename IS NOT NULL,  CONCAT("https://www.weareworship.com/",File.filename),  CONCAT("https://www.weareworship.com/",f.filename))) as image, songs.song_ids
          FROM SongCollection_Live
          JOIN SiteTree_Live ON SongCollection_Live.ID = SiteTree_Live.ID
          LEFT JOIN File f ON f.ID = SongCollection_Live.ThumbnailID
          LEFT JOIN Album_SongCollections ON SongCollectionID = SiteTree_Live.ID
          LEFT JOIN Album ON Album.ID = AlbumID
          LEFT JOIN File ON File.ID = ArtworkID
          LEFT JOIN (
            SELECT SongCollectionID, GROUP_CONCAT(SongLyric.SongID) AS 'song_ids'
            FROM SongArrangement_SongCollections
            LEFT JOIN SongArrangement ON SongArrangement.ID = SongArrangement_SongCollections.SongArrangementID
            LEFT JOIN SongLyric ON SongArrangement.SongLyricID = SongLyric.ID
            WHERE SongArrangementID > 0
            GROUP BY SongCollectionID
          ) songs
          ON songs.SongCollectionID = SiteTree_Live.ID
          WHERE Locale = "en_US"`,
          images: ['image']
        }
      ]
    }
  }],
  templates: {
    Song: [{
        path: '/songs/chords/:slug',
        component: './src/templates/Song.vue'
      },
      {
        name: 'sheet-music',
        path: '/songs/sheet-music/:slug',
        component: './src/templates/SheetMusic.vue'
      }
    ],
    Theme: [
        {
          name: 'theme',
          path: '/songs/themes/:slug',
          component: './src/templates/Theme.vue'
        }
    ],
    WorshipLeader: [{
      path: '/worship-leaders/:slug',
      component: './src/templates/WorshipLeader.vue'
    }],
    Article: [{
      path: '/learning/articles/:slug',
      component: './src/templates/Article.vue'
    }],
    SongList: [{
      path: '/song-lists/:slug',
      component: './src/templates/SongList.vue'
    }],
  },
  css: {
    loaderOptions: {
      postcss: {
        plugins: [
          tailwindcss
        ],
      },
    },
  },
}
```

**Comment by noxify** [comment]
Based on the plugin description:

> Make sure `siteUrl` is set in your project config....

Can you please recheck that `process.env.SITE_URL` contains a valid value?
Maybe set a static value to make sure, everything is working as expected.

**Comment by tscole** [comment]
Doubled checked `process.env.SITE_URL` - same error
Tried a static value - same error

**Comment by hjvedvik** [comment]
@tscole There is an empty object in the `staticUrls` array. Could that be the problem?

**Comment by tscole** [comment]
I hadn't noticed that. Removed and trying again... (build takes several minutes - the site is quite large)

**Comment by tscole** [comment]
@hjvedvik that was it - thanks for you help
