### ISSUE TITLE
Dynamic page routing on Windows fails

### ISSUE THREAD

**Issue by japalekhin** [gridsome/gridsome#1359]
## Description

On Windows, when running (`npm start`/`gridsome develop`) a gridsome project with dynamic routes (file based dynamic pages) where the path contains a variable in the middle (example below), path expansion fails and the whole script just crashes.

Example page path: `./src/pages/admin/users/[id]/Edit.vue`

### Steps to reproduce

1. Create a gridsome project ON WINDOWS.
0. Create a dynamic route where the parameter is at the middle (on a directory not on a file) for example: `./src/pages/something/[identifier]/action/SubAction.vue`.
0. Run the project in dev mode (`npm start`/`gridsome develop` or your favorite script config).

### Expected result

The script should run and the development server with hot reload should finish setting up and a website served on `http://localhost:8080`.

### Actual result

The script crashes with an error:

```
D:\Projects\node_modules\snapdragon\lib\parser.js:473
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^

Error: no parsers registered for: "]"
    at parse (D:\Projects\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (D:\Projects\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (D:\Projects\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (D:\Projects\node_modules\braces\lib\braces.js:40:45)
    at Braces.parse (D:\Projects\node_modules\braces\lib\braces.js:66:26)
    at Braces.expand (D:\Projects\node_modules\braces\lib\braces.js:87:18)
    at create (D:\Projects\node_modules\braces\index.js:142:15)
    at memoize (D:\Projects\node_modules\braces\index.js:298:13)
    at Function.braces.create (D:\Projects\node_modules\braces\index.js:165:10)
    at Function.braces.expand (D:\Projects\node_modules\braces\index.js:81:17)
    at getDirParts (D:\Projects\node_modules\gridsome\node_modules\chokidar\index.js:435:31)
    at FSWatcher.<anonymous> (D:\Projects\node_modules\gridsome\node_modules\chokidar\index.js:452:24)
    at D:\Projects\node_modules\gridsome\node_modules\readdirp\readdirp.js:220:72
    at Array.filter (<anonymous>)
    at D:\Projects\node_modules\gridsome\node_modules\readdirp\readdirp.js:220:12
    at D:\Projects\node_modules\gridsome\node_modules\readdirp\readdirp.js:193:38
```

### Environment

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.1 => 0.6.3
    gridsome: ^0.7.0 => 0.7.21
```

**Comment by RonelTheGreat** [comment]
I got the same error with windows 10

**Comment by ryanrhay** [comment]
same here - got this error also :(

**Comment by hjvedvik** [comment]
I think I've found a solution for this. I will do some more tests and publish an update tomorrow.

**Comment by japalekhin** [comment]
@hjvedvik thank you for the time you put on this. now how can i test this to confirm?

**Comment by hjvedvik** [comment]
@japalekhin Would be great if you can test it. I haven't been able to tests it on Windows myself yet, but I saw that other frameworks have done the same change to fix a similar issue. You can try to create a page at for example, `src/pages/[id]/user.vue`. It shouldn't fail with the latest version of Gridsome.
