### ISSUE TITLE
ReferenceError: icon is not defined when setting icon in gridsome.config.js

### ISSUE THREAD

**Issue by ameistad** [gridsome/gridsome#138]
## Description
Getting reference error when setting the icon property in gridsome.config.js

### Steps to reproduce

 Set icon in gridsome.config.js
```
module.exports = {
  siteName: 'Gridsome',
  icon: 'src/new-favicon.png',
  plugins: []
}
```

And run `gridsome develop` on a new project.

### Expected result

Project should use the new icon.

### Actual result
Getting the error:
```
ReferenceError: icon is not defined
    at normalizeIconsConfig (/Users/andreas/projects/gridsome/gridsome/gridsome/lib/app/loadConfig.js:215:56)
    at module.exports (/Users/andreas/projects/gridsome/gridsome/gridsome/lib/app/loadConfig.js:98:17)
    at new App (/Users/andreas/projects/gridsome/gridsome/gridsome/lib/app/App.js:27:19)
    at module.exports (/Users/andreas/projects/gridsome/gridsome/gridsome/lib/app/index.js:9:15)
    at module.exports (/Users/andreas/projects/gridsome/gridsome/gridsome/lib/develop.js:14:21)
    at args (/Users/andreas/projects/gridsome/gridsome/gridsome/index.js:41:12)
    at Command.program.command.description.option.option.action.args (/Users/andreas/projects/gridsome/gridsome/gridsome/index.js:8:44)
    at Command.listener (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:654:12)
    at Command.parse (/usr/local/lib/node_modules/@gridsome/cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/@gridsome/cli/bin/gridsome.js:48:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

**Comment by taigadigital** [comment]
Same thing here.
