### ISSUE TITLE
gridsome build: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by cnglen** [gridsome/gridsome#1385]
$ gridsome build
Gridsome v0.7.22

Initializing plugins...
Load sources - 0.03s
Create GraphQL schema - 0.06s
Create pages and templates - 0.03s
Generate temporary code - 0.02s
Bootstrap finish - 0.45s
Compile assets - 4.85s
Execute GraphQL (13 queries) - 0.97s
Could not generate HTML for "/Categories/technology/":
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/foo/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/unsupportedIterableToArray.js
require() of ES modules is not supported.
require() of /home/foo/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/unsupportedIterableToArray.js from /home/foo/node_modules/_vue-server-renderer@2.6.12@vue-server-renderer/build.prod.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename unsupportedIterableToArray.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/foo/node_modules/_@babel_runtime@7.12.5@@babel/runtime/helpers/esm/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/foo/node_modules/_vue-server-renderer@2.6.12@vue-server-renderer/build.prod.js:1:77645
    at Object.YbeR (webpack:/external "@babel/runtime/helpers/esm/unsupportedIterableToArray":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.gD92 (assets/js/app.2b1b6273.js:2076:35)
    at __webpack_require__ (webpack/bootstrap:25:0)

**Comment by cco3** [comment]
If you are trying to make js modules using the built in support in the latest node, you will have to change the file extension like the error message says.  Otherwise, you'll need some babel plugin like [babel-plugin-transform-es2015-modules-commonjs](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs) (I think that's the one)

**Comment by zalazhar** [comment]
Having the same issues. @cco3 , installing the plugin didn't help for me. Is it possible to share a more extensive how to?

**Comment by zalazhar** [comment]
> Having the same issues. @cco3 , installing the plugin didn't help for me nor changing the file extension. Is it possible to share a more extensive how to?

OK, migrated back to 0.7.14 as a workaround....

**Comment by jbuhacoff** [comment]
I had a similar issue related to ES modules while building, and it pointed to the import statement of the same Babel runtime helper, but the error message was different:

```
./node_modules/@babel/runtime/helpers/esm/unsupportedIterableToArray.js:1
import arrayLikeToArray from "@babel/runtime/helpers/esm/arrayLikeToArray";
       ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at C:\Users\jonat\Documents\Cryptium\Workspace\tigercomet\website-info-broken-html5\node_modules\vue-server-renderer\build.prod.js:1:77645
    at Object.YbeR (webpack:/external "@babel/runtime/helpers/esm/unsupportedIterableToArray":1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module.O/VM (assets/js/app.16186c58.js:2115:35)
```

I thought it was a babel issue so I [asked](https://github.com/babel/babel/discussions/12549#discussioncomment-238798) over there, but someone helpfully pointed me at this ticket.

Downgrading gridsome from 0.7.23 to 0.7.22 fixed the issue for me.

**Comment by jbuhacoff** [comment]
Content of `babel.config.js` in my project:

```
module.exports = {
    presets: [
        '@vue/babel-preset-app',
    ],
};
```

**Comment by jbuhacoff** [comment]
In common:

* related to how the Babel ESM runtime helpers are used
* workaround was to downgrade gridsome
* @babel/runtime v7.12.5

Differences:

* the error message: "Error [ERR_REQUIRE_ESM]: Must use import to load ES Module" vs "SyntaxError: Unexpected identifier"
* gridsome version: for @cnglen it was to downgrade from v0.7.22 to 0.7.14, and for me it was to downgrade from 0.7.23 to 0.7.22

**Comment by jbuhacoff** [comment]
When I try the build with gridsome v0.7.23, the errors only appear when I do a production build by running `gridsome build`. When I run the development server locally by running `gridsome develop`, everything is working fine.

**Comment by logue** [comment]
It worked when I changed the extension of the script using the require statement to `.mjs`.

ex. gridsome.server.js -> gridsome.server.mjs

**Comment by martijnmichel** [comment]
Same error on 0.7.14 and 0.7.22 and .23

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Martijn\Apps\sonid.app\node_modules\@babel\runtime\helpers\esm\unsupportedIterableToArray.js
require() of ES modules is not supported.
require() of C:\Users\Martijn\Apps\sonid.app\node_modules\@babel\runtime\helpers\esm\unsupportedIterableToArray.js from C:\Users\Martijn\Apps\sonid.app\node_modules\vue-server-renderer\build.prod.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename unsupportedIterableToArray.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Martijn\Apps\sonid.app\node_modules\@babel\runtime\helpers\esm\package.json.

**Comment by jbuhacoff** [comment]
I originally asked about my issue on the [babel discussion forum](https://github.com/babel/babel/discussions/12549) and there was a suggestion there by @nicolo-ribaudo to set the environment variable `VUE_CLI_BABEL_TRANSPILE_MODULES=true` during the build.

In a new shell 1:

```
rm -rf dist node_modules package-lock.json
npm install
gridsome build
# fails with syntax error
rm -rf dist
export VUE_CLI_BABEL_TRANSPILE_MODULES=true
gridsome build
# fails with syntax error
```

Continuing in the same shell 1 or in a new shell 2:

```
rm -rf dist node_modules package-lock.json
export VUE_CLI_BABEL_TRANSPILE_MODULES=true
npm install
gridsome build
# works
```

It seems the variable has to be set before `npm install`, but I don't know why.

In a new shell 3, without the variable set, but keeping the node modules already installed, and the first build already done:

```
gridsome build
# works
rm -rf dist
gridsome build
# works
rm -rf node_modules package-lock.json
npm install
gridsome build
# fails with syntax error
```

If I go back to the shell 2 steps above, then it works again.

But here's a twist, in a new shell 4:

```
rm -rf dist node_modules package-lock.json
export VUE_CLI_BABEL_TRANSPILE_MODULES=true
npm install
```

Then a new shell 5, with the variable not set:

```
gridsome build
# fails with syntax error
export VUE_CLI_BABEL_TRANSPILE_MODULES=true
gridsome build
# fails with syntax error
rm -rf dist
gridsome build
# fails with syntax error
```

It just looks crazy but I can repeat these sequences and the results are consistent on my system. Somehow, that variable needs to be set before `npm install` and also before the first `gridsome build`, or I get the syntax error. But after that's happened, I can do subsequent `gridsome build` without that variable set and it works.

Can anyone else reproduce this?

**Comment by martijnmichel** [comment]
on Windows: 
export : The term 'export' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ export VUE_CLI_BABEL_TRANSPILE_MODULES=true

**Comment by jbuhacoff** [comment]
In Windows PowerShell you'd write:

```
$env:VUE_CLI_BABEL_TRANSPILE_MODULES="true"
```

Or if you're using the regular command line:

```
set VUE_CLI_BABEL_TRANSPILE_MODULES=true
```

**Comment by jbuhacoff** [comment]
Also, on Windows you'd replace `rm -rf` with `del -Recurse -Force`

**Comment by milindsingh** [comment]
Thanks @jbuhacoff  

> Downgrading gridsome from 0.7.23 to 0.7.22 fixed the issue for me.

This fixed the issue!

**Comment by martijnmichel** [comment]
Have tried a dozen of variations, sometimes it works, sometimes it doesnt :(

**Comment by milindsingh** [comment]
Working on local, failing on netlify! How to fix the error!

**Comment by jbuhacoff** [comment]
Have you set the environment variable in your [netlify config file](https://docs.netlify.com/configure-builds/file-based-configuration/#build-settings)?

**Comment by milindsingh** [comment]
.env file is working in netlify and all env variables are having values.

Do you know any specific I need to add?

**Comment by jbuhacoff** [comment]
Did you already add `VUE_CLI_BABEL_TRANSPILE_MODULES=true`? I don't know if it will solve anything for you, but if it does please share your results.

**Comment by milindsingh** [comment]
Thanks @jbuhacoff It worked.

It's very difficult to identify whats not working, but working versions are:

gridsome: 7.14
node: 12.20

.env
`VUE_CLI_BABEL_TRANSPILE_MODULES=true`

**Comment by jbuhacoff** [comment]
Since Gridsome depends on the latest Babel version, which in turn depends on these ESM helpers in `@babel/runtime`, I'm wondering if there's any situation where someone would **not** want to transpile those helpers? It seems to me like that would be the exception.

To spare people from the pain of finding out about this environment variable, it might be helpful for Gridsome to check if `VUE_CLI_BABEL_TRANSPILE_MODULES` is not defined or empty, define it with a value of `true` as a default, and let developers override it by setting `VUE_CLI_BABEL_TRANSPILE_MODULES=false` if they don't want to transpile the helpers for some reason.

**Comment by oripka** [comment]
Setting this option in my .env file has side effects . It creates one big app.js file (in my case over one megabyte when using vue-remark).

**Comment by jbuhacoff** [comment]
Thanks for mentioning that. I had a similar experience, my `app.js` file was 3MB. But I couldn't build without setting that variable.

Since then, I upgraded to:

* node v16.6.1
* @babel/runtime-corejs3 v7.15.3
* webpack v4.46.0

I'm able to build now without setting the variable, and my `app.js` file is 1.1 MB with the rest is spread out in the other files, for a total of only 2 MB instead of 3 MB.

I'm not getting the error anymore. Build is working with both Gridsome v0.7.22 and v0.7.23.
