### ISSUE TITLE
source-strapi plugin cannot fetch new content-type (strapi-plugin-comments)

### ISSUE THREAD

**Issue by kwiat1990** [gridsome/gridsome#1400]
Hi,

I wanted to add comments plugin to my page, so in order to do that I've installed `strapi-plugin-comments`. 

Strapi part works: I can see a new content-type for comments in my admin panel and all the enabled endpoints are accessible from the outside world. New comments can be added and retrieved as well, so backend certainly works as intended. A one more step is left though. It seems like Gridsome's `souce-strapi` plugin cannot fetch the new content-type and I don't know whose fault it is: the way the content-type was exposed by `strapi-plugin-comments` or how Gridsome's plugin handle content-types created by Strapi plugins.

![image](https://user-images.githubusercontent.com/19494075/102252361-47aff680-3f06-11eb-9c56-48915fe60342.png)

My `gridsome.config.js`:
```
...
plugins: [
    {
      use: "@gridsome/source-strapi",
      options: {
        apiURL: `http://localhost:1337`,
        queryLimit: 1000, // Defaults to 100
        contentTypes: ["Article", "Category", "Tag"],
        singleTypes: ["About", "Footer"],
      },
    },
  ],
```

Logs from `npm run develop`:
```
gridsome develop

Gridsome v0.7.23

Initializing plugins...
Fetching data from Strapi (http://localhost:1337)
Unable to get content type (Comments). Did you enable permissions in the Strapi admin for this?
Error: Request failed with status code 404
    at createError (/home/mateusz.kwiatkowski/Playground/marketingowy-wir/frontend/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/mateusz.kwiatkowski/Playground/marketingowy-wir/frontend/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/mateusz.kwiatkowski/Playground/marketingowy-wir/frontend/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1226:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! marketingowy-wir@1.0.0 develop: `gridsome develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marketingowy-wir@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by OzzyTheGiant** [comment]
@kwiat1990 I too got that permissions error. Not sure which of these did the trick but here's what I did:

- After `singleTypes` use this (note that those constants are defined in a .env file, and those credentials are the credentials for your user account on Strapi admin panel):
```javascript
loginData: {
    identifier: process.env.STRAPI_USER,
    password: process.env.STRAPI_PASS
}
```

- Also, make sure that you define at least one route for eachStrapi model that you will be including in GraphQL, specifically a route in which you can fetch ALL the records for that model. Example:
```json
// api/pages/config/routes.json
[
    {
        "method": "GET",
        "path": "/pages",
        "handler": "PageController.getPages"
    },
]
```
```javascript
// api/pages/controllers/PageController.js
module.exports = {
    async getPages(ctx) {
        const entities = await strapi.services.page.find(ctx.query);
        return entities.map(entity => sanitizeEntity(entity, {model: strapi.models.page}));
    }
};
```

**Comment by kwiat1990** [comment]
From what I know I get the error because endpoints from comments plugin are not a normal content type and only custom endpoints (which are created directly by yourself in Strapi) can be queried. 

I also must admit that I don't understand your example. For comments there is neither a model nor a controller (the entire code for it is available only under `extensions`). What I tried to do is to use Gridsome's `loadSource` method to fetch all comments for a given article and add a new field with all the comments. It didn't work.

**Comment by OzzyTheGiant** [comment]
@kwiat1990 Oh I see, you are using a comments plugin. Not exactly sure how that differs from the rest of the app but I think the structure is roughly the same so I would think the controllers and routes still apply.

Either way, I actually gave up on the strapi plugin. I noticed that Gridsome's GraphQL messes up my data big time, so I'm gonna have to use Data Store API to define the types and relations.

**Comment by kwiat1990** [comment]
@OzzyTheGiant yeah those are two different problems I suppose. I would be interested to know how is Gridsome messing your data. To be honest in my project everything (my custom content types) works just fine and I can't really complain.

**Comment by OzzyTheGiant** [comment]
@kwiat1990 I'm using a Page model to store a web page's content (title, meta-description, and body). The body field is a dynamic zone which uses multiple components, each of which define what content and how that content is laid out on said web page. Unfortunately, graphql doesn't play nice with these dynamic zones because of the wildly different fields each component has, not to mention I can't tell them apart, not unless I use interfaces which I'm still working on. Then on a Category model, I'm using that to get all Dishes that belong to that category (this is for a restaurant template website), so related models can't be fetched with Categories unless I define the graphql type explicitly. Lastly, I have a Locations model that specifies all restaurant locations; it's a simple model but for some reason graphql put the zip code on the name field and filled all other field values with 1's and 0's which to me seems like the plugin is broken or something.

**Comment by PaperPlaneSoftware** [comment]
@kwiat1990 I'm having the exact same problem as you. Did you manage to solve it in the end? I've added a controller and route for getting all the comments for the comments type added by the plugin but it still doesn't work.

**Comment by kwiat1990** [comment]
@PaperPlaneSoftware sadly no. I've tried to manually fetch and add comments to the article but it didn't work. Eventually I decided to make it dynamic and fetch comments in mounted hook. I would say that for my needs it's the better solution.

**Comment by PaperPlaneSoftware** [comment]
@kwiat1990 I agree, I've decided to handle comments dynamically too, after thinking about it for a minute it's clearly the best way to handle comments!

**Comment by JerrySun-X** [comment]
@kwiat1990 
The problem can be solved by restoring the hosts file

**Comment by kwiat1990** [comment]
> @kwiat1990
> The problem can be solved by restoring the hosts file
Hi @JerrySun-X , I'm afraid I don't get entirely what you mean. Could you elaborate a little bit more on this one?
