### ISSUE TITLE
gridsome develop error in new project

### ISSUE THREAD

**Issue by EnglederLucas** [gridsome/gridsome#1413]
## Description

When I run `gridsome develop` in my newly created project I get an error that the module `color-string` cannot be found.
### Steps to reproduce

I created a project with `gridsome create personal-site`, changed directory and then ran gridsome develop. I tried to install gridsome with both yarn and npm (different directories, no mixing).

```
> yarn global add @gridsome/cli
> gridsome create personal-site
> cd personal-site
> gridsome develop
```

#### Tried Fixes

* Running `yarn` 
* Running `yarn add color-string`

### Expected result

It should start the development server.

#### Console Output

```
Error: Cannot find module 'color-string'
Require stack:
- A:\Coding\PersonalSite\personal-site-npm\node_modules\gridsome\lib\app\loadConfig.js
- A:\Coding\PersonalSite\personal-site-npm\node_modules\gridsome\lib\app\index.js
- A:\Coding\PersonalSite\personal-site-npm\node_modules\gridsome\lib\develop.js
- A:\Coding\PersonalSite\personal-site-npm\node_modules\gridsome\index.js
- C:\Users\Lucas\AppData\Local\Yarn\Data\global\node_modules\@gridsome\cli\bin\gridsome.js     
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (A:\Coding\PersonalSite\personal-site-npm\node_modules\gridsome\lib\app\loadConfig.js:7:21)                                                                         pp\loadConfig.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

```
### Environment

```

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 AMD Ryzen 3 1300X Quad-Core Processor
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.0.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gridsome: ^0.7.0 => 0.7.23
```

#### Probably related issue
https://github.com/gridsome/gridsome/issues/252

**Comment by noxify** [comment]
OT: is Drive `A` not the floppy disk? Maybe you have to insert disk 2 🤔

**Comment by EnglederLucas** [comment]
`A` is my HDD. I don't think it has anything to do with it, I have many projects on this drive and never had any problems.
