### ISSUE TITLE
Gridsome develop failing with TypeError

### ISSUE THREAD

**Issue by JLeeeeeeee** [gridsome/gridsome#1439]
`gridsome develop` is giving me the following error:

> TypeError:   Object.fromEntries is not a function
at collectionStore.data.map.node   (/home/ots-orch/my-gridsome-site/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:70:34)
at Array.map (<anonymous>)
at getStoreCollection   (/home/ots-orch/my-gridsome-site/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:65:35)
at collection   (/home/ots-orch/my-gridsome-site/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:134:14)
at   /home/ots-orch/my-gridsome-site/node_modules/gridsome-plugin-flexsearch/node_modules/p-map/index.js:57:28

### Steps to reproduce
Run `gridsome develop` from the command line.

I'm currently on gridsome v.0.7.23 and @gridsome/cli v0.3.4.

**Comment by cameronrr** [comment]
Which version of NodeJS are you running (`node -v` in command line)? If it's 12, try installing [version 14](https://nodejs.org/en/download/) and see if that resolves it.
