### ISSUE TITLE
Following doc to add tailwind unable to build

### ISSUE THREAD

**Issue by mhamri** [gridsome/gridsome#1441]
## Description

I followed the documentation to add the tailwind manually and the development is just fine, but can't create a build because of this error 

```
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-purgecss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (C:\repo\mhamri\node_modules\postcss-loader\node_modules\postcss\lib\processor.js:167:15)
    at new Processor (C:\repo\mhamri\node_modules\postcss-loader\node_modules\postcss\lib\processor.js:56:25)
    at postcss (C:\repo\mhamri\node_modules\postcss-loader\node_modules\postcss\lib\postcss.js:55:10)
    at C:\repo\mhamri\node_modules\postcss-loader\src\index.js:140:12
    at C:\repo\mhamri\node_modules\webpack\lib\NormalModule.js:316:20
    at C:\repo\mhamri\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\repo\mhamri\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\repo\mhamri\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\repo\mhamri\node_modules\postcss-loader\src\index.js:208:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mhamri@ build: `gridsome build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mhamri@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amrim\AppData\Roaming\npm-cache\_logs\2021-02-13T04_29_10_473Z-debug.log
```

looking at purgecss documentation, it's already an archived repo and there is a whole new usage and repo for that

appreciate if you guide me and also update the doc 

### Steps to reproduce

follow the doc to add the tailwind manually and then run `npm run build`

### Expected result

a dist folder generated

### Actual result

throwing error

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.63)
  npmPackages:
    @gridsome/plugin-critical: ^0.2.0 => 0.2.0
    @gridsome/plugin-google-analytics: ^0.1.2 => 0.1.2
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4
    gridsome: ^0.7.0 => 0.7.23
    gridsome-plugin-remark-prismjs-all: ^0.3.5 => 0.3.5
```

**Comment by mhamri** [comment]
solved the problem by installing older version of purgecss

`npm i -D @fullhuman/postcss-purgecss@2.x.x`

but still the doc is broken, need to be updated

**Comment by noxify** [comment]
Hey @mhamri 

Could you provide the needed changes in the docs as PR in the `gridsome/gridsome.org` repo?

Would be awesome if you can help here to improve the documentation:)

Thanks!

**Comment by mhamri** [comment]
@noxify sure, should I make PR to https://github.com/gridsome/gridsome.org?

**Comment by noxify** [comment]
@mhamri - yes

Can we close this issue here?

**Comment by mhamri** [comment]
sure
