### ISSUE TITLE
Latest `@gridsome/source-wordpress` version breaks the build

### ISSUE THREAD

**Issue by hacknug** [gridsome/gridsome#146]
## Description

Updating `@gridsome/source-wordpress` to v0.2.0 breaks the build because its now trying to access an API endpoint that requires authentication. This is the API's raw response:

```json
{
    "code": "rest_user_cannot_view",
    "message": "Sorry, you are not allowed to list users.",
    "data": {
        "status": 401
    }
}
```

### Steps to reproduce

Have a Gridsome site using the latest version of the `@gridsome/source-wordpress` plugin (v0.2.0). Try running `gridsome develop` without doing any auth stuff besides adding the plugin's config like shown on the docs: https://gridsome.org/plugins/source-wordpress

Here's a link to my repo in case you prefer cloning it and updating the dependency: https://github.com/hacknug/klayaya

### Expected result

This should only throw a notice after being unable to access a given endpoint. Erroring here breaks the build which is unnecessary imho since I don't event do anything with users on my site.

### Actual result

Gridsome throws an error which break the build completely. Here's the error output on the console:

```node
Error: Failed to fetch: https://dev.nestorvera.com/klayaya/wp-json/wp/v2/users, Sorry, you are not allowed to list users.
    at WordPressSource.fetch (/Users/nestor/Code/klayaya/node_modules/@gridsome/source-wordpress/index.js:170:15)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by hacknug** [comment]
Works perfectly. Thank you!
