### ISSUE TITLE
```gridsome build``` it's returning an error when importing from api that includes PDF

### ISSUE THREAD

**Issue by ricardov03** [gridsome/gridsome#1475]
## Description

Gridsome build's returning an error if the API imported includes a .PDF extension on it.

### Steps to reproduce

gridsome.server.js
```javascript
...
  // Catalogs from STRAPI Endpoint
  api.loadSource(async (actions) => {
    const token = await getAccessToken()
    const Catalogs = await getContent('/catalogs', token)

    const collection = actions.addCollection('Catalogs')

    for (const catalog of Catalogs) {
      collection.addNode({
        id: catalog.id,
        title: catalog.title,
        description: catalog.description,
        home: catalog.homepage ? true : false,
        state: catalog.state ? true : false,
        portrait: process.env.GRIDSOME_STRAPI_ENDPOINT + catalog.portrait.url,
        catalog: process.env.GRIDSOME_STRAPI_ENDPOINT + catalog.catalog.url,
      })
    }
  })
...
```

I'm loading a source from API (Strapi). This source includes an item with a PDF extension on it. I know this is important, because I'm trying to delete the extension on the collection map, but doesn't work. ```gridsome develop``` it's compiling but when execute ```gridsome build``` this error it's displayed:

```batch
❯ gridsome build
Gridsome v0.7.23

Initializing plugins...
Load sources - 1.15s
Create GraphQL schema - 0.1s
Create pages and templates - 0.07s
Generate temporary code - 0.04s
Bootstrap finish - 1.94s
Compile assets - 36.62s
Execute GraphQL (15 queries) - 0.02s
Could not generate HTML for "/":
Error: Cannot find module './.pdf'
    at webpackContextResolve (webpack:/node_modules/gridsome/lib/webpack/loaders/assets-loader.js ^\.\/.*\.pdf$:42:0)
    at webpackContext (webpack:/node_modules/gridsome/lib/webpack/loaders/assets-loader.js ^\.\/.*\.pdf$:37:0)
    at assets/js/page--src--pages--index-vue.d33856d8.js:420:2818
    at a.pe [as _l] (/Users/ricardov/Projects/_Jamstack/disesa/node_modules/vue/dist/vue.runtime.common.prod.js:6:15887)
    at a.render (src/pages/Index.vue?2860:1:2563)
    at a.t._render (/Users/ricardov/Projects/_Jamstack/disesa/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /Users/ricardov/Projects/_Jamstack/disesa/node_modules/vue-server-renderer/build.prod.js:1:70575
    at Yi (/Users/ricardov/Projects/_Jamstack/disesa/node_modules/vue-server-renderer/build.prod.js:1:67139)
    at io (/Users/ricardov/Projects/_Jamstack/disesa/node_modules/vue-server-renderer/build.prod.js:1:70551)
    at ro (/Users/ricardov/Projects/_Jamstack/disesa/node_modules/vue-server-renderer/build.prod.js:1:70182)
```

### Expected result

Build correctly. I'm able to use this information on the development mode.

### Actual result

Error: Cannot find module './.pdf'

### Environment

```batch
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.1 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 83.0
    Safari: 14.0.3
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    gridsome: ^0.7.21 => 0.7.23
    gridsome-helper-json: ^1.0.3 => 1.0.3
    gridsome-plugin-gtm: ^0.1.1 => 0.1.1
```

**Comment by ricardov03** [comment]
I found that I was rewriting a collection using the same name on the new loadSource. 😞
