### ISSUE TITLE
Could not generate HTML for "/"?

### ISSUE THREAD

**Issue by seriiserii825** [gridsome/gridsome#1476]
## Description

Localy works fine, but when i tried to build, i get this error. 

### Steps to reproduce
```
Gridsome v0.7.23

Initializing plugins...
Loading data from http://wp-rewind.seriiburduja.ru
Load sources - 10.55s
Create GraphQL schema - 0.35s
Create pages and templates - 0.03s
Generate temporary code - 0.03s
Bootstrap finish - 11.41s
Compile assets - 5.78s
Execute GraphQL (3 queries) - 0.01s
Could not generate HTML for "/":
ReferenceError: document is not defined
    at a.isMobileVersion (src/components/navigation/Header.vue:77:0)
    at a.isMobileVersion (/home/serii/Sites/jamstack/rewind/gr-rewind/node_modules/vue/dist/vue.runtime.common.prod.js:6:29698)
    at a.Headervue_type_template_id_569be152_render (src/components/navigation/Header.vue?12dc:1:15545)
    at a.t._render (/home/serii/Sites/jamstack/rewind/gr-rewind/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /home/serii/Sites/jamstack/rewind/gr-rewind/node_modules/vue-server-renderer/build.prod.js:1:70575
    at Yi (/home/serii/Sites/jamstack/rewind/gr-rewind/node_modules/vue-server-renderer/build.prod.js:1:67139)
    at io (/home/serii/Sites/jamstack/rewind/gr-rewind/node_modules/vue-server-renderer/build.prod.js:1:70551)
    at ro (/home/serii/Sites/jamstack/rewind/gr-rewind/node_modules/vue-server-renderer/build.prod.js:1:70182)
    at _t.eo [as renderNode] (/home/serii/Sites/jamstack/rewind/gr-rewind/node_modules/vue-server-renderer/build.prod.js:1:67429)
    at _t.next (/home/serii/Sites/jamstack/rewind/gr-rewind/node_modules/vue-server-renderer/build.prod.js:1:20445)

```
I founded a response to use ClientOnly. 

I neet to change the template, which depends on the size of the browser window.

```
  computed: {
    isMobileVersion() {
      return windwo.innerWidth < 1100
    },
    isHomePage() {
      return this.$router.history.current.path === '/'
    }
  },

```

And i used here 

```
      <MainMenu :class="{'fixed': isMobileVersion && isVisibleMenu}"/>

```

**Comment by iamarpitpatidar** [comment]
seems like a typo but u sure its `window` in here `windwo.innerWidth < 1100`

**Comment by hjvedvik** [comment]
Gridsome generates the HTML in a Node.js environment, where `document` and `window` don't exist. You can use `process.isClient` to determine if the component is rendered in Node.js. Something like this:

```js
computed: {
  isMobileVersion() {
    return process.isClient ? window.innerWidth < 1100 : true
  }
}
```

**Comment by DimaO2** [comment]
it doesn't work ((

> Gridsome generates the HTML in a Node.js environment, where `document` and `window` don't exist. You can use `process.isClient` to determine if the component is rendered in Node.js. Something like this:
> 
> ```js
> computed: {
>   isMobileVersion() {
>     return process.isClient ? window.innerWidth < 1100 : true
>   }
> }
> ```

**Comment by DimaO2** [comment]
< ClientOnly >
    < your-component/ >
< /ClientOnly >
