### ISSUE TITLE
Error 500 while fetching from live server with source-graphql

### ISSUE THREAD

**Issue by idesignzone** [gridsome/gridsome#1530]
## Description

back-end: Wordpress, 
plugins: WPGraphQL, ACF Pro, ACF WPGraphql, WPGraphQL Widgets

Grdisome develops and builds locally but after moving Wordpress to live server Gridsome build breaks the server and results in 500.

### Steps to reproduce

Need to setup Wordpress on the live server with mentioned plugins and query using source-graphql. 

### Expected result

Built was successful 

### Actual result

Gridsome v0.7.23

```
Initializing plugins...
Load sources - 0s
Create GraphQL schema - 4.46s
Create pages and templates - 0.99s
Generate temporary code - 0.04s
Bootstrap finish - 6.85s
Error: Response not successful: Received status code 500
    at Object.module.exports (D:\iDesign\Gridbox\Repository\Frontend\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\static-query.js:58:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Environment

System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
  npmPackages:
    @gridsome/source-graphql: ^0.1.0 => 0.1.0
    gridsome: ^0.7.23 => 0.7.23
    gridsome-plugin-uikit: ^1.0.0 => 1.0.0

**Comment by idesignzone** [comment]
This turned out to be a server problem. Server was running out of memory on a query.
