### ISSUE TITLE
Gridsome won't build – Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by djmtype** [gridsome/gridsome#1544]
## Description

My project use to build on a Mac Intel with Node v14.15.

However, Gridsome won't build with Node v15.0.1. I'm also now on an M1 Mac. I had previously fixed the Sharp issue. I removed the package-lock.json file, node modules, etc. Now when trying to run `gridsome build`, I get the following: 

(BTW, Gridsome will still run in development `gridsome develop`.)

```
(node:26617) ExperimentalWarning: AbortController is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Create GraphQL schema - 19.53s
Create pages and templates - 4.75s
Generate temporary code - 0.04s
Bootstrap finish - 27.18s
0% compilingTypeError: Cannot read property 'tapAsync' of undefined
    at /Volumes/Evo/Sites/mtype-alpha/node_modules/vue-server-renderer/server-plugin.js:52:39
    at SyncHook.eval [as call] (eval at create (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
    at SyncHook.lazyCompileHook (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/lib/Compiler.js:631:26)
    at /Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/lib/Compiler.js:662:28)
    at /Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/lib/Compiler.js:529:11)
    at /Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/lib/Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at /Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/lib/Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Volumes/Evo/Sites/mtype-alpha/node_modules/gridsome/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
```

Paste the information here as shown by `gridsome info`

```
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 91.0
    Safari: 14.1.1
  npmPackages:
    @gridsome/remark-prismjs: ^0.5.0 => 0.5.0
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/source-graphql: ^0.1.0 => 0.1.0
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4
    gridsome: ^0.7.0 => 0.7.23
    gridsome-source-rss: ^1.0.0 => 1.0.0
    gridsome-source-static-meta: ^1.0.1 => 1.0.1
```

**Comment by djmtype** [comment]
BTW, I didn't have the issue when installed my dependencies with `yarn install` only `npm install`

**Comment by michto01** [comment]
I have the same problem with following `gridsome info`:

```

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: 3.0.1 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.0.1
  npmPackages:
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4 
    gridsome: ^0.7.23 => 0.7.23 
    gridsome-plugin-algolia: ^2.1.4 => 2.1.4 
    gridsome-plugin-i18n: ^1.6.0 => 1.6.0 
    gridsome-plugin-ogp: ^0.0.14 => 0.0.14 
    gridsome-plugin-robots-txt: ^1.0.2 => 1.0.2 
    gridsome-plugin-rss: ^1.2.0 => 1.2.0 
    gridsome-plugin-tailwindcss: ^4.1.1 => 4.1.1 
    gridsome-plugin-typescript: ^0.4.0 => 0.4.0 
    gridsome-source-graphql-prismic: ^0.1.6 => 0.1.6 
```

**Comment by rasensio** [comment]
Same issue here 

`  System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 17.3.0 - /usr/local/bin/node
    npm: 8.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Edge: 97.0.1072.55
    Firefox: 91.4.1
    Safari: 15.2
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.2 
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0 
    @gridsome/remark-prismjs: ^0.5.0 => 0.5.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4 
    gridsome: ^0.7.23 => 0.7.23 
    gridsome-plugin-gtag: ^0.1.10 => 0.1.10 
  npmGlobalPackages:
    @gridsome/cli: 0.3.4`

**Comment by gregorso** [comment]
Same by me:
gridsome info 

  System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    gridsome: ^0.7.0 => 0.7.23 
    gridsome-plugin-typescript: ^0.4.0 => 0.4.0 
  npmGlobalPackages:
    @gridsome/cli: 0.3.4

**Comment by steffchep** [comment]
Same issue here - any solutions?

System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  Binaries:
    Node: 16.3.0 - ~\AppData\Local\Volta\tools\image\node\16.3.0\node.EXE
    Yarn: 1.22.5 - C:\Program Files\Volta\yarn.EXE
    npm: 7.20.2 - ~\AppData\Local\Volta\tools\image\npm\7.20.2\bin\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
  npmPackages:
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4
    gridsome: ^0.7.0 => 0.7.23
    gridsome-helper-json: ^1.0.3 => 1.0.3
    gridsome-plugin-pwa: ^0.0.21 => 0.0.21

**Comment by dj-rabel** [comment]
I sadly cannot come up with a solution. But at least I found "the issue" in my project. Gridsome interally uses webpack 4.x, but in mx project I was using webpack 5. Somehow somewhere inside the gridsome dependency chain, some webpack 5 parts pierced threw. As I uninstalled my webpack 5 for testing, I could compile gridsome without problems.
As I said, not a real solution for the general problem. In my case I could switch to webpack 4 on project level and ignore the problem for now. Maybe this works as well for others ...

**Comment by t9luke** [comment]
To anyone else who encounters this issue, I managed to fix it by downgrading the major version of these 2 packages from `5` to `4`:

```json
"@vue/cli-plugin-eslint": "^4.5.16",
"@vue/cli-service": "^4.5.18"
```

The 5th version of each of these depend on Webpack v5. By downgrading them they become dependent on v4.

I'm also using Node v16 (with NVM) and have switched from using Node to Yarn for package installation (due to some unrelated issues).
