### ISSUE TITLE
Gridsom & Shap on Mac mini M1 Broken

### ISSUE THREAD

**Issue by Gradlon** [gridsome/gridsome#1555]
## Description

Since last MacOS Update I can't run gridsome develop.
I have looked arround and havn't found real solutions for this problem.

Any help will be highly appreciated.

### Steps to reproduce

1. npm install --global @gridsome/cli
2. gridsome create my-gridsome-site
3. cd my-gridsome-site
4. gridsome develop
### Expected result

Gridsome start and serves site with hot reloading.

### Actual result

Gridsome v0.7.23

Error:
Something went wrong installing the "sharp" module

dlopen(/Users/gradlon/Desktop/my-gridsome-site/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: /opt/homebrew/opt/openexr/lib/libIlmImf-2_5.25.dylib
  Referenced from: /usr/local/lib/libvips-cpp.42.dylib
  Reason: image not found

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/Users/gradlon/Desktop/my-gridsome-site/node_modules/sharp/lib/constructor.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/gradlon/Desktop/my-gridsome-site/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)

### Environment
Apple Mac Mini M1
OS: BigSure Version 11.5.2 (20G95)
Brew: /opt/homebrew

  System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.22.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Edge: 93.0.961.38
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    gridsome: ^0.7.0 => 0.7.23
  npmGlobalPackages:
    @gridsome/cli: 0.3.4

**Comment by AllanChain** [comment]
https://github.com/lovell/sharp/issues/2794#issuecomment-900360023

Maybe we can upgrade to sharp 0.29 ?

**Comment by Gradlon** [comment]
I tried this already, but did not help.
Still stuck with a broken dev environment.

**Comment by david-gagne** [comment]
@Gradlon I experienced the exact same issue a while ago. You can see the issue [here](https://github.com/gridsome/gridsome/issues/1503). Initially, the suggested workaround did fix the problem, but it turned out not to be a lasting fix. I have yet to find an answer to this issue. Hopefully, you will!

**Comment by humblecoder** [comment]
It appears that, despite the latest GH version referencing ﻿`sharp@0.28.1`, the actual `yarn install` pulled version still references `sharp@0.25.4`.  This, even though it claims `"version": "0.7.23"` in `package.json`.

Can we please, please get someone on this?

**Comment by ppierre** [comment]
As a workaround I have change the `package.json` of the project from : 
```json
  "dependencies": {
    "gridsome": "^0.7.23"
  }
```
To :
```json
  "dependencies": {
    "gridsome": "https://gitpkg.now.sh/gridsome/gridsome/gridsome?master"
  }
```

**Comment by david-gagne** [comment]
@ppierre, does this work repeatedly? The workaround I used in the past only worked one time in the same project for some reason.

**Comment by ppierre** [comment]
I haven't a Mac M1 to test it. I have done this on a student's Mac.
It worked : make new project template... Fail at dependency install... Change "gridsome" dependency to point to the sub-package "gridsome" of this repository : It work.

It's juste a workaround using the "live" version from Github because NPM package isn't up-to-date !
IMO it's just a temporary fix in wait of a new NPM package version.

**Comment by dubem-design** [comment]
What is the way forward on this?

**Comment by stared** [comment]
This worked for me: https://github.com/gridsome/gridsome/issues/1519#issuecomment-870039308
