### ISSUE TITLE
Installation problem with sharp and Python 3.x installed

### ISSUE THREAD

**Issue by DavidCouronne** [gridsome/gridsome#156]
## Description

It is not a specific problem to Gridsome: I had the same with Gatsby.

Sharp only support Python 2.7, and when you have Python 3.x installed (Python 3.7 for me), you've got this error:

``` bash
C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
"" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.8.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
``` 

### Solution

Run:

``` bash
npm config set python C:\Python27
```

[https://stackoverflow.com/questions/20454199/how-to-use-a-different-version-of-python-during-npm-install](https://stackoverflow.com/questions/20454199/how-to-use-a-different-version-of-python-during-npm-install)

Maybe add this solution to the docs ?

**Comment by robaxelsen** [comment]
@DavidCouronne Do I understand correctly that the steps to reproduce this would be:

1. Have Python 3.x only installed (and not Python 2.x), or set as system default for python
2. Do `gridsome create my-gridsome-site`
3. Error occurs

I can take a stab at a PR for this, but needs to fully understand the steps first. We should also cover MacOS and Linux, I presume. I can cover Linux, but MacOS I might need help with testing.

**Comment by mario-neuhold** [comment]
I came across the same Python error (invalid syntax) using the latest Python (3.9) und latest Node (15.7.0).
Instead of downgrading Python to 2.x, as suggested in this issue, I tried falling back to Node LTS (14.15.4) first, which is working for me so far 👍
