### ISSUE TITLE
window is not defined when using FirebaseUI

### ISSUE THREAD

**Issue by Arka-cell** [gridsome/gridsome#1561]
## Description

I am getting the error `ReferenceError: window is not defined` when using FirebaseUI. I have tried to use the code inside `process.isClient` as well as inside the component `ClientOnly`.

### Steps to reproduce

Here is my component code:
```html
<template>
  <login id="firebaseui-auth-container"></login>
</template>

<script>
import firebase from "@firebase/app";
import * as firebaseui from "firebaseui";
import "firebaseui/dist/firebaseui.css";

export default {
  name: "LoginSection",
  mounted() {
    if (process.isClient) {
      let ui = firebaseui.auth.AuthUI.getInstance();
      if (!ui) {
        ui = new firebaseui.auth.AuthUI(firebase.auth());
      }
      const uiConfig = {
        signInSuccessUrl: "/profile",
        signInOptions: [
          firebase.auth.FacebookAuthProvider.PROVIDER_ID,
          firebase.auth.GoogleAuthProvider.PROVIDER_ID,
          firebase.auth.EmailAuthProvider.PROVIDER_ID,
        ],
      };
      ui.start("#firebaseui-auth-container", uiConfig);
    }
  },
};
</script>
```

I am importing this component as follows:

```html
<template>
  <div id="login-view" class="container">
    <ClientOnly>
      <LoginSection />
    </ClientOnly>
  </div>
</template>

<script>
import LoginSection from "@/components/LoginSection.vue";
export default {
  metaInfo: {
    title: "Login",
  },
  components: { LoginSection },
};
</script>
```

Finally, I am getting this error when running `gridsome build`:

```bash
Execute GraphQL (6 queries) - 0.01s
Could not generate HTML for "/test-config/":
ReferenceError: window is not defined
    at assets/js/app.9a554a75.js:44855:28
    at Object.yXDX (node_modules/dialog-polyfill/dialog-polyfill.js:738:1)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.I5iV (node_modules/firebaseui/dist/esm.js:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.O/VM (assets/js/app.9a554a75.js:30125:16)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.0 (assets/js/app.9a554a75.js:1765:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at assets/js/app.9a554a75.js:118:18
```

**Comment by AllanChain** [comment]
Seems firebaseui's problem and you can try https://github.com/firebase/firebaseui-web/issues/213#issuecomment-367451139
