### ISSUE TITLE
Gridsome CLI failed to install dependencies with npm

### ISSUE THREAD

**Issue by Sylk** [gridsome/gridsome#1588]
## Description

Ubuntu build essentials are required to install through gridsome CLI. 

### Steps to reproduce

Install gridsome through cli on a clean ubuntu version, with clean LTS node. 
Then use Gridsome cli to make a new project.

### Expected result

A properly built gridsome project.

### Actual result

It shouldn't spew errors and say it fails like so:

`❯ gridsome create gridsome-test
❯ Clone https://github.com/gridsome/gridsome-starter-default.git 0.47s
❯ Update project package.json 0s
❯ Install dependencies
  • Installing dependencies with npm...
Error: Failed to install dependencies with npm. Please enter gridsome-test directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

    Exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@gridsome/cli/lib/commands/create.js:106:17)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)`

### Environment

N - LTS
Ubuntu - LTS
Terminal - Microsoft Terminal WSL2 Ubuntu

**Comment by mulder21c** [comment]
I have same problem too on same environment.

**Comment by dev23jjl** [comment]
Hey @Sylk and @mulder21c

The reason you are having this problem is that Gridsome has numerous prerequisites in order to install its dependencies. For example, you need more than just Node.js installed on your machine. You'll also need Python and Visual Studio installed on the machine that you're running. In my case, it got to be a bit too much, however, don't worry - I switched back from running VS Code on my laptop to using [Gitpod](https://gitpod.io) (cloud-based VS Code). It gives you full access to a terminal - so no more need of hastily installing all the prerequisites to use Gridsome. Plus, it's a lot faster when it comes to frontend development, VS Code was a bit slow at installing dependencies and running the `gridsome develop` command - but Gitpod is superfast. Plus, it's totally free and there are self-hostable versions of it as well. In the end, it's your choice whatever you decide to do. You can either install the other prerequisites on your machine or use Gitpod.

Glad to help 😉,
dev23jjl

**Comment by jasperyzh** [comment]
> i switched my node version from the latest to 14.18.1 and things began working for me

- Install NVM to switch between nodejs version, start .exe with Run as Administrator
- if NVM "access denied": uninstall nvm-setup.exe, reinstall setup with "Run as administrator"

**Comment by Emilsone** [comment]
I had this same issue, but I resolved it after installing yarn and running the project with yarn instead of NPM. So you should try using yarn it will help.

**Comment by MarcoGriep88** [comment]
Same issue on WSL Ubuntu 20.04

**Comment by MarcoGriep88** [comment]
npm install --global yarn
cd myproject
yarn install

worked for me

**Comment by knightknight** [comment]
Just tried this today on WSL 2 and used `nvm use v14.18.1` and worked as per the [instructions](https://gridsome.org/docs/). 

However I was using node v18.16.0 and was getting error on the `gridsome develop` stage.

```
desktop:~$ node --version
v18.16.0
desktop:~$ yarn --version
1.22.19
desktop:~$ nvm --version
0.39.3
desktop:~$ yarn global add @gridsome/cli
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "@gridsome/cli@0.3.4" with binaries:
      - gridsome
Done in 1.76s.
desktop:~$ gridsome create demo-gridsome-site
❯ Clone https://github.com/gridsome/gridsome-starter-default.git 0.7s
❯ Update project package.json 0s
❯ Install dependencies 28.37s

  - Enter directory cd demo-gridsome-site
  - Run gridsome develop to start local development
  - Run gridsome build to build for production

desktop:~$ cd demo-gridsome-site/
desktop:~/demo-gridsome-site$ gridsome develop
Gridsome v0.7.23

Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.03s
Create pages and templates - 0.03s
Generate temporary code - 0.04s
Bootstrap finish - 0.6s
10% building 1/1 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/<user-name>/demo-gridsome-site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/<user-name>/demo-gridsome-site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
10% building 1/3 modules 2 active ...site/node_modules/webpack/hot/dev-server.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/<user-name>/demo-gridsome-site/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/<user-name>/demo-gridsome-site/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/<user-name>/demo-gridsome-site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/<user-name>/demo-gridsome-site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/<user-name>/demo-gridsome-site/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
```

**Comment by dev23jjl** [comment]
Hi @knightknight,

Gridsome hasn't been receiving proper maintenance for the past few years. As you can see, the last commit was in September of 2022 and the last release was long before then in 2020. It appears that the devs have walked away from the project for some reason and seem to no longer be able to maintain it. The reason that you are experiencing an error is that Gridsome does not support using versions of Node above v16 (being that it hasn't been updated for 3 years). Therefore, you must downgrade Node to v16 to successfully develop and build Gridsome. However, it might be recommended to find a different framework since Gridsome doesn't appear to be going to get more updates anytime soon. In this case, I would recommend another Vue-based framework such as [Nuxt](https://nuxt.com/) or [îles](https://iles.pages.dev/).

**Comment by knightknight** [comment]
@dev23jjl, thanks for the update.
