### ISSUE TITLE
Use @gridsome\source-strapi: TypeError: docs.forEach is not a function

### ISSUE THREAD

**Issue by Suwings** [gridsome/gridsome#1590]
## Description

I want to build a CMS using Gridsome and Strapi. When I use the @gridsome/source-strapi plug-in, the data cannot be imported.

The error is as follows:

```
PS C:\Workspace\my-gridsome-site> gridsome develop
Gridsome v0.7.23

Initializing plugins...
Fetching data from Strapi (http://localhost:1337/api)
TypeError: docs.forEach is not a function
    at C:\Workspace\my-gridsome-site\node_modules\_@gridsome_source-strapi@0.2.0@@gridsome\source-strapi\index.js:40:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Plugins.run (C:\Workspace\my-gridsome-site\node_modules\_gridsome@0.7.23@gridsome\lib\app\Plugins.js:141:11)
```

Strapi has been launched.
visit http://127.0.0.1:1337/api/blog-posts
```json
{"data":[{"id":1,"attributes":{"title":"TestArticle2","createdAt":"2021-12-03T02:11:03.034Z","updatedAt":"2021-12-03T03:10:21.841Z","publishedAt":"2021-12-03T02:11:36.622Z","date":"2021/1/1","text":"sssssssssssssssssss"}},{"id":2,"attributes":{"title":"TestArticle1","createdAt":"2021-12-03T02:11:15.365Z","updatedAt":"2021-12-03T03:10:14.606Z","publishedAt":"2021-12-03T02:11:33.755Z","date":"2021/1/1","text":"sfooooooooo"}},{"id":3,"attributes":{"title":"TestArticle3","createdAt":"2021-12-03T02:11:26.609Z","updatedAt":"2021-12-03T03:10:29.575Z","publishedAt":"2021-12-03T02:11:39.189Z","date":"2021/1/3","text":"xxxxxxxxxxxxxxxxxxxxxxxxx"}}],"meta":{"pagination":{"page":1,"pageSize":25,"pageCount":1,"total":3}}}
```

And when I use the following configuration (from the documentation):
```
module.exports = {
  siteName: 'Gridsome',
  plugins: [
    {
      use: '@gridsome/source-strapi',
      options: {
        apiURL: `http://localhost:1337/`,
        queryLimit: 1000, // Defaults to 100
        contentTypes: [`blog-posts`],
      },
    },
  ],
};
```
The following error will appear:
```
Initializing plugins...
Fetching data from Strapi (http://localhost:1337)
Unable to get content type (blog-posts). Did you enable permissions in the Strapi admin for this?
Error: Request failed with status code 404
    at createError (C:\Workspace\my-gridsome-site\node_modules\_axios@0.19.2@axios\lib\core\createError.js:16:15)
    at settle (C:\Workspace\my-gridsome-site\node_modules\_axios@0.19.2@axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Workspace\my-gridsome-site\node_modules\_axios@0.19.2@axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

You must set apiURL to http://localhost:1337/api/, and then you will get a `TypeError: docs.forEach is not a function` error.

Is it because `@gridsome/source-strapi` hasn't been updated for a long time?

What did i do wrong?

### Steps to reproduce

```
npm i @gridsome/source-strapi
gridsome develop
```

### Expected result

Strapi and Gridsome work properly.

### Actual result

```
TypeError: docs.forEach is not a function
    at C:\Workspace\my-gridsome-site\node_modules\_@gridsome_source-strapi@0.2.0@@gridsome\source-strapi\index.js:40:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Plugins.run (C:\Workspace\my-gridsome-site\node_modules\_gridsome@0.7.23@gridsome\lib\app\Plugins.js:141:11)
```

### Environment

```
@gridsome/cli v0.3.4
gridsome v0.7.23
@source-strapi@0.2.0
```

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.17763.831.0)
  npmPackages:
    gridsome: ^0.7.0 => 0.7.23
```

**Comment by Suwings** [comment]
I think I know the problem, maybe it is to use the @gridsome/source-graphql library?
