### ISSUE TITLE
Build not complete with firebase 9

### ISSUE THREAD

**Issue by arnoclr** [gridsome/gridsome#1592]
## Description

My app can't build, but works perfectly on dev server.

```
Could not generate HTML for "/fr/get-started/":
ReferenceError: IDBIndex is not defined
    at Object.Mcsz (node_modules/idb/lib/idb.mjs:87:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.QN+i (assets/js/page--src-pages-get-started-vue.5240b971.js:230:21)
    at __webpack_require__ (webpack/bootstrap:25:0)
```

My code :
```js
import { logEvent } from 'firebase/analytics'
```

I've seen that I can use the webpack lazyloading, but I use the new modular SDK of firebase, with tree shaking and it's seem impossible to use it.

### Steps to reproduce

Install firebase
Import a function from a firebase module

### Environment

```
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.43)
  npmPackages:
    gridsome: ^0.7.0 => 0.7.23
    gridsome-plugin-i18n: ^1.6.0 => 1.6.0
```
(also not working on github actions)

**Comment by UnKnoWn-Consortium** [comment]
IndexedDB is only available at clients' browsers. You need to ensure the function is invoked at client side only. 
FYR https://gridsome.org/docs/client-api/#process-injections

**Comment by arnoclr** [comment]
You can't conditionnaly import scripts with import syntax.

However, I've found a (dirty) solution. I've created a new composant to encapsulate the one that use firebase. So, my code look like this : 

/pages
```html
<template>
  <div>
    <ClientOnly>
      <firebaseComponent />
    </ClientOnly>
  </div>
</template>

<script>
export default {
  components: {
    firebaseComponent: () => import ('~/components/firebaseComponent.vue')
  }
}
</script>
```

/components
```html
...
<script>
import { logEvent } from "firebase/analytics";
...
```

And inside my firebase component, I can use all import I need.

**Comment by UnKnoWn-Consortium** [comment]
Actually you can do a conditional import by leveraging the dynamic imports: ```const { logEvent } = await import("firebase/analytics")```, though you would likely lose the benefit of tree shaking. And I think your solution is pretty neat. 

FYI https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports
