### ISSUE TITLE
gridsome build error

### ISSUE THREAD

**Issue by nothinghalosix** [gridsome/gridsome#1594]
## Description

get an error when gridsome build

TypeError: Cannot read properties of undefined (reading '__esModule')
    at Ue (/Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:24372)
    at /Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:21337
    at /Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394

Node.js v17.2.0

## Repo Link

<https://gitlab.com/nothinghalosix/gridsome-build-fail>

### Environment

System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 17.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 15.2
  npmPackages:
    @gridsome/cli: ^0.3.4 => 0.3.4
    gridsome: ^0.7.0 => 0.7.23
    gridsome-plugin-tailwindcss: ^4.1.1 => 4.1.1

**Comment by a-kriya** [comment]
@nothinghalosix @scottyzen Try pinning `"webpack": "4.46.0"` in your `package.json`, clearing `node_modules` and re-installing.

**Comment by kubo6472** [comment]
> Node.js v17.2.0

Node LTS (16) fixed this exact error for me. Should be probably added to the docs. @nothinghalosix

**Comment by kubo6472** [comment]
> I too am getting the same error when running the build command.
> 
> I'm loading the carousel inside a `<client-only>` element.
> 
> ```
> <client-only>
>     <carousel :autoplay="true" :perPage="1" :autoplayTimeout="5000" :autoplayHoverPause="true">
>         <slide>
>             
>         </slide>
>     </carousel>
> </client-only>
> ```
> 
> ```
> <script>
> import ClientOnly from 'vue-client-only'
> 
> export default {
>     components: {
>         ClientOnly,
>         Carousel: () =>
>             import ('vue-carousel')
>             .then(m => m.Carousel)
>             .catch(),
>         Slide: () =>
>             import ('vue-carousel')
>             .then(m => m.Slide)
>             .catch()
>     }
> }
> </script>
> ```
> 
> Any advice on how to fix or what to change? Thanks.

Hey, check node version

**Comment by keithmclaughlin** [comment]
> > Any advice on how to fix or what to change? Thanks.
> 
> Hey, check node version @keithmclaughlin

node -v = v16.13.1

Updated all dependencies to latest.

Now getting error about vue-cookie-law even though I have that enclosed in a client-only element too *sigh*

**Comment by nothinghalosix** [comment]
Node.js v17.7.2

`<ClientOnly>
            <carousel
              :perPage="1"
              autoplay
              loop
              :autoplayTimeout="2000"
              :paginationPadding="5"
              paginationColor="#FFEB00"
              paginationActiveColor="#000"
            >
              <slide>
                <g-image
                  src="~/assets/images/kabel.jpg"
                  class="w-full"
                  alt=""
                  title=""
                />
              </slide>
              <slide>
                <g-image
                  src="~/assets/images/durchgang.jpg"
                  class="w-full"
                  alt=""
                  title=""
                />
              </slide>
              <slide>
                <g-image
                  src="~/assets/images/baustelle.jpg"
                  class="w-full"
                  alt=""
                  title=""
                />
              </slide>
              <slide>
                <g-image
                  src="~/assets/images/stiegenhaus.jpg"
                  class="w-full"
                  alt=""
                  title=""
                />
              </slide>
            </carousel>
          </ClientOnly>`

`components: {
    Carousel: () =>
      import("vue-carousel")
        .then((m) => m.Carousel)
        .catch(),
    Slide: () =>
      import("vue-carousel")
        .then((m) => m.Slide)
        .catch(),
    MglMap: () =>
      import("vue-mapbox")
        .then((m) => m.MglMap)
        .catch(),
    MglMarker: () =>
      import("vue-mapbox")
        .then((m) => m.MglMarker)
        .catch(),
  },`
