### ISSUE TITLE
gridsome build error

### ISSUE THREAD

**Issue by Buzhifanji** [gridsome/gridsome#1595]
## Description

get an error when gridsome build

assets/js/page--src-templates-markdown-page-vue.6f12e27f.js:618
      this.observer.disconnect(); // And create another one for the next page.
                    ^

TypeError: Cannot read properties of null (reading 'disconnect')
    at a.$route (assets/js/page--src-templates-markdown-page-vue.6f12e27f.js:618:21)
    at Rt (E:\personal-project\blog\node_modules\vue\dist\vue.runtime.common.prod.js:6:11188)
    at ln.run (E:\personal-project\blog\node_modules\vue\dist\vue.runtime.common.prod.js:6:27682)
    at cn (E:\personal-project\blog\node_modules\vue\dist\vue.runtime.common.prod.js:6:25653)
    at Array.<anonymous> (E:\personal-project\blog\node_modules\vue\dist\vue.runtime.common.prod.js:6:12270)
    at qt (E:\personal-project\blog\node_modules\vue\dist\vue.runtime.common.prod.js:6:11671)

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  Binaries:
    Node: 16.11.1 - ~\AppData\Local\Temp\yarn--1639754299233-0.32109436524237767\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1639754299233-0.32109436524237767\yarn.CMD
    npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.57)
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.2 => 0.1.2
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3
    @gridsome/remark-prismjs: ^0.3.0 => 0.3.0
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4
    gridsome: ^0.7.23 => 0.7.23
    gridsome-plugin-tailwindcss: ^2.2.36 => 2.2.48

**Comment by UnKnoWn-Consortium** [comment]
You need to ensure codes involving ```disconnect()``` is executed only at the client side as ```IntersectionObserver``` or ```MutationObserver``` or whatever observer is available at the DOM only. Otherwise those pieces of code are invoked during static generation at the server side where the DOM is not present and result in the reported errors. 

 https://gridsome.org/docs/client-api/#process-injections

**Comment by Buzhifanji** [comment]
Thank you for your prompt reply
