### ISSUE TITLE
New Error (error:0308010C:digital envelope routines::unsupported)

### ISSUE THREAD

**Issue by SSShupe** [gridsome/gridsome#1612]
## Description

I've been using the Breda template to create [this static site](https://newblog.ssshupe.com). It's always worked beautifully. Last time I tried to update the site, however, the `gridsome develop` command threw an error. I've researched and researched but can't find a solution. I've updated everything, deleted the node_modules folder, and reinstalled using yarn, but still get the error repeatedly. I'm stumped.

### Steps to reproduce

Code [https://github.com/SSShupe/sssblog2.git](https://github.com/SSShupe/sssblog2.git)

### Expected result

Should produce local version of site.

### Environment
```
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 17.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.2
    @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3
    @gridsome/remark-prismjs: ^0.3.0 => 0.3.0
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.5.0 => 0.5.0
    @gridsome/vue-remark: ^0.2.1 => 0.2.6
    gridsome: ^0.7.13 => 0.7.23
    gridsome-plugin-remark-shiki: ^0.3.1 => 0.3.1
    gridsome-plugin-rss: ^1.2.0 => 1.2.0
```

### Printout of Error Message
```
PS C:\Users\ssshu\Webdev\sssblog2> gridsome develop
Gridsome v0.7.23

Initializing plugins...
Load sources - 10.27s
Create GraphQL schema - 0.11s
Create pages and templates - 0.07s
Generate temporary code - 0.04s
Bootstrap finish - 11.76s
10% building 1/1 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\ssshu\Webdev\sssblog2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
10% building 1/2 modules 1 active C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack-hot-middleware\client.js?name=app&reload=true&noInfo=truenode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\ssshu\Webdev\sssblog2\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\ssshu\Webdev\sssblog2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\ssshu\Webdev\sssblog2\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
```

**Comment by dev23jjl** [comment]
Hey @SSShupe, this would be because Node 17 is currently not supported with Gridsome - it's a known error. Instead, try it with Node 16.

**Comment by SSShupe** [comment]
Thanks for your quick response. It might be worth adding this information to the "Prerequisites" or "Troubleshooting" page on the Gridsome website. In particular, the "Prerequisites" pages references the requirement to have Node installed, but says nothing about Gridsome not working with Node 17.

**Comment by dev23jjl** [comment]
There are Pull Requests open to update that information on the website, however, Gridsome progress has been somewhat slow and most of the members of Gridsome aren't very active. I would gladly merge such Pull Requests if I had write access to the website repository (I'm not an actual member at Gridsome, but I'm still here to help where I can), but for now, I guess we all just have to be patient - I'm sure that either those Pull Requests will eventually get merged in the or Gridsome will support Node 17 future. I hope that fixes your problem, and as a general rule-of-thumb, unless you need Node 17, the latest LTS version (currently v16) is always going to be the most compatible.

**Comment by SSShupe** [comment]
Yes, the change back to the LTS version of Node fixed my problem. The site works perfectly now. Thanks again @dev23jjl.

I have a stupid question: How does this issue get "closed"? Or should it be closed? I'm more or less an amateur coder so I'm not familiar with the etiquette/procedures surrounding this.

**Comment by dev23jjl** [comment]
@SSShupe, there should be a button at the bottom below the comment box that has an option to close this issue. If there isn't, it is possible that only Gridsome members can close issues. It doesn't necessarily need to be closed, but since other people have had this issue, I would close it so that the Gridsome devs don't have extra duplicate issues to sort through (that is, if you can). Also, don't worry. I'm basically an amateur developer as well, and we all have silly questions sometimes, but either way, it's better to reach out - then next time, you know what to do. It's all part of learning! 😉

**Comment by LorenAmelang** [comment]
I'm seeing this error in Arch Linux which has nodejs 19. 

It also has this installed:
pacman -S -i nodejs-lts-gallium
Repository      : community
Name            : nodejs-lts-gallium
Version         : 16.18.0-1
Description     : Evented I/O for V8 javascript (LTS release: Gallium)
Provides        : nodejs=16.18.0
Conflicts With  : nodejs

Is there some way to tell gridsome to use the 16LTS version?

**Comment by dev23jjl** [comment]
@LorenAmelang, I think you can set the default version of Node.js using an "nvm" command as shown in this article: [https://stackoverflow.com/questions/47190861/how-can-the-default-node-version-be-set-using-nvm](https://stackoverflow.com/questions/47190861/how-can-the-default-node-version-be-set-using-nvm).

**Comment by LorenAmelang** [comment]
@dev23jjl Yes, I actually found nvm in a search binge later. Worked great, and made the default Gridsome install compile properly. 

Unfortunately it did not fix the Bulma part of my project. Does anybody know if calebanthony/gridsome-bulma is the same Bulma as jgtms Bulma? Is there any other Bulma that works with Gridsome?

**Comment by dev23jjl** [comment]
@LorenAmelang Would this help [https://dev.to/zooly/fast-static-site-with-gridsome-and-bulma-in-5-minutes-4md9](https://dev.to/zooly/fast-static-site-with-gridsome-and-bulma-in-5-minutes-4md9)?

**Comment by LorenAmelang** [comment]
> @LorenAmelang Would this help https://dev.to/zooly/fast-static-site-with-gridsome-and-bulma-in-5-minutes-4md9?

Sorry this has taken so long! I really did try to make it work. 

When I try to install buefy, it gets in a loop of "Updating gridsome to 0.7.23" and "Updating gridsome to 0.0.4" with hundreds of lines of errors. I suppose since the basic Gridsome install works, this is a buefy problem? But all the other Bulma alternatives I've tried have similar problems with the current Gridsome...  

And of course Gridsome itself is incompatible with the current node 19, you have to use nvm to hack node back to 16 to even get as far as I have...  

Here's a summary: 

```
[loren@Gazp9 gridsome]$ npm install --global @gridsome/cli

added 182 packages, and audited 183 packages in 5s

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

[loren@Gazp9 gridsome]$ npm audit fix --force
npm WARN using --force Recommended protections disabled.

up to date, audited 104 packages in 474ms

found 0 vulnerabilities
[loren@Gazp9 gridsome]$
```


```
[loren@Gazp9 gridsome]$ gridsome create buefy
❯ Clone https://github.com/gridsome/gridsome-starter-default.git 0.77s
❯ Update project package.json 0s
❯ Install dependencies 42.58s
[loren@Gazp9 gridsome]$ cd buefy
[loren@Gazp9 buefy]$ gridsome develop
Gridsome v0.7.23

Initializing plugins...
Load sources - 0s
Create GraphQL schema - 0.03s
Create pages and templates - 0.03s
Generate temporary code - 0.03s
Bootstrap finish - 0.49s
egrep: warning: egrep is obsolescent; using grep -E

 DONE  Compiled successfully in 2145ms                                                                               4:56:23 PM

  Site running at:
  - Local:                 http://localhost:8080/
  - Network:               http://10.1.1.9:8080/

  Explore GraphQL data at: http://localhost:8080/___explore

 WAIT  Compiling...                                                                                                  4:56:23 PM
 DONE  Compiled successfully in 60ms                                                                                 4:56:23 PM

  Site running at:
  - Local:                 http://localhost:8080/
  - Network:               http://10.1.1.9:8080/

  Explore GraphQL data at: http://localhost:8080/___explore

egrep: warning: egrep is obsolescent; using grep -E
egrep: warning: egrep is obsolescent; using grep -E
^C
[loren@Gazp9 buefy]$
```

--> That Gridsome start page worked!


--> Following https://dev.to/zooly/fast-static-site-with-gridsome-and-bulma-in-5-minutes-4md9

```
[loren@Gazp9 buefy]$ npm install --save buefy

added 2 packages, and audited 1411 packages in 4s

39 vulnerabilities (14 moderate, 22 high, 3 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

```
--> Fix 1:

```
[loren@Gazp9 buefy]$ npm audit fix --force
npm WARN audit Updating gridsome to 0.0.4, which is a SemVer major change.
...
added 546 packages, removed 263 packages, changed 86 packages, and audited 1694 packages in 18s

--> 376 lines of errors...

79 vulnerabilities (1 low, 44 moderate, 23 high, 11 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force
```
--> Fix 2:

```
[loren@Gazp9 buefy]$ npm audit fix --force
npm WARN audit Updating gridsome to 0.7.23, which is a SemVer major change.
...
added 265 packages, removed 571 packages, changed 85 packages, and audited 1388 packages in 25s

--> 155 lines of (different) errors

37 vulnerabilities (14 moderate, 20 high, 3 critical)

To address all issues (including breaking changes), run:

npm audit fix --force
```  
--> Fix 3: 

```
[loren@Gazp9 buefy]$ npm audit fix --force
npm WARN audit Updating gridsome to 0.0.4, which is a SemVer major change.
...
added 571 packages, removed 265 packages, changed 85 packages, and audited 1694 packages in 9s

--> 371 lines of errors, pretty much the same as "Fix 1"

79 vulnerabilities (1 low, 44 moderate, 23 high, 11 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force
[loren@Gazp9 buefy]$
```
--> Gave up since it is going in circles



--> Tried to compile:

```
[loren@Gazp9 buefy]$ gridsome develop
egrep: warning: egrep is obsolescent; using grep -E
Bootstrapping...
Initialize - 0.16s
Run plugins - 0.03s
Create GraphQL schema - 0.01s
Generate temporary files - 0.02s
Bootstrap finish - 0.21s
✖ ｢wdm｣: Hash: 09f13940eb9cac3c686b
Version: webpack 4.46.0
Time: 1500ms
Built at: 12/25/2022 5:14:27 PM
            Asset      Size  Chunks  Chunk Names
_assets/js/app.js  1.63 MiB     app  app
Entrypoint app = _assets/js/app.js
[0] multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js 52 bytes {app} [built]
[./node_modules/@babel/runtime/helpers/interopRequireDefault.js] 224 bytes {app} [built]
[./node_modules/@babel/runtime/helpers/typeof.js] 554 bytes {app} [built]
[./node_modules/ansi-html-community/index.js] 4.16 KiB {app} [built]
[./node_modules/gridsome/app/app.js] 3.96 KiB {app} [built]
[./node_modules/gridsome/app/entry.client.js] 314 bytes {app} [built]
[./node_modules/strip-ansi/index.js] 154 bytes {app} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.14 KiB {app} [built]
[./node_modules/webpack-hot-middleware/client.js?name=app&reload=true] (webpack)-hot-middleware/client.js?name=app&reload=true 7.67 KiB {app} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.36 KiB {app} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {app} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {app} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {app} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.34 KiB {app} [built]
    + 42 hidden modules

ERROR in ./src/pages/Index.vue?vue&type=template&id=4bc9d7de& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/gridsome/node_modules/.cache/gridsome","cacheIdentifier":"04091edc-vue-loader-template"}!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/vue-loader/lib/loaders/templateLoader.js??ref--6!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=template&id=4bc9d7de&)
Module not found: Error: Can't resolve '~/favicon.png' in '/home/loren/gridsome/buefy/src/pages'
 @ ./src/pages/Index.vue?vue&type=template&id=4bc9d7de& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/gridsome/node_modules/.cache/gridsome","cacheIdentifier":"04091edc-vue-loader-template"}!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/vue-loader/lib/loaders/templateLoader.js??ref--6!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=template&id=4bc9d7de&) 13:11-78
 @ ./src/pages/Index.vue?vue&type=template&id=4bc9d7de&
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js

ERROR in ./src/main.js
Module not found: Error: Can't resolve '~/layouts/Default.vue' in '/home/loren/gridsome/buefy/src'
 @ ./src/main.js 8:38-70
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.37 MiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/gridsome/app/index.dev.html] 292 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 531 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

  Site running at:          http://localhost:8080
  Explore GraphQL data at:  http://localhost:8080/___explore

✖ ｢wdm｣: Hash: ea5dab3c7e2e52e77870
Version: webpack 4.46.0
Time: 20ms
Built at: 12/25/2022 5:14:27 PM
            Asset      Size  Chunks  Chunk Names
_assets/js/app.js  1.63 MiB     app  app
Entrypoint app = _assets/js/app.js
[0] multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js 52 bytes {app}
[./node_modules/@babel/runtime/helpers/interopRequireDefault.js] 224 bytes {app}
[./node_modules/@babel/runtime/helpers/typeof.js] 554 bytes {app}
[./node_modules/ansi-html-community/index.js] 4.16 KiB {app}
[./node_modules/gridsome/app/app.js] 3.96 KiB {app}
[./node_modules/gridsome/app/entry.client.js] 314 bytes {app}
[./node_modules/strip-ansi/index.js] 154 bytes {app}
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.14 KiB {app}
[./node_modules/webpack-hot-middleware/client.js?name=app&reload=true] (webpack)-hot-middleware/client.js?name=app&reload=true 7.67 KiB {app}
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.36 KiB {app}
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {app}
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app}
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {app}
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {app}
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.34 KiB {app}
    + 42 hidden modules

ERROR in ./src/pages/Index.vue?vue&type=template&id=4bc9d7de& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/gridsome/node_modules/.cache/gridsome","cacheIdentifier":"04091edc-vue-loader-template"}!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/vue-loader/lib/loaders/templateLoader.js??ref--6!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=template&id=4bc9d7de&)
Module not found: Error: Can't resolve '~/favicon.png' in '/home/loren/gridsome/buefy/src/pages'
 @ ./src/pages/Index.vue?vue&type=template&id=4bc9d7de& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/gridsome/node_modules/.cache/gridsome","cacheIdentifier":"04091edc-vue-loader-template"}!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/vue-loader/lib/loaders/templateLoader.js??ref--6!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=template&id=4bc9d7de&) 13:11-78
 @ ./src/pages/Index.vue?vue&type=template&id=4bc9d7de&
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js

ERROR in ./src/main.js
Module not found: Error: Can't resolve '~/layouts/Default.vue' in '/home/loren/gridsome/buefy/src'
 @ ./src/main.js 8:38-70
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.37 MiB       1
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/gridsome/app/index.dev.html] 292 bytes {1}
    [./node_modules/lodash/lodash.js] 531 KiB {1}
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {1}
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {1}

^C
[loren@Gazp9 buefy]$
```
--> No response to browser request...  

--> The short version of repeating compile errors: 

ERROR in ./src/pages/Index default.vue
Error: Can't resolve '~/favicon.png' in '/home/loren/gridsome/buefy/src/pages'

ERROR in ./src/main.js
Module not found: Error: Can't resolve '~/layouts/Default.vue' in '/home/loren/gridsome/buefy/src'

--> (Endless struggle with trying to understand the details...)

"ERROR in ./src/pages/Index default.vue" is miserably hard to understand! 
Turns out there is an 'Index default.vue' file that only shows up if you search for the quoted name, because of the space in the middle. 


```
[loren@Gazp9 layouts]$ ls -al /home/loren/gridsome/buefy/src/pages
total 56
drwxr-xr-x 2 loren loren  4096 Dec 27 18:35  .
drwxr-xr-x 7 loren loren  4096 Dec 27 17:53  ..
-rw-r--r-- 1 loren loren   384 Dec 25 16:54  About.vue
-rw-r--r-- 1 loren loren 30642 Dec 25 16:54  favicon.png
-rw-r--r-- 1 loren loren   810 Dec 27 18:35 'Index default.vue'
-rw-r--r-- 1 loren loren  1230 Dec 25 17:25  Index.vue
-rw-r--r-- 1 loren loren   263 Dec 25 16:54  README.md
[loren@Gazp9 layouts]$

```

--> Tried commenting the favicon.png line in 'Index default.vue'...  


```
[loren@Gazp9 layouts]$ gridsome develop
egrep: warning: egrep is obsolescent; using grep -E
Bootstrapping...
Initialize - 0.16s
Run plugins - 0.03s
Create GraphQL schema - 0.01s
Generate temporary files - 0.02s
Bootstrap finish - 0.21s

  Site running at:          http://localhost:8080
  Explore GraphQL data at:  http://localhost:8080/___explore

^C
[loren@Gazp9 layouts]$
```


--> No compile errors! But no content in the page, only the Header Gridsome:Gridsome above blank white page...

--> So I suspect some of those 'npm install --save buefy' circular errors really do prevent proper operation.
