### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by nathansmedley** [gridsome/gridsome#1621]
Hi Guys, upon running gridsome develop i get error about it not being able to install the sharp module

PS C:\Users\Name\Documents\GitHub\Web.UK.Site> gridsome develop
Mode:  undefined  APIURL:  
Gridsome v0.7.23

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-win32-x64.node'
Require stack:
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\sharp\lib\sharp.js
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\sharp\lib\constructor.js
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\sharp\lib\index.js
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\gridsome\lib\app\queue\ImageProcessQueue.js
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\gridsome\lib\app\queue\AssetsQueue.js
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\gridsome\lib\app\App.js
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\gridsome\lib\app\index.js
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\gridsome\lib\develop.js
- C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\gridsome\index.js
- C:\Users\Name\AppData\Roaming\npm\node_modules\@gridsome\cli\bin\gridsome.js

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\sharp\lib\sharp.js:31:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\Name\Documents\GitHub\Web.UK.Site\node_modules\sharp\lib\constructor.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Gridsome Info:**
  System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz  
  Binaries:
    Node: 14.18.3 - C:\Program Files\nodejs\node.EXE        
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
  npmPackages:
    @gridsome/cli: ^0.3.4 => 0.3.4 
    @gridsome/plugin-critical: ^0.2.0 => 0.2.0 
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0 
    gridsome: ^0.7.23 => 0.7.23

**Comment by alisalad** [comment]
I have similar errors....have you find solutions?

**Comment by alisalad** [comment]
remove ("node-sass": "^4.13.1",) from the JSON file.

**Comment by chrisrueger** [comment]
I had a similar problem with sharp but related to Mac M1 processor. 
[This](https://github.com/nuxt/image/issues/204#issuecomment-1001585763) has helped me.

**Comment by SatoruFF** [comment]
Switching the base image in the docker container helped me.

alpine => bullseye
