### ISSUE TITLE
Netlify Build Fail Do to "Cannot read property 'image' of undefined"

### ISSUE THREAD

**Issue by Burnsedia** [gridsome/gridsome#1628]
## Description

I am using Gridsome Netlify CMS Starter to build a website for my client. I am getting a "Cannot read property 'image' of undefined"
" 
could not generate HTML for "/author/"MY_CLIENT"/":
TypeError: Cannot read property 'image' of undefined
    at a.render (src/components/PostItem.vue?f60a:1:130)
    at a.t._render (/home/overlord/dev/"MYCLIENT"/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /home/overlord/dev//"MYCLIENT"node_modules/vue-server-renderer/build.prod.js:1:70603
    at Yi (/home/overlord/dev/n"MYCLIENT"/ode_modules/vue-server-renderer/build.prod.js:1:67167)
    at io (/home/overlord/dev/"MYCLIENT"/node_modules/vue-server-renderer/build.prod.js:1:70579)
    at ro (/home/overlord/dev/Tonya-King/node_modules/vue-server-renderer/build.prod.js:1:70210)
    at _t.eo [as renderNode] (/home/overlord/dev/"MYCLIENT"/node_modules/vue-server-renderer/build.prod.js:1:67457)
    at _t.next (/home/overlord/dev/Tonya-King/node_modules/vue-server-renderer/build.prod.js:1:20473)
    at n (/home/overlord/dev/"MYCLIENT"/node_modules/vue-server-renderer/build.prod.js:1:18685)
    at /home/overlord/dev/"MYCLIENT"/node_modules/vue-server-renderer/build.prod.js:1:68568
"
I replace my repo name with "MYCLIENT" because the repo is name after my client.
### Steps to reproduce

gridsome build

### Expected result

Successful Build

### Actual result
" 
could not generate HTML for "/author/"MY_CLIENT"/":
TypeError: Cannot read property 'image' of undefined
    at a.render (src/components/PostItem.vue?f60a:1:130)
    at a.t._render (/home/overlord/dev/"MYCLIENT"/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /home/overlord/dev//"MYCLIENT"node_modules/vue-server-renderer/build.prod.js:1:70603
    at Yi (/home/overlord/dev/n"MYCLIENT"/ode_modules/vue-server-renderer/build.prod.js:1:67167)
    at io (/home/overlord/dev/"MYCLIENT"/node_modules/vue-server-renderer/build.prod.js:1:70579)
    at ro (/home/overlord/dev/Tonya-King/node_modules/vue-server-renderer/build.prod.js:1:70210)
    at _t.eo [as renderNode] (/home/overlord/dev/"MYCLIENT"/node_modules/vue-server-renderer/build.prod.js:1:67457)
    at _t.next (/home/overlord/dev/Tonya-King/node_modules/vue-server-renderer/build.prod.js:1:20473)
    at n (/home/overlord/dev/"MYCLIENT"/node_modules/vue-server-renderer/build.prod.js:1:18685)
    at /home/overlord/dev/"MYCLIENT"/node_modules/vue-server-renderer/build.prod.js:1:68568
"

### Environment

Nodejs v12.22.11
vuejs v2.6.11
gridsome
├─┬ @gridsome/remark-prismjs@0.3.0
├─┬ @gridsome/source-filesystem@0.6.2
├─┬ @gridsome/transformer-remark@0.6.1
├─┬ gridsome@0.7.19
│ ├─┬ @gridsome/cli@0.3.3

**Comment by chrisrueger** [comment]
I had this too sometimes. It is usually not a gridsome problem, but something with your data. 
It seems that in `PostItem.vue` an object where you try to call `.image` is null.

Check where in your code you do `myobject.image`

**Comment by Burnsedia** [comment]
Image was defined, but it was not working because there was a braket was out of place.
