### ISSUE TITLE
Gridsome install failed

### ISSUE THREAD

**Issue by nothinghalosix** [gridsome/gridsome#1630]
## Description

gridsome create test
❯ Clone https://github.com/gridsome/gridsome-starter-default.git 0.62s
❯ Update project package.json 0s
❯ Install dependencies
  • Building fresh packages (4 of 4)
Error: Failed to install dependencies with yarn. Please enter test directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

    Exit code 1
    at ChildProcess.<anonymous> (/Users/nothing/.config/yarn/global/node_modules/@gridsome/cli/lib/commands/create.js:106:17)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)

**Other Project**: gridsome boilerplate base stuff work fine. "yarn add -D sass-loader@^10.1.1 sass" brake the application

...
[4/4] 🔨  Building fresh packages...
[6/7] ⢀ sharp
[-/7] ⢀ waiting...
[-/7] ⢀ waiting...
[-/7] ⢀ waiting...
error /Users/nothing/sites/designfabrik/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /Users/nothing/sites/designfabrik/node_modules/sharp
Output:
info sharp Detected globally-installed libvips v8.12.2
info sharp Building from source via node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.19.1 | darwin | arm64
gyp info find Python using Python version 3.9.12 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
...

Machine: MacBook Pro 16" M1 pro
Node V: 14.19.1
yarn V: 1.22.18
npm V: 6.14.16

Paste the information here as shown by `gridsome info`

**Comment by mgd722** [comment]
https://github.com/gridsome/gridsome/issues/1596

**Comment by nothinghalosix** [comment]
hi mgd722,

thank you for your response. This not working for me. I unlinked the project from node@14 and linked with node@17.8.0 and it works, but the gridsome build command give me:
.
.
.
TypeError: Cannot read properties of undefined (reading '__esModule')
    at Ue (/Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:24372)
    at /Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:21337
    at /Users/nothing/sites/designfabrik/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394

Node.js v17.8.0

**Comment by dev23jjl** [comment]
Hi @nothinghalosix,

Instead of using Node 17 (which is known to be incompatible with Gridsome), use the latest LTS version of Node (16.14.2) and hopefully this will fix your problem.
