### ISSUE TITLE
Error happening when 'npm run build'

### ISSUE THREAD

**Issue by mrkylemac** [gridsome/gridsome#197]
Hi there! 

I'm experiencing an error which I can't seem to debug when running ```npm run build```, running ```npm run develop``` works perfectly.

Here is the error:
```
> gridsome build

Gridsome v0.4.7

Initialize - 0.09s
Load sources - 0.05s
Create GraphQL schema - 0.03s
Generate code - 0.02s
Bootstrap finish - 0.2s
Run GraphQL (5 queries) - 0.06s

 10% building 1/1 modules 0 active 10% building 5/10 modules 5 active ...and/   11% building 10/14 modules 4 active ...and/wtw2019/src/.temp/plugins-server.j
(undefined) ./src/components/SiteHeader.vue?vue&type=template&id=6fc51915& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/gr
idsome","cacheIdentifier":"b1fe6752-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-lo
ader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/SiteHeader.vue?vue&type=template&id=6fc51915&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unterminated string constant (1:311)
    at Parser.pp$4.raise (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:2610:13)
    at Parser.pp$8.readString (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:3436:35)
    at Parser.pp$8.getTokenFromCode (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:3220:17)
    at Parser.pp$8.readToken (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:2975:15)
    at Parser.readToken (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:4398:22)
    at Parser.pp$8.nextToken (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:2966:15)
    at Parser.pp$8.next (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:2923:8)
    at Parser.pp.eat (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:569:10)
    at Parser.pp$3.parseSubscripts (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:1979:35)
    at Parser.pp$3.parseExprSubscripts (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:1958:21)
    at Parser.pp$3.parseMaybeUnary (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
    at Parser.pp$3.parseExprOps (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:1857:1
9)
    at Parser.pp$3.parseMaybeAssign (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:1832:19)
    at Parser.pp$3.parseExprList (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:2528:20)
    at Parser.pp$3.parseExprAtom (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/vue-template-es2015-compiler/buble.js:2073:26)
 @ ./src/components/SiteHeader.vue?vue&type=template&id=6fc51915& 1:0-382 1:0-382
 @ ./src/components/SiteHeader.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modul
es/vue-loader/lib??vue-loader-options!./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue
 @ ./src/main.js
 @ ./node_modules/gridsome/app/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.server.js
 @ multi ./node_modules/gridsome/app/entry.server.js
Error: Failed to compile.
    at webpack.run (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/gridsome/lib/webpack/compileAssets.js:40:23)
    at finalCallback (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/neo-async/async.js:2928:13)
    at runCompilers (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/Compiler.js:220:39)
    at hooks.done.callAsync.err (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/Compiler.js:269:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/tapable/lib/HookCodeFactor
y.js:32:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/Compiler.js:267:22)
    at Compiler.emitRecords (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/Compiler.js:449:39)
    at emitAssets.err (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/Compiler.js:261:10)
    at hooks.afterEmit.callAsync.err (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/webpack/lib/Compiler.js:435:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/tapable/lib/HookCodeFactor
y.js:32:10), <anonymous>:20:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! welcome-to-wasteland-2019@ build: `gridsome build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the welcome-to-wasteland-2019@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

and the log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v10.14.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle welcome-to-wasteland-2019@~prebuild: welcome-to-wasteland-2019@
6 info lifecycle welcome-to-wasteland-2019@~build: welcome-to-wasteland-2019@
7 verbose lifecycle welcome-to-wasteland-2019@~build: unsafe-perm in lifecycle true
8 verbose lifecycle welcome-to-wasteland-2019@~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle welcome-to-wasteland-2019@~build: CWD: /Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019
10 silly lifecycle welcome-to-wasteland-2019@~build: Args: [ '-c', 'gridsome build' ]
11 silly lifecycle welcome-to-wasteland-2019@~build: Returned: code: 1  signal: null
12 info lifecycle welcome-to-wasteland-2019@~build: Failed to exec build script
13 verbose stack Error: welcome-to-wasteland-2019@ build: `gridsome build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid welcome-to-wasteland-2019@
15 verbose cwd /Users/mrkylemac/Local Sites/welcome-to-wasteland/wtw2019
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.14.2
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error welcome-to-wasteland-2019@ build: `gridsome build`
22 error Exit status 1
23 error Failed at the welcome-to-wasteland-2019@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
If anyone could assist that would be amazing, let me know if you need any more information,
Thanks!

**Comment by hjvedvik** [comment]
The `SyntaxError: Unterminated string constant` message can indicate that you might have an issue with mismatching pairs of quotation marks in `src/layouts/Default.vue`.

**Comment by mrkylemac** [comment]
Thanks, @hjvedvik!

This was because perhaps the following content had a special character? Retyping this out manually seemed to fix the build error - strange!

``` 
<div class="about">
      <p>
           Note -> Please be mindful of your power consumption. Your
           prolonged usage of this website will deplete the solar battery
           ☀
     </p>
</div> 
```
