### ISSUE TITLE
Problem with directory junction in windows 10

### ISSUE THREAD

**Issue by Vlasterx** [gridsome/gridsome#206]
## Description

While trying to create basic build on freshly installed gridsome, I found out that it has problems with directory junctions in Windows machines. 

My local web server, where I keep everything for web development and non-php related projects, is in 
` e:/xampp/htdocs/` which was mapped to directory junction to `e:/webroot/`.

![image](https://user-images.githubusercontent.com/2601074/53174518-48b5bc80-35ea-11e9-9654-78c0ce32fcf7.png)

### Steps to reproduce
Create directory junction in windows with mklink command.  CD into that junction folder, create new project with gridsome and run development server.

### Expected result

Basic demo should be compiled without problems.

### Actual result

Error with g-image

```
Failed to render /
TypeError: Cannot read property 'width' of undefined
    at render (e:/xampp/htdocs/test/gridtest/node_modules/gridsome/app/components/Image.js:38:27)
    at e:\xampp\htdocs\test\gridtest\node_modules\vue\dist\vue.runtime.common.prod.js:6:22087
    at Ie (e:\xampp\htdocs\test\gridtest\node_modules\vue\dist\vue.runtime.common.prod.js:6:22269)
    at e:\xampp\htdocs\test\gridtest\node_modules\vue\dist\vue.runtime.common.prod.js:6:23399
    at Le (e:\xampp\htdocs\test\gridtest\node_modules\vue\dist\vue.runtime.common.prod.js:6:23750)
    at e._c (e:\xampp\htdocs\test\gridtest\node_modules\vue\dist\vue.runtime.common.prod.js:6:31905)
    at a.render (e:/xampp/htdocs/test/gridtest/src/pages/Index.vue?25ed:1:89)
    at a.t._render (e:\xampp\htdocs\test\gridtest\node_modules\vue\dist\vue.runtime.common.prod.js:6:34798)
    at e:\xampp\htdocs\test\gridtest\node_modules\vue-server-renderer\build.prod.js:1:69946
    at Zi (e:\xampp\htdocs\test\gridtest\node_modules\vue-server-renderer\build.prod.js:1:66510)
```

**Comment by Vlasterx** [comment]
I guess that the problem is in determining the relative path toward to root of the project and then assigning it to webpack alias in `gridsome/lib/webpack/createBaseConfig.js`:

```js
const resolve = (p, c) => path.resolve(c || __dirname, p)

// ...

  config.resolve
    .set('symlinks', true)
    .alias
    .set('~', resolve('src', app.context))
    .set('@', resolve('src', app.context))
    .set('gridsome$', path.resolve(projectConfig.appPath, 'index.js'))
    .end()
```

In one of my other projects, we have solved this problem by using [app-root-path](https://github.com/inxilpro/node-app-root-path) plugin to determine actual root of the project. Then, we used this result to set our custom aliases in webpack.
