### ISSUE TITLE
Cannot read property path of null (GraphQL layer)

### ISSUE THREAD

**Issue by Truemedia** [gridsome/gridsome#220]
## Description

Recently pulled in master branch of gridsome on a full development setup (project within projects/ folder). Started getting this error whenever I use static query within a component:

```bash
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of null
    at forks/gridsome/gridsome/lib/server/middlewares/graphql.js:14:19
```

I have a fix but I don't have enough context on the middleware to know if it's has implications of other things.

### Steps to reproduce

Clone fresh copy of master branch from this repo and setup a new project in the projects/ folder with at least one component using a static query.

### Expected result

No errors

### Actual result

Query breaks graphQL layer and consequently my page requesting data

**Comment by tomtev** [comment]
Could you also add the code of your `<static-query>`?

**Comment by hjvedvik** [comment]
The middleware is only used for `page-query` and it parses the query and sets up a context for it before `express-graphql` executes it. Would be interesting to see the request body that is causing the error because it looks like `express-graphql` isn't able to parse the variables.

**Comment by Truemedia** [comment]
Sure, here is the static query:

```graphql
<static-query>
  query {
    articles: allStrapiArticle {
      edges {
        node {
          id,
        	title,
          content
      	}
      }
    }
  }
</static-query>
```

And here is what I get in the body variable:
```json

```

**Comment by ion1** [comment]
I can confirm this issue on a fresh project from `gridsome create`. Running `DEBUG='*' gridsome develop` and `curl 'http://localhost:8080/___graphql' -X OPTIONS` (the web browser was doing that request on an actual project), I see the following and the request never completes.

```
 DONE  Compiled successfully in 235ms                                                                                                                                           09:18:59

  Site running at:          http://localhost:8080/
  Explore GraphQL data at:  http://localhost:8080/___explore

  express:router dispatching OPTIONS /___graphql +17s
  express:router query  : /___graphql +0ms
  express:router expressInit  : /___graphql +1ms
  express:router <anonymous>  : /___graphql +0ms
  express:router trim prefix (/___graphql) from url /___graphql +1ms
  express:router <anonymous> /___graphql : /___graphql +0ms
(node:20092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of null
    at C:\Users\ion\Documents\src\gridsome-test\node_modules\gridsome\lib\server\middlewares\graphql.js:14:19
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:20092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting
a promise which was not handled with .catch(). (rejection id: 1)
(node:20092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by u12206050** [comment]
I am also having a similar problems with dates: `Cannot read property 'toISOString' of null`

Dates are optional on the field so it is either null or a date.
