### ISSUE TITLE
TypeError: String cannot represent a non string value

### ISSUE THREAD

**Issue by kjbrum** [gridsome/gridsome#243]
I'm having trouble viewing individual content type pages. When I click on a `<g-link>` to go to the single page, I get a 404 page and `%2F` is added before each section of the URL.

Expected: `http://localhost:8080/article/internal-meetings`
Actual: `http://localhost:8080/%2Farticle%2Finternal-meetings`

I suspect it's related, but when I run `npm run build`, I get the following output:
```
Initialize - 0.52s
Load sources - 2.34s
Create GraphQL schema - 0.19s
Set up routes - 0s
Generate code - 0.03s
Bootstrap finish - 3.08s
TypeError: String cannot represent a non string value: 35
    at GraphQLScalarType.coerceString [as parseValue] (/Users/kylebrumm/sites/gridsome-example/node_modules/graphql/type/scalars.js:164:11)
    at coerceValue (/Users/kylebrumm/sites/gridsome-example/node_modules/graphql/utilities/coerceValue.js:55:30)
    at coerceValue (/Users/kylebrumm/sites/gridsome-example/node_modules/graphql/utilities/coerceValue.js:42:12)
    at getVariableValues (/Users/kylebrumm/sites/gridsome-example/node_modules/graphql/execution/values.js:85:54)
    at buildExecutionContext (/Users/kylebrumm/sites/gridsome-example/node_modules/graphql/execution/execute.js:196:63)
    at executeImpl (/Users/kylebrumm/sites/gridsome-example/node_modules/graphql/execution/execute.js:70:20)
    at execute (/Users/kylebrumm/sites/gridsome-example/node_modules/graphql/execution/execute.js:62:229)
    at pMap (/Users/kylebrumm/sites/gridsome-example/node_modules/gridsome/lib/build.js:199:27)
    at Promise.resolve.then.element (/Users/kylebrumm/sites/gridsome-example/node_modules/p-map/index.js:47:21)
    at <anonymous>
```

Any help would be greatly appreciated!

**Comment by kaceo** [comment]
There is a chain of errors cascading down.  The 404 (page not found) is the effect of URL changing "/" to "%2F".  That is the effect of Vue-router not able to find a resolved route to that page.  That is the effect of a compilation error from one of the parts of that page.  

During "Yarn Develop" the source of the error is not flagged, but during "Yarn Build" you can clearly see the error came from the GraphQL expressions.  This issue has been reported in [#204](https://github.com/gridsome/gridsome/issues/204), and a fix is being worked on.

In general, try to verify the correctness of your GraphQL expression by testing them out in the GraphQL explorer (at location "___explore").

**Comment by kjbrum** [comment]
Thanks for bringing that issue to my attention. I actually used the explorer to build my GraphQL query for the page and it's working as expected.

I'm fairly new to Gridsome and GraphQL, so any direction on how to troubleshoot the issue more would be awesome.

**Comment by hjvedvik** [comment]
Looks like you have nodes with `id` as numbers? Try changing them to strings and see if that helps.

**Comment by kjbrum** [comment]
@hjvedvik Looks like that was the issue! Thanks so much.
