### ISSUE TITLE
Cannot run gridsome develop

### ISSUE THREAD

**Issue by Jegard** [gridsome/gridsome#254]
When running `gridsome develop` i am receiving this error this has only occurred recently

```
Apples-MacBook-Pro:slomans apple$ gridsome develop

Gridsome v0.5.4
Initialize - 0.13s
Load sources - 0.05s
Create GraphQL schema - 0.03s
Set up routes - 0s
Generate code - 0.03s
Bootstrap finish - 0.24s
Error: stderr is null - this should never happen. Please open up an issue at https://github.com/facebook/jest
at ChildProcessWorker.getStderr (/Users/apple/Documents/projects/slomans/node_modules/jest-worker/build/workers/ChildProcessWorker.js:222:13)
at new BaseWorkerPool (/Users/apple/Documents/projects/slomans/node_modules/jest-worker/build/base/BaseWorkerPool.js:69:35)
at new WorkerPool (/Users/apple/Documents/projects/slomans/node_modules/jest-worker/build/WorkerPool.js:31:1)
at new JestWorker (/Users/apple/Documents/projects/slomans/node_modules/jest-worker/build/index.js:123:26)
at createWorker (/Users/apple/Documents/projects/slomans/node_modules/gridsome/lib/workers/index.js:9:10)
at module.exports (/Users/apple/Documents/projects/slomans/node_modules/gridsome/lib/server/middlewares/assets.js:8:18)
at module.exports (/Users/apple/Documents/projects/slomans/node_modules/gridsome/lib/server/createExpressServer.js:59:55)
at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by chelseadgls** [comment]
This is a dupe if issue #252, but I have this problem as well.

**Comment by hjvedvik** [comment]
You can find a temporary solution in the issue mentioned by @chelseadgls
