### ISSUE TITLE
Cant hit Wordpress.com endpoint

### ISSUE THREAD

**Issue by ay13** [gridsome/gridsome#299]
## Description

Cant hit wordpress.com endpoint. The plugin seems to be designed to assume the self-hosted api by appending `/wp/w2` to the end of each call. The Wordpress hosted api uses this format `https://public-api.wordpress.com/wp/v2/sites/<hosted-url.wordpress.com>`

### Steps to reproduce

Set up the Wordpress plugin as normal but try to use a wordpress.com hosted site instead of a self-hosted one.

### Expected result

The expected result is fetching the data.

### Actual result

Fails in develop startup with:
`Error: Status 404 - https://public-api.wordpress.com/wp/v2/sites/staticsitegeneration.wordpress.com/wp/v2/types
    at WordPressSource.fetch (/Users/ayoung/experiments/gridsome/gridsome-wordpress-demo/node_modules/@gridsome/source-wordpress/index.js:171:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.5
- @gridsome/cli version: 0.0.8

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Berkmann18** [comment]
I'm experiencing the same issue although I've only tried with `npm run dev` and `npm run generate`.

**Comment by technoSpino** [comment]
seems the self hosted and wordpress.com sites do not follow the same structure on purpose. https://developer.wordpress.com/docs/api/ 

```
If you’re looking for the WordPress REST API that shipped as part of WordPress core in version 4.7, see its documentation.  Note that this API is also enabled on WordPress.com, but the URL structure on WordPress.com is slightly different than for self-hosted sites.  See this post for more details
```

**Comment by robaxelsen** [comment]
@technoSpino thanks for looking into this, that is helpful!

@hjvedvik: do we want to update the source plugin documentation to reflect this, and/or provide a config option (and implementation) for allowing both self-hosted and wordpress.com?

**Comment by iamthismarvin** [comment]
I made some changes to the index.js to make it work for Wordpress.com sites. I changed all the "**wp/v2/**" in the file for "**/**". This worked for me. 

Although it does seem like Wordpress.com also made a change for images and instead of being "**featured_media {url, width, etc...}**" I could only find and make the images work in full size by changing it to "**jetpackFeaturedMediaUr**l" in the query for WordPressPost.vue and others.

Now it works locally for me, but I can't deplay it to Netlify because it builds the dist using the dependency. Any idea how to make it work with these changes? Should we wait for an update or should I submit a pull request with the changes I made?

[index file here](https://github.com/gridsome/gridsome/files/3041970/index.zip)

**Comment by rodrigorhas** [comment]
I've fixed this bug updating the permalinks.

See this
https://stackoverflow.com/questions/34670533/wordpress-rest-api-wp-api-404-error

**Comment by rufuspollock** [comment]
OK, I had the same issue, for wordpress.com urls this fails ...

```
wp/v2/types
Error: ECONNREFUSED - wp/v2/types
    at WordPressSource.fetch (/Users/rgrp/src/art-earth-tech/sandbox/gridsome-wordpress/node_modules/@gridsome/source-wordpress/index.js:193:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

And I found this issue 😄  For others struggling like me here's the debug ...

## Analysis

### Non-WP.com Wordpress sites

For non-wordpress.com sites the REST API endpoint is is as per the docs at https://developer.wordpress.org/rest-api/ i.e.

```
BASE_URL/wp-json/
BASE_URL/wp-json/wp/v2/
BASE_URL/wp-json/wp/v2/posts
```

where `BASE_URL` is the url of your site e.g. `artearthtech.com`

If we look in the gridsome code we can see that is exactly what is supported:

```
  // your config file gridsome.config.js
  options: {
    // baseUrl: process.env.WORDPRESS_URL, // required
    baseUrl: 'artearthtech.com',
  }


  // @gridsome/source-wordpress index.js

  static defaultOptions () {
    return {
      baseUrl: '',
      apiBase: 'wp-json',
      perPage: 100,
      concurrent: 10,
      typeName: 'WordPress'
    }
  }

  ...

    this.client = axios.create({
      baseURL: `${baseUrl}/${options.apiBase}`
    })

  ...

   // here url will be e.g. wp/v2/types
   res = await this.client.request({ url, params })
```

### However, wordpress.com is a little different

> If you’re looking for the WordPress REST API that shipped as part of WordPress core in version 4.7, see its documentation.  Note that this API is also enabled on WordPress.com, but the URL structure on WordPress.com is slightly different than for self-hosted sites.  See this post for more details. https://developer.wordpress.com/docs/api/

The linked post is here: https://developer.wordpress.com/2016/11/11/wordpress-rest-api-on-wordpress-com/

As that explains the endpoint on WP.com is:

https://public-api.wordpress.com/wp/v2/

And to use it for a site named e.g. `artearthtech.com` you do:

```
GET https://public-api.wordpress.com/wp/v2/sites/artearthtech.com/posts
```

The key difference here is that you have `sites/BASE_URL` inserted plus the wp/v2 comes before that with actual REST path after.

### So we need a patch ...

Here's my new `gridsome.config.js`

```js
  plugins: [
    {
      use: '@gridsome/source-wordpress',
      options: {
        // baseUrl: process.env.WORDPRESS_URL, // required
        baseUrl: 'artearthtech.com',
        hostingWPCOM: true
      }
    }
  ]
```

And here's the changed `source-wordpress/index.js`. I'll try and submit a patch for this ...

```diff
--- a/packages/source-wordpress/index.js
+++ b/packages/source-wordpress/index.js
@@ -10,10 +10,11 @@ class WordPressSource {
   static defaultOptions () {
     return {
       baseUrl: '',
-      apiBase: 'wp-json',
+      apiBase: 'wp-json/wp/v2',
       perPage: 100,
       concurrent: 10,
-      typeName: 'WordPress'
+      typeName: 'WordPress',
+      hostingWPCOM: false
     }
   }
 
@@ -32,9 +33,18 @@ class WordPressSource {
     this.customEndpoints = this.sanitizeCustomEndpoints()
 
     const baseUrl = trimEnd(options.baseUrl, '/')
+    // wordpress.com has a different layout
+    // GET https://public-api.wordpress.com/wp/v2/sites/BASE_URL/posts
+    // vs (for non wp.com)
+    // GET https://BASE_URL/wp-json/wp/v2/posts
+    let clientBase = `${baseUrl}/${options.apiBase}`
+    if (options.hostingWPCOM) {
+      const wpcom = 'https://public-api.wordpress.com/wp/v2/sites'
+      clientBase = `${wpcom}/${baseUrl}`
+    }
 
     this.client = axios.create({
-      baseURL: `${baseUrl}/${options.apiBase}`
+      baseURL: clientBase
     })
 
     this.routes = this.options.routes || {}
@@ -53,7 +63,7 @@ class WordPressSource {
   }
 
   async getPostTypes (actions) {
-    const { data } = await this.fetch('wp/v2/types', {}, {})
+    const { data } = await this.fetch('/types', {}, {})
     const addCollection = actions.addCollection || actions.addContentType
 
     for (const type in data) {
@@ -69,7 +79,7 @@ class WordPressSource {
   }
 
   async getUsers (actions) {
-    const { data } = await this.fetch('wp/v2/users')
+    const { data } = await this.fetch('/users')
     const addCollection = actions.addCollection || actions.addContentType
 
     const authors = addCollection({
@@ -91,7 +101,7 @@ class WordPressSource {
   }
 
   async getTaxonomies (actions) {
-    const { data } = await this.fetch('wp/v2/taxonomies', {}, {})
+    const { data } = await this.fetch('/taxonomies', {}, {})
     const addCollection = actions.addCollection || actions.addContentType
 
     for (const type in data) {
@@ -103,7 +113,7 @@ class WordPressSource {
 
       this.restBases.taxonomies[type] = trimStart(options.rest_base, '/')
 
-      const terms = await this.fetchPaged(`wp/v2/${options.rest_base}`)
+      const terms = await this.fetchPaged(`/${options.rest_base}`)
 
       for (const term of terms) {
         taxonomy.addNode({
@@ -130,7 +140,7 @@ class WordPressSource {
       const typeName = this.createTypeName(type)
       const posts = getCollection(typeName)
 
-      const data = await this.fetchPaged(`wp/v2/${restBase}`)
+      const data = await this.fetchPaged(`/${restBase}`)
 
       for (const post of data) {
         const fields = this.normalizeFields(post)
@@ -189,11 +199,15 @@ class WordPressSource {
       if (!response && code) {
         throw new Error(`${code} - ${config.url}`)
       }
-
       if ([401, 403].includes(response.status)) {
         console.warn(`Error: Status ${response.status} - ${config.url}`)
         return { ...response, data: fallbackData }
-      } else {
+      } else if ( // 404 ok for /menus endpoint on wp.com as does not exist afaict
+          [404].includes(response.status) &&
+          (url == '/menus' || url == '/menu-items') && this.options.hostingWPCOM) {
+        return { ...response, data: fallbackData }
+      }
+      else {
         throw new Error(`${response.status} - ${config.url}`)
       }
     }
```
