### ISSUE TITLE
Issue with template caused hard to debug build issue

### ISSUE THREAD

**Issue by cfjedimaster** [gridsome/gridsome#300]
## Description

I'm learning Gridsome and trying to get templates to work correctly. I'm 100% definitely doing something wrong. In an attempt to try to diagnose what is wrong, I did a `gridsome build`. Doing so returned this error:

```
Initialize - 0.45s
Load sources - 2.23s
Create GraphQL schema - 0.05s
Set up routes - 0s
Generate code - 0.04s
Bootstrap finish - 2.78s
TypeError: Cannot read property 'split' of null
    at exports.createPath (/mnt/c/projects/gridsometests/app1/node_modules/gridsome/lib/utils/index.js:22:27)
    at createEntry (/mnt/c/projects/gridsometests/app1/node_modules/gridsome/lib/build.js:80:18)
    at createRenderQueue (/mnt/c/projects/gridsometests/app1/node_modules/gridsome/lib/build.js:116:20)
    at module.exports (/mnt/c/projects/gridsometests/app1/node_modules/gridsome/lib/build.js:29:23)
```

Ok, so while it is my fault, couldn't the CLI have reported some more information about what went wrong? On a whim I just renamed my template file to .bak so Gridsome would ignore it.

On a related note, my 'bad' template file also caused other requests to return blank pages. Nothing was reported in the terminal at all. I can file another bug report for that, but in general it seems like template issues aren't handled as nice as they could be (if that makes sense).

### Steps to reproduce

I've attached a zip of my code, but note the template is renamed to .bak. Just rename it to .vue. Again, I know my code is wrong. ;)

### Expected result

Some context as to why the build fails.

### Actual result

A vague issue.

### Environment

<pre><code>
Libs:
- gridsome version: 0.5.5
- @gridsome/cli version: 0.0.8
</code></pre>

**Comment by hjvedvik** [comment]
Do you have a route option for the content type you create a template for? Or do you have a path on each node instead?

**Comment by cfjedimaster** [comment]
I honestly do not know. :) I'm using gridsome.server.js to create a collection and my index page correctly shows it. My understanding is that by adding a template file, I can then get XXX/ID to work for showing a single value from the collection. All I did was add the template, nothing more.

**Comment by cfjedimaster** [comment]
And I forgot to include my source - sorry! 
[src.zip](https://github.com/gridsome/gridsome/files/2988682/src.zip)

**Comment by hjvedvik** [comment]
Gridsome needs either a route option for the content type OR a path option on each node in order to render a template. You can read something about routing [here](https://gridsome.org/docs/routing#routing-for-custom-data-sources) with a simple example.

**Comment by cfjedimaster** [comment]
Ah nice! I'm almost there. I've added a route and my other pages work fine now. My route is: `film/:slug`. When I hit `film/4` in my browser I get a 404 though.

**Comment by cfjedimaster** [comment]
Ah ok - I did a build and I'm seeing it is NOT using the ID value I specified but rather the title.

**Comment by cfjedimaster** [comment]
And duh - changing it to `film/:id` fixed it. Cool. Ok, so thank you for the help! However, my original request seems to be related to route not existing. So could Gridsome have noticed the lack of that setting (or path) and handled the error better?

**Comment by hjvedvik** [comment]
Yes, I'll see what I can do about it :)

**Comment by cfjedimaster** [comment]
Thank you. I may be on a new bug now, but while my route is working, the detail is not. I'm still trying to figure out why, but as an example, I had used `:title="$page.post.title"` where `post` isn't what I'm working with. My fault for sure, again, but Gridsome should have thrown an error about an undefined value, right?

**Comment by hjvedvik** [comment]
Gridsome doesn't have much control inside the components. But you will most likely get an error message in the browser console, either by Vue or a standard JS error.

**Comment by cfjedimaster** [comment]
Nope. :\ Ok I'll stop now - I'm polluting this issue with commentary. ;) Thank you again!

**Comment by cfjedimaster** [comment]
One last comment, I swear. Do you think the fact that the Templates doc comes *before* Routing may have caused me an issue? As I learn I tend to try things as I see them in the doc. If you imagine a new learner reading the docs, do you see them repeating this issue if they don't read everything from start to finish before they play?

**Comment by cfjedimaster** [comment]
As an example, consider this page: https://gridsome.org/docs/taxonomies. Why doesn't it use a route in the sample code? It's always required, right?
