### ISSUE TITLE
Any `gridsome` command throws syntax error

### ISSUE THREAD

**Issue by jasonday** [gridsome/gridsome#327]
## Description

Gridsome installs without issue.

```
npm info using npm@3.10.9
npm info using node@v6.9.2
```

Syntax error on `gridsome create my-project`, `gridsome -v` etc. 

```
C:\Users\a635800\AppData\Roaming\npm\node_modules\@gridsome\cli\lib\utils\version.js:25
  const packages = { ...devDependencies, ...dependencies }
                     ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\a635800\AppData\Roaming\npm\node_modules\@gridsome\cli\bin\gridsome.js:7:25)
    at Module._compile (module.js:570:32)
```

**Comment by hjvedvik** [comment]
You need to update Node.js to at least 8.3 in order to use Gridsome. We should probably mention that in the docs. I'll fix that :)
