### ISSUE TITLE
Fails to build on importing pwacompat

### ISSUE THREAD

**Issue by thasmo** [gridsome/gridsome#365]
In my `main.js` file [`pwacompat`](https://github.com/GoogleChromeLabs/pwacompat) is imported.
```js
import 'pwacompat';
```

This works in development, but when running `gridsome build` it fails.
```sh
Failed to render /
ReferenceError: XMLHttpRequest is not defined
    at assets/js/app.c1708a5e.js:3084:21
    at Object.<anonymous> (node_modules/pwacompat/pwacompat.js:442:1)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (assets/js/app.c1708a5e.js:2992:67)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (node_modules/gridsome/app/main.js:6:9)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (assets/js/app.c1708a5e.js:2132:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at module.exports.module.exports.version (webpack/bootstrap:116:0)
```

Any way to get this running? Thanks!

**Comment by loda-kun** [comment]
I have the same issue. when import `vue-infinite-scroll`. It works fine in development but when building it, I got this: 

```
Failed to render /vuejs
ReferenceError: document is not defined
    at /Users/lv00141/Documents/WORKING_SPACE/GITHUB/loda.me/node_modules/vue-infinite-scroll/vue-infinite-scroll.js:51:26
    at /Users/lv00141/Documents/WORKING_SPACE/GITHUB/loda.me/node_modules/vue-infinite-scroll/vue-infinite-scroll.js:2:83
    at Object.<anonymous> (/Users/lv00141/Documents/WORKING_SPACE/GITHUB/loda.me/node_modules/vue-infinite-scroll/vue-infinite-scroll.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by thasmo** [comment]
Does someone know where the error has it's origin in? Is this a babel issue or something?

**Comment by hjvedvik** [comment]
I don't think `XMLHttpRequest` is available in Node.js, so you probably need to use `process.isClient` to only import the module in the browser.

**Comment by thasmo** [comment]
@hjvedvik, thanks! Fixed it by using `process.isClient` this way:
```js
if (process.isClient) {
    window.addEventListener('load', () => import('pwacompat'));
}
```
