### ISSUE TITLE
Unable to build when using vue-google-maps: Unexpected token <

### ISSUE THREAD

**Issue by timcreatewell** [gridsome/gridsome#384]
## Description

I've included vue-google-maps in my project and it works perfectly in dev.  However, when I try to build my project I receive the following error: `SyntaxError: Unexpected token < ...`

I notice that Nuxt users are having similar issues - but they seem to have a solution (e.g. https://github.com/xkjyeah/vue-google-maps/issues/537#issuecomment-449900348).  Is there something similar we can do in Gridsome?

### Steps to reproduce

1. Include vue-google-maps in your Gridsome project (refer to quickstart: https://github.com/xkjyeah/vue-google-maps#quickstart-webpack-nuxt)
2. Attempt to build your project (`gridsome build`)

### Expected result

The project should build.

### Actual result

A build error is thrown: `SyntaxError: Unexpected token <`.  The file it is complaining about is `/path/to/node_modules/vue2-google-maps/dist/components/infoWindow.vue`.

### Environment

<pre><code>
Libs:
- gridsome version: v0.5.7
- @gridsome/cli version: v0.0.9
 
Tooling:
- Node version: v11.14.0
- Platform:  Mac
</code></pre>

**Comment by Yo1L** [comment]
Hello,
Has someone found something ? Event an hint ?

Thx

**Comment by hjvedvik** [comment]
Yes, I think I know what goes wrong. Try this in your `gridsome.config.js` file:

```js
module.exports = {
  chainWebpack (config, { isServer }) {
    if (isServer) {
      config.externals([/^(vue|vue-router|vue-meta)$/])
    }
  }
}
```

**Comment by Yo1L** [comment]
You rocks !
It works for me :)

Thank you.

**Comment by Kainkainkain** [comment]
I am having this exact same issue, 
18c-iMac-Pro:project-x-final kainkainkain$ gridsome build
Gridsome v0.6.9

Initializing plugins...
Initialize - 0.39s
Load sources - 6.97s
Create GraphQL schema - 0.44s
Create pages and templates - 0.09s
Generate code - 0.09s
Bootstrap finish - 7.97s
Execute GraphQL (156 queries) - 0.01s
Write page data (156 files) - 0.13s
Compile assets - 18.37s
Failed to render /news/abc
/Users/kainkainkain/Documents/GitHub/project-x-final/node_modules/vue2-google-maps/dist/components/infoWindow.vue:3
<template>
^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/kainkainkain/Documents/GitHub/project-x-final/node_modules/vue2-google-maps/dist/main.js:4
2:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
18c-iMac-Pro:project-x-final kainkainkain$ gridsome -v
@gridsome/cli v0.3.1
gridsome v0.6.9

**Comment by Kainkainkain** [comment]
> Yes, I think I know what goes wrong. Try this in your `gridsome.config.js` file:
> 
> ```js
> module.exports = {
>   chainWebpack (config, { isServer }) {
>     if (isServer) {
>       config.externals([/^(vue|vue-router|vue-meta)$/])
>     }
>   }
> }
> ```

This gave me different errors: TypeError: this.getSafe is not a function

**Comment by eliasdiek** [comment]
> Yes, I think I know what goes wrong. Try this in your `gridsome.config.js` file:
> 
> ```js
> module.exports = {
>   chainWebpack (config, { isServer }) {
>     if (isServer) {
>       config.externals([/^(vue|vue-router|vue-meta)$/])
>     }
>   }
> }
> ```

It works perfectly for me, thanks!

**Comment by Kainkainkain** [comment]
Ok 
`module.exports = {
  chainWebpack (config, { isServer }) {
    if (isServer) {
      config.externals([/^(vue|vue-router|vue-meta)$/])
    }
  }
}`

Now does work for me. The error I was getting was from my own function which was testing wether referencing an objects.childrens.children exist before using them, and turns out whatever that was doing was throwing exceptions. So my convoluted function was the issue, and rewriting using try catch worked. 

TIL more javascript basics: Try, Catch(e).
