### ISSUE TITLE
gridsome build 0.5.0 throws error, 0.5.8 does not

### ISSUE THREAD

**Issue by vorti2** [gridsome/gridsome#408]
## Description

If I build my project with `gridsome build` where grisome has the version 0.5.0 I receive an error message, if I build the same project with gridsome version 0.5.8  the build process is frozen after the `Compile assets` step.

### Expected result

The error message should occur in both versions.

### Actual result

The error message in the 0.5.0 build is: 

```
Gridsome v0.5.0

Initialize - 1.24s
Load sources - 0.24s
Create GraphQL schema - 0.26s
Set up routes - 0s
Generate code - 0.02s
Bootstrap finish - 1.76s
Run GraphQL (32 queries) - 0.14s
Compile assets - 21.75s
Failed to render /mein-better-hr/self-checks
ReferenceError: self is not defined
    at Object.<anonymous> (node_modules/whatwg-fetch/fetch.js:2:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module.<anonymous> (assets/js/app.123f8d61.js:5127:84)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module.<anonymous> (assets/js/app.123f8d61.js:78078:21)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module.<anonymous> (src/.temp/routes.js:17:34)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Object.<anonymous> (assets/js/app.123f8d61.js:67520:18)
    at __webpack_require__ (webpack/bootstrap:19:0)
```
In gridsome 0.5.8 the build process is frozen:

```
Gridsome v0.5.8

Initialize - 1.24s
Load sources - 0.22s
Create GraphQL schema - 0.3s
Set up routes - 0s
Generate code - 0.02s
Bootstrap finish - 1.79s
Run GraphQL (32 queries) - 0.13s
Compile assets - 13.75s
``` 

### Environment

<pre><code>
Libs:
- gridsome version:0.5.0 and 0.5.8
- @gridsome/cli version: 0.0.9
 
For Tooling issues:
- Node version: 11.15.0
- Platform:  MacOS 10.14.4

</code></pre>

**Comment by vorti2** [comment]
Further debugging with the gridsome 0.5.0 version showed a problem with a non SSR compatible library, in this case with MongoDB Stitch Browser SDK:

```
Gridsome v0.5.0

Initialize - 1.6s
Load sources - 0.27s
Create GraphQL schema - 0.27s
Set up routes - 0s
Generate code - 0.02s
Bootstrap finish - 2.17s
Run GraphQL (32 queries) - 0.15s
Compile assets - 9s
Failed to render /mein-better-hr/self-checks
ReferenceError: self is not defined
    at Module../node_modules/whatwg-fetch/fetch.js (node_modules/whatwg-fetch/fetch.js:2:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../node_modules/mongodb-stitch-browser-core/dist/esm/core/internal/net/BrowserFetchTransport.js (node_modules/mongodb-stitch-browser-core/dist/esm/core/internal/net/BrowserFetchTransport.js:1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../node_modules/mongodb-stitch-browser-core/dist/esm/index.js (node_modules/mongodb-stitch-browser-core/dist/esm/index.js:1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../node_modules/mongodb-stitch-browser-sdk/dist/esm/index.js (node_modules/mongodb-stitch-browser-sdk/dist/esm/index.js:1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../src/login-service.js (assets/js/app.daf3a88e.js:85226:84)
    at __webpack_require__ (webpack/bootstrap:19:0)
```

**Comment by vorti2** [comment]
Futher testing with the different versions resulted in:

- Two used non-SSR libraries was not included in the correct way.
- After I have corrected the use of the libraries I can build with version `0.5.0'.
- In version `0.5.1' and above (I tried '0.5.1', '0.5.2', '0.5.3` and the actual ' 0.5.8' ) the build get stuck after `Compile assets`.
- This behavior is described in #366, the solution with `vue-router` does not solve my problem.

**Comment by hjvedvik** [comment]
Thanks for testing all this :) Are you able to test your project with the latest code in the master branch too? You need to follow the [contribution guide](https://github.com/gridsome/gridsome#how-to-contribute) to set up your project within the core repo locally.

**Comment by vorti2** [comment]
NP, I will test it with the latest code from the master branch on Saturday.

**Comment by hjvedvik** [comment]
The master branch was published earlier today as 0.6. So you can test the latest version instead :)

**Comment by vorti2** [comment]
@hjvedvik Sorry, this week I have no time ... Hopefully on next weekend 😉

**Comment by vorti2** [comment]
I have `camelCased` fields in all of my GraphQL schemas, so I can't do any more tests with 0.6.x until APIs for letting plugins define their own schemas with custom resolvers are implemented.

**Comment by hjvedvik** [comment]
Oh, I see. Which source plugins are you using?

**Comment by vorti2** [comment]
I use `@gridsome/source-filesystem`

**Comment by vorti2** [comment]
hi @hjvedvik any news for this issue?

**Comment by hjvedvik** [comment]
I don't think the `@gridsome/source-filesystem` is going to camel case the field names It will just use the original name from the source. It was a breaking change in 0.6 because plugins need to have full control over this :)

But we are working on some methods which will allow you to define the schema yourself in a simple way if you want to have one casing in front-matter but another casing in the schema for example.

**Comment by vorti2** [comment]
Hi @hjvedvik any progress on methods which will allow me to define the schema in a simple way if I want to have one casing in front-matter but another casing in the schema?

**Comment by vorti2** [comment]
Hi @hjvedvik, I see your comment on https://github.com/gridsome/gridsome/issues/471#issuecomment-497703058, IMHO this could solve my problem, too.

**Comment by hjvedvik** [comment]
@vorti2 Almost done :) I working in this PR #509

**Comment by tbredin** [comment]
Have also got this error coming up when I try to build a page that includes VueMapbox:

`ReferenceError: self is not defined`

Not sure if there's something I need to do to ask gridsome to handle this component, is it related?

**Comment by havardl** [comment]
@tbredin: I'm currently experiencing the same issue when using the mapbox-gl package while running the `gridsome build` command. Would you be able to share the configuration which you mention?

**Comment by tomtev** [comment]
@havardl , @tbredin Try run it inside <ClientOnly> component or in mounted()

**Comment by havardl** [comment]
Hi @tomtev, I'm not sure if I'm missing something here, but when I require mapbox-gl inside mounted() as it says in the [docs](https://gridsome.org/docs/assets-scripts/), I still get an error when running `gridsome build`. Here's the code and error output:

main.js: 
```JavaScript
import Vue from "vue";
import mapboxgl from "mapbox-gl";
export default function(Vue, { router, head, isClient }) {
  Vue.component("Layout", Layout);
  Vue.prototype.mapboxgl = mapboxgl;
}
```

MapBox.vue:
```JavaScript
  mounted() {
    window.mapboxgl = require('mapbox-gl');
    this.map = new this.mapboxgl.Map(mapOptions);
  }
```

Error:
```
Gridsome v0.7.7
...
Could not generate HTML for "/404/":
ReferenceError: self is not defined
    at assets/js/app.333d20f1.js:1525:5342
    at define (node_modules/mapbox-gl/dist/mapbox-gl.js:22:0)
    at assets/js/app.333d20f1.js:1529:1
    at assets/js/app.333d20f1.js:1500:26
    at Object.<anonymous> (node_modules/mapbox-gl/dist/mapbox-gl.js:6:1)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (assets/js/app.333d20f1.js:31993:17)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (assets/js/app.333d20f1.js:2796:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
```

**Comment by hacknug** [comment]
@havardl not sure if this is it or not but, shouldn't you check you're running on the client before trying to do anything with `window`? https://gridsome.org/docs/client-api/#process-injections

**Comment by simduchaine** [comment]
@havardl and @tbredin I'm experiencing the same issue... How did you manage to resolve the issue? 

I imported the mapbox-gl library inside `main.js`. Then, I referenced `window.mapboxgl = require("mapbox-gl");` inside the `mounted()` hook of my map component.

I also wrapped my map component inside a `<ClientOnly></ClientOnly>` tag. 

But I still get a `ReferenceError: self is not defined` error on build.

**Comment by pmcp** [comment]
Did somebody get this sorted? Running into the same problem.

**Comment by havardl** [comment]
Following input from @tomtev, I resolved it with the following setup in my map component file:

```javascript
data: function() {
 return {
  map: null
  }
},
mounted() {
 window.mapboxgl = require('mapbox-gl');
 const map = (this.map = new window.mapboxgl.Map(mapOptions));
}
```
