### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by GerhardMes** [gridsome/gridsome#410]
made a fresh install of gridsome using "yarn global add @gridsome/cli" and so on from the "getting started"

When calling gridsome deveolp the process stops after several errors. Any help, please?

here the errors

PS:: using MacOS with uptodate npm 

```
$ gridsome develop
/Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/build/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/build/Debug/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/build/Release/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/out/Debug/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/Debug/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/out/Release/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/Release/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/build/default/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/compiled/12.1.0/darwin/x64/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/addon-build/release/install-root/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/addon-build/debug/install-root/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/addon-build/default/install-root/sharp.node
 → /Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/lib/binding/node-v72-darwin-x64/sharp.node
    at bindings (/Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/lib/constructor.js:10:34)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/XXX/Desktop/Airtable/gridsome/airtable/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
XXX airtable
$ 
```

**Comment by dixonge** [comment]
I get the same on Linux Mint - fresh install of node, npm, yarn, vue and gridsome cli

**Comment by GerhardMes** [comment]
Sorry to hear. I thought I will be the only one. Also tried to fresh install everything you mentioned too.
One thought of mine was, if there is something with python? I am not sure, but I have a feeling that linking is broken.

**Comment by hjvedvik** [comment]
Do you use Node.js v12? The Sharp version Gridsome use doesn't support v12. We'll publish a fix in a few hours.

**Comment by GerhardMes** [comment]
Yes. I am using node 12.2.0 and npm 6.9.0, yarn 1.6.0, vue 3.5.5, gridsome/cli 0.0.9

So I will wait. Thanks

**Comment by ladislavsulc** [comment]
Same here (Windows 10, latest build). Thank you. Will wait also.

**Comment by dixonge** [comment]
I think I was using Node.js v12, but not sure as I am not near that PC right now.

**Comment by i-bsd** [comment]
Seems to be a problem with sharp - getting similar errors with Gatsby. Hours of searching and no solutions found.

**Comment by hjvedvik** [comment]
Node.js 12 and Sharp should work better with Gridsome 0.6 (published a few hours ago).

**Comment by robaxelsen** [comment]
Closing, as this should not be a problem anymore in 0.6. Please reopen if problem persists.
