### ISSUE TITLE
Error: Failed to install dependencies with yarn.

### ISSUE THREAD

**Issue by i-bsd** [gridsome/gridsome#416]
## Description

```
❯ Clone https://github.com/gridsome/gridsome-starter-default.git 0.44s
❯ Update project package.json 0s
❯ Install dependencies
  • Building fresh packages (4 of 4)
Error: Failed to install dependencies with yarn. Please enter goo directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

    Exit code 1
    at ChildProcess.<anonymous> (/usr/home/user/.npm-packages/lib/node_modules/@gridsome/cli/lib/commands/create.js:100:17)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
```

### Steps to reproduce

```
gridsome create goo

Simply trying to create a new site project after a fresh install.
```

### Expected result

It should create a new project without error.

### Actual result

See above.

### Environment

<pre><code>
Libs:
- gridsome version: 0.0.9
- @gridsome/cli version: 0.0.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version 66.0.5
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.2.0
- Platform:  FreeBSD 12.0-RELEASE-p3

</code></pre>

**Comment by hjvedvik** [comment]
Change the `gridsome` version in `package.json` from `0.5.0` to `0.6.0` to make it work in Node.js 12.

**Comment by i-bsd** [comment]
Worked, thanks. 

Is it always going to be necessary to manually change this in package.json?

**Comment by hjvedvik** [comment]
No, we will update the version in the starters pretty soon :)

**Comment by i-bsd** [comment]
Default starter works. Other starters are causing other errors like this when running 'gridsome develop':

```
Gridsome v0.6.0

Initializing plugins...
Initialize - 1.06s
TypeError: Cannot read property 'tags' of undefined
    at FilesystemSource.createNodeRefs (/usr/home/user/Work/gridsome/my-project/node_modules/@gridsome/source-filesystem/index.js:71:36)
    at /usr/home/user/Work/gridsome/my-project/node_modules/@gridsome/source-filesystem/index.js:63:12
    at async Promise.all (index 0)
    at async FilesystemSource.createNodes (/usr/home/user/Work/gridsome/my-project/node_modules/@gridsome/source-filesystem/index.js:59:5)
    at async /usr/home/user/Work/gridsome/my-project/node_modules/@gridsome/source-filesystem/index.js:27:7
    at async Events.dispatch (/usr/home/user/Work/gridsome/my-project/node_modules/gridsome/lib/app/Events.js:24:11)
    at async App.loadSources (/usr/home/user/Work/gridsome/my-project/node_modules/gridsome/lib/app/App.js:144:5)
    at async App.bootstrap (/usr/home/user/Work/gridsome/my-project/node_modules/gridsome/lib/app/App.js:58:7)
    at async module.exports (/usr/home/user/Work/gridsome/my-project/node_modules/gridsome/lib/app/index.js:10:3)
    at async module.exports (/usr/home/user/Work/gridsome/my-project/node_modules/gridsome/lib/develop.js:10:15)
```

**Comment by hjvedvik** [comment]
I think that error should have been fixed in `@gridsome/source-filesystem@0.4.1`.

**Comment by i-bsd** [comment]
Now I'm getting:
```
ERROR  Failed to compile with 3 errors
 error  in ./src/templates/Tag.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "coverImage" on type "Post". Did you mean "cover_image"?
```

**Comment by hjvedvik** [comment]
Yes, that is one of the breaking changes in 0.6. Fields keep their original name. I think @tomtev will update the blog starter tomorrow :)

**Comment by i-bsd** [comment]
Ok. Well at least it's good to know there's nothing wrong with my setup.

I'll wait for the updates. Thanks!

**Comment by 010arya010** [comment]
i have this problem. but i cant solve it

**Comment by 010arya010** [comment]
how can 

> i have this problem. but i cant solve it. how can i?

i solved it.
i used yarn instead npm.:))
