### ISSUE TITLE
Strange error every now and then after adding a new dependency

### ISSUE THREAD

**Issue by lobo-tuerto** [gridsome/gridsome#42]
Hello, I've come across this multiple times, it usually happens after I install a new dependency then try to run the development server:

```bash
$ yarn serve
yarn run v1.12.3
warning ../../package.json: No license field
$ gridsome develop
internal/modules/cjs/loader.js:736
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/yomero/tmp/my-site/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It'll keep erroring out until I `rm -rf node_modules` then do a `yarn install`.
Any ideas on what's going on?

Cheers,
VA

**Comment by lobo-tuerto** [comment]
This seems related to adding packages while the server is running.
Will close for now, as there is a fix for the error state:

```
rm -rf node_modules
yarn install
```
