### ISSUE TITLE
Regression in `@gridsome/source-wordpress`

### ISSUE THREAD

**Issue by hacknug** [gridsome/gridsome#421]
## Description

Latest version of `@gridsome/source-wordpress` (v0.3.0) breaks when trying to work with things that were available on v0.2.2.

### Steps to reproduce

Clone [this repo](https://github.com/hacknug/klayaya/), run `npm run develop` to check everything works fine. Upgrade `@gridsome/source-wordpress` to v0.3.0 and watch it break.

### Expected result

Everything should still work? 🤔 

### Actual result

GraphQL is missing some previously available things like `format` and `featuredMedia` in my case.

You can see they are still available on the REST endpoint: https://dev.nestorvera.com/klayaya/wp-json/wp/v2/posts/1649!!

**Comment by hjvedvik** [comment]
`@gridsome/source-wordpress` 0.3 is meant to work with `gridsome` 0.6. 

I tried your project with the latest versions and it seems to work as expected. Just change all `to` attributes from `:to="{ name: 'store' }"` to `to="/store"` where you have `g-links` with named routes.

**Comment by hacknug** [comment]
That's weird. I've tried updating both dependencies and changing the attributes like you suggested (I even remove all `g-link` instances from the project) but I still get this error:

```bash
yarn run v1.13.0
$ gridsome develop
Gridsome v0.6.0

Initializing plugins...
Initialize - 0.94s
Loading data from https://dev.nestorvera.com/klayaya
Error: Status 401 - https://dev.nestorvera.com/klayaya/wp-json/wp/v2/users
Load sources - 4.21s
Create GraphQL schema - 0.42s
Create pages and templates - 0.22s
Generate code - 0.03s
Bootstrap finish - 5.82s
 95% emitting HtmlWebpackPlugin/Users/nestor/Code/klayaya/node_modules/toposort/index.js:35
      throw new Error('Cyclic dependency' + nodeRep)
      ^

Error: Cyclic dependency
    at visit (/Users/nestor/Code/klayaya/node_modules/toposort/index.js:35:13)
    at visit (/Users/nestor/Code/klayaya/node_modules/toposort/index.js:53:9)
    at visit (/Users/nestor/Code/klayaya/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/Users/nestor/Code/klayaya/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/Users/nestor/Code/klayaya/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/Users/nestor/Code/klayaya/node_modules/html-webpack-plugin/index.js:364:35)
    at /Users/nestor/Code/klayaya/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/nestor/Code/klayaya/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/nestor/Code/klayaya/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/nestor/Code/klayaya/node_modules/webpack/lib/Compiler.js:441:19)
    at onCompiled (/Users/nestor/Code/klayaya/node_modules/webpack/lib/Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (/Users/nestor/Code/klayaya/node_modules/webpack/lib/Compiler.js:630:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/nestor/Code/klayaya/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/nestor/Code/klayaya/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/nestor/Code/klayaya/node_modules/webpack/lib/Compiler.js:627:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/nestor/Code/klayaya/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hjvedvik** [comment]
I just got the same error. Working on a fix now :)

**Comment by hacknug** [comment]
@hjvedvik works like a charm now. Thanks! ❤️
