### ISSUE TITLE
Support for async components

### ISSUE THREAD

**Issue by atilacamurca** [gridsome/gridsome#443]
## Description

Support for Vue async component syntax, as seen in the [docs](https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components)

```js
Vue.component('my-component': () => import('./my-async-component'))
```

### Steps to reproduce

This is a [link to a codesandbox example](https://codesandbox.io/s/saravieiragridsomestartercodesandbox-juetk)

The command `npm run develop` runs fine.

But the command `npm run build` fails.

```
Failed to render /
TypeError: _vm._ssrEscape is not a function
    at render (src/components/VExample.vue?42ed:1:46)
    at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:78:0)
    at /sandbox/node_modules/vue-server-renderer/build.prod.js:1:65642
    at Ki (/sandbox/node_modules/vue-server-renderer/build.prod.js:1:65823)
    at i (/sandbox/node_modules/vue-server-renderer/build.prod.js:1:68839)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Expected result

I know the development process is different than the process build, which the code must be SSR compatible. We should have a way around it, or a documentation about it.

### Actual result

The build process fail.

### Environment

<pre><code>
Libs:
- gridsome version: v0.6.0
- @gridsome/cli version: v0.1.0

Browser:
- [X] Chrome (desktop) version 74
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.16.0 
- Platform: Linux  

Others:

</code></pre>

**Comment by Al-Rozhkov** [comment]
Definitely it doesn't work on codesandbox. But I can't reproduce it locally with Node v10.15.3. Either global import inside `main.js` and inside a page component works for me.

**Comment by atilacamurca** [comment]
This is the project that I've been working on <https://github.com/atilacamurca/agregador-fc>.

After install Node v10.15.3, I'm still getting the error:

```
Failed to render /rodada/2019/4
TypeError: _vm._ssrEscape is not a function
    at render (src/components/scouts/Scout.vue?6238:1:287)
    at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:78:0)
```

**Comment by hjvedvik** [comment]
You can try to uninstall Vue in your project. Gridsome has Vue included.

**Comment by atilacamurca** [comment]
Even uninstalling Vue, the same thing happens.

**Comment by atilacamurca** [comment]
Just pasting a link to a branch that still uses async components, because I needed to revert to continue to work on my website: <https://github.com/atilacamurca/agregador-fc/tree/async-components>

**Comment by atilacamurca** [comment]
@Al-Rozhkov, you state that you couldn't reproduce the problem locally, but have you use the same project configured in the codesandbox? Can you download the project and test that again?

I was able to reproduce it myself using node v10.16.1. I think I forgot to mention that the async component is also a functional component, and I think that is causing the problem.

The error when I run `gridsome build` is:

```bash
> @ build /tmp/saravieira-gridsome-starter-codesandbox
> gridsome build

Gridsome v0.6.7

Initializing plugins...
Initialize - 0.77s
Load sources - 0s
Create GraphQL schema - 0.07s
Create pages and templates - 0.05s
Generate code - 0.03s
Bootstrap finish - 0.92s
Execute GraphQL (0 queries) - 0s
Write page data (0 files) - 0s
Compile assets - 7.82s
Failed to render /
TypeError: _vm._ssrEscape is not a function
    at render (src/components/VExample.vue?fdff:1:46)
    at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:78:0)
    at /tmp/saravieira-gridsome-starter-codesandbox/node_modules/vue-server-renderer/build.prod.js:1:65580
    at Ki (/tmp/saravieira-gridsome-starter-codesandbox/node_modules/vue-server-renderer/build.prod.js:1:65761)
    at i (/tmp/saravieira-gridsome-starter-codesandbox/node_modules/vue-server-renderer/build.prod.js:1:68777)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `gridsome build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by atilacamurca** [comment]
On [vuejs/vue-loader](https://github.com/vuejs/vue-loader) some people have a similar issue, and it seems to be fixed.

See <https://github.com/vuejs/vue-loader/issues/1170>.

**Comment by sanscheese** [comment]
Think I've just hit this too.
