### ISSUE TITLE
FileNode > Skipping Duplicate Path

### ISSUE THREAD

**Issue by marwie** [gridsome/gridsome#460]
I started modifying the [Forestry Starter](https://gridsome.org/starters/forestry-starter)
While gridsome develop I copied a markdown file, renamed it and edited it. When saving gridsome crashed.

After that I get the following warning during gridsome develop startup

<pre><code>
Initialize - 2.41s
FileNode > Skipping duplicate path for /projects/markdownfile
File Node > Skipping duplicate path for /projects/anothermarkdownfile
Load sources - 0.15s
...
</code></pre>

Editing any of the markdown files crashes gridsome again. The error says:

<pre><code>
C:\path\to\project\node_modules\gridsome\lib\app\ContentTypeCollection.js:153
      throw new Error(`Could not find node to update with id: ${id}`)
      ^

Error: Could not find node to update with id: 2210c22291bfd6c45a4d50f17237acfd
    at ContentTypeCollection.updateNode (C:\path\to\project\node_modules\gridsome\lib\app\ContentTypeCollection.js:153:13)
    at FSWatcher.watcher.on.file (C:\path\to\project\node_modules\@gridsome\source-filesystem\index.js:112:21)
    at FSWatcher.emit (events.js:189:13)
    at FSWatcher.<anonymous> (C:\path\to\project\node_modules\chokidar\index.js:199:15)
    at FSWatcher._emit (C:\path\to\project\node_modules\chokidar\index.js:241:5)
    at FSWatcher.<anonymous> (C:\path\to\project\node_modules\chokidar\lib\nodefs-handler.js:267:16)
    at FSReqWrap.oncomplete (fs.js:154:5)

</code></pre>

**Comment by marwie** [comment]
perfect, just after opening the issue I found that the problem was caused by gridsome-plugin-remark-youtube which I added to gridsome config and which was also watching the project path for markdown file changes.

**Comment by RehanSaeed** [comment]
@marwie I'm also getting the same issue. How did you get the youtube plugin to play nice?

**Comment by marwie** [comment]
Hi @RehanSaeed 
I'm not entirely sure anymore but I think I ended up not using the plugin but embed youtube via html in markdown.
