### ISSUE TITLE
Vue Tiny Slider Component

### ISSUE THREAD

**Issue by inalbisdev** [gridsome/gridsome#474]
Hello,

I'am using the vue-tiny-slider (https://github.com/viktorlarsson/vue-tiny-slider) as component.

Here is the script code in the page:

```
<script>
    import VueTinySlider from 'vue-tiny-slider';
    import PostResume from '~/components/PostResume.vue';
    export default {
        components:{
            PostResume,
            VueTinySlider
        },

    }
</script>

```

And this is the HTML

```
      <tiny-slider :mouse-drag="true" :loop="false" items="1" gutter="20">
                <post-resume v-for="post in $page.allPost.edges"
                             :key="post.node.id"
                             :title="post.node.title"
                             :media="post.node.media"
                             :path="post.node.path"
                             :excerpt="post.node.excerpt"></post-resume>
            </tiny-slider>
```

The slider works at development profile, but when i build the proyect it fails 
throwing this error at the console:
```
Failed to render /blog
ReferenceError: window is not defined
    at Object.198 (node_modules/vue-tiny-slider/dist/index.js:1:234)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.203 (assets/js/page--src--pages--blog--index-vue.6a945117.js:138:12)
    at __webpack_require__ (webpack/bootstrap:25:0)
```

Why? Is the implementing ok?

Thanks!

**Comment by cizza** [comment]
Hi,

I've run into this issue as well. This will break in the build process because in node.js there's no window object, which this plugin exposes and most likely relies on. Please have a look at this page in the gridsome documentation https://gridsome.org/docs/assets-scripts/#without-ssr-support . What to pay attention to is the <ClientOnly> tag and the dynamic import of requested components (tiny slider in this case).

**Comment by inalbisdev** [comment]
Hello,

Thanks for the answer. I' have change my code to:

```
<script>
    export default {
        components: {
            Carousel: () =>
                import ('vue-tiny-slider')
                    .then(m => m.Carousel)
                    .catch(),
            Slide: () =>
                import ('vue-tiny-slider')
                    .then(m => m.Slide)
                    .catch()

        },
    }
</script>
```

And the HTML is:

```
<template>
    <Layout>
        <ClientOnly>
            <carousel :mouse-drag="true" :loop="false" items="1" gutter="20">
                <slide>a</slide>
                <slide>b</slide>
            </carousel>
        </ClientOnly>
    </Layout>
</template>

```

And now i get this error:

````
vue.runtime.esm.js?2b0e:3586 Uncaught (in promise) TypeError: Cannot read property '__esModule' of undefined
    at ensureCtor (vue.runtime.esm.js?2b0e:3586)
    at eval (vue.runtime.esm.js?2b0e:3659)
    at eval (vue.runtime.esm.js?2b0e:336)
```
I think the code is correct, is that so?

Thanks!

**Comment by hjvedvik** [comment]
The `vue-tiny-slider` export is a bit different. Try with this code instead:

```js
export default {
  components: {
    TinySlider: () => import('VueTinySlider')
  }
}
```

```html
<Layout>
  <ClientOnly>
    <TinySlider :mouse-drag="true" :loop="false" items="1" gutter="20">
      <div>Slider item #1</div>
    </TinySlider>
  </ClientOnly>
</Layout>
```

**Comment by inalbisdev** [comment]
Perfect, now works in dev and i can build the project. Thanks!
