### ISSUE TITLE
Build not working as dev is working.

### ISSUE THREAD

**Issue by herrbomm** [gridsome/gridsome#522]
## Description

When i try **gridsome build**, nothing is shown (blank page). In **gridsome dev** everything is working fine. Im not sure why but i guess it is due to path-configuration or something. 

Also i get this error.

`Failed to render /service
/Users/fabbsen/Aufträge/site/Relaunch 2019/Website/gridsome-site (update)/node_modules/vue-flickity/src/flickity.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^

SyntaxError: Unexpected token <
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)`

### Steps to reproduce

gridsome build

### Expected result

Render the page as expected and working in grindsome dev

### Actual result

Error or nothing is shown up (when clearing the error)

**Comment by sergeyfilimonov** [comment]
@herrbomm Looks as a Vue hydration error. Could you post your code from the flickity.vue file here?
