### ISSUE TITLE
Error: Names must match when added link to a pdf file

### ISSUE THREAD

**Issue by nuriaheep** [gridsome/gridsome#578]
## Description

I get this error when I add a link to a pdf file inside a WYSIWYG field at WordPress

```bash
7:06:32 PM: Bootstrap finish - 10.55s
7:06:32 PM: Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "1" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "2" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "3" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "4" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "5" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "7" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "8" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "9" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "10" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "11" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "12" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "1" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "2" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "3" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "4" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "5" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "7" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "8" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "9" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "10" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "11" does not.
7:06:32 PM: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "12" does not.
7:06:32 PM:     at assertValidSchema (/opt/build/repo/node_modules/graphql/type/validate.js:71:11)
7:06:32 PM:     at assertValidExecutionArguments (/opt/build/repo/node_modules/graphql/execution/execute.js:163:35)
7:06:32 PM:     at executeImpl (/opt/build/repo/node_modules/graphql/execution/execute.js:84:3)
7:06:32 PM:     at App.execute [as _execute] (/opt/build/repo/node_modules/graphql/execution/execute.js:62:63)
7:06:32 PM:     at App.graphql (/opt/build/repo/node_modules/gridsome/lib/app/App.js:280:24)
7:06:32 PM:     at pMap (/opt/build/repo/node_modules/gridsome/lib/graphql/executeQueries.js:25:19)
7:06:32 PM:     at Promise.resolve.then.element (/opt/build/repo/node_modules/gridsome/node_modules/p-map/index.js:47:21)
```

### Steps to reproduce

I'm deploying with Netlify, and this error fails the deploy.
The filename is a single word, like: somefile.pdf

**Comment by u12206050** [comment]
I've also had this error a few times but when I try building again it is gone. Have you tried just building again? Do you get the same result?

**Comment by jxlstudio** [comment]
I'm having this issue with my Slug field when generating the schema from Airtable. All my slugs are plain text with no numbers/integers.

Tried rebuilding, did not work.
