### ISSUE TITLE
Can't find manifest.json so won't build

### ISSUE THREAD

**Issue by tcober** [gridsome/gridsome#581]
## Description

Can't run gridsome build

### Steps to reproduce

ran gridsome build and got 

```Gridsome v0.6.7

Initializing plugins...
Initialize - 0.4s
Load sources - 0.42s
Create GraphQL schema - 0.05s
Create pages and templates - 0.07s
Generate code - 0.03s
Bootstrap finish - 0.97s
Execute GraphQL (1 queries) - 0.02s
Write page data (1 files) - 0.01s
Compile assets - 2.95s                                                                                                                                                                                    . Error: Cannot find module '/Users/thomascober/Desktop/MNCludeGridsome/dist/assets/manifest/client.json'
Require stack:
- /Users/thomascober/Desktop/MNCludeGridsome/node_modules/gridsome/lib/server/createRenderFn.js
- /Users/thomascober/Desktop/MNCludeGridsome/node_modules/gridsome/lib/workers/html-writer.js
- /Users/thomascober/Desktop/MNCludeGridsome/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at createRenderFn (/Users/thomascober/Desktop/MNCludeGridsome/node_modules/gridsome/lib/server/createRenderFn.js:14:26)
    at Object.exports.render (/Users/thomascober/Desktop/MNCludeGridsome/node_modules/gridsome/lib/workers/html-writer.js:10:18)
    at execFunction (/Users/thomascober/Desktop/MNCludeGridsome/node_modules/jest-worker/build/workers/processChild.js:165:17)
    at execHelper (/Users/thomascober/Desktop/MNCludeGridsome/node_modules/jest-worker/build/workers/processChild.js:149:5)
    at execMethod (/Users/thomascober/Desktop/MNCludeGridsome/node_modules/jest-worker/build/workers/processChild.js:153:5)
    at process.<anonymous> (/Users/thomascober/Desktop/MNCludeGridsome/node_modules/jest-worker/build/workers/processChild.js:72:7)```

**Comment by cmseeling** [comment]
I was running into the same issue and ended up duplicating my project, adding files in one at a time. 

The build command kept working in the clean version until I added in the .env file. The version I was using had NODE_ENV=development so I tried changing that value to production and the build command succeeded.

**Comment by TheAkshitS** [comment]
Removing NODE_ENV from my env file worked for me too.

**Comment by jbuhacoff** [comment]
I ran into the same issue with Gridsome 0.7.23:

```
> @inboss/main-website-html5@0.1.0 build
> gridsome build

Gridsome v0.7.23

Initializing plugins...
Tag > Failed to add node: Duplicate key for property id: user-experience
Tag > Failed to add node: Duplicate key for property id: quality
Tag > Failed to add node: Duplicate key for property id: security
Load sources - 0.31s
Create GraphQL schema - 0.21s
Create pages and templates - 0.3s
Generate temporary code - 0.13s
Bootstrap finish - 5.52s
Compile assets - 57.09s
Execute GraphQL (87 queries) - 0.78s
Error: Cannot find module '/home/jonathan/workspace/inboss/main-website-html5/dist/assets/manifest/client.json'
Require stack:
- /home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/lib/server/createRenderFn.js
- /home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/lib/workers/html-writer.js
- /home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/node_modules/jest-worker/build/workers/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at createRenderFn (/home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/lib/server/createRenderFn.js:16:26)
    at exports.render (/home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/lib/workers/html-writer.js:15:18)
    at execFunction (/home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/node_modules/jest-worker/build/workers/processChild.js:165:17)
    at execHelper (/home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/node_modules/jest-worker/build/workers/processChild.js:149:5)
    at execMethod (/home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/node_modules/jest-worker/build/workers/processChild.js:153:5)
    at process.<anonymous> (/home/jonathan/workspace/inboss/main-website-html5/node_modules/gridsome/node_modules/jest-worker/build/workers/processChild.js:72:7)
```

I have been building with `export NODE_ENV=production` and it was fine until now. I also tried `unset NODE_ENV` just now just to see. Still got the error.

Following the code, looks like this is related to gridsome's use of vue:

https://v2.ssr.vuejs.org/api/#clientmanifest
https://v2.ssr.vuejs.org/guide/build-config.html#client-config

Since I've done many successful builds with Gridsome before and it's been at 0.7.23 for years, I know it's not due to any change in Gridsome. I checked the dependency versions, Gridsome references vue 2.6.10 and my project uses vue 2.7.16. I tried downgrading vue, vue-server-renderer, and vue-template-compiler to 2.6.10 but I'm still getting this error.
