### ISSUE TITLE
Gridsome v0.6.7 it's broken

### ISSUE THREAD

**Issue by Waaflee** [gridsome/gridsome#612]
## Description

Can't run `gridsome develop`, `gridsome build` nor `gridsome serve`. It always fails with error message. Started happening in a project, so I tried starting from scratch with the forestry starter and the same, then tried with default starter (no starter option) and the same.
All started after `yarn upgrade`

### Steps to reproduce

Create a new project with `gridsome create this-does-not-build`, `cd` into it and run `gridsome develop`.

### Expected result

Should build and serve the project.

### Actual result

It will say it Failed to compile with 2 errors. Apparently they are associated to Babel

> gridsome develop

Gridsome v0.6.7

Initializing plugins...
Initialize - 0.39s
Load sources - 0s
Create GraphQL schema - 0.07s
Create pages and templates - 0.07s
Generate code - 0.02s
Bootstrap finish - 0.56s

 ERROR  Failed to compile with 2 errors                                 11:28:11

 error  in ./node_modules/gridsome/app/entry.client.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/wafle/Documentos/WEB/holi/node_modules/gridsome/app/entry.client.js: Cannot find module 'private'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/wafle/Documentos/WEB/holi/node_modules/regenerator-transform/lib/meta.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/wafle/Documentos/WEB/holi/node_modules/regenerator-transform/lib/emit.js:7:36)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)

 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./node_modules/gridsome/app/entry.sockjs.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/wafle/Documentos/WEB/holi/node_modules/gridsome/app/entry.sockjs.js: Cannot find module 'private'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/wafle/Documentos/WEB/holi/node_modules/regenerator-transform/lib/meta.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/wafle/Documentos/WEB/holi/node_modules/regenerator-transform/lib/emit.js:7:36)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)

 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

### Environment

<pre><code>
Libs:
@gridsome/cli v0.2.1
gridsome v0.6.7

Browser:
- Don't apply since you can't get it to run
 
For Tooling issues:
- Node version: v11.15.0
- Platform: Linux
</code></pre>

**Comment by hjvedvik** [comment]
I can't reproduce the error in v0.6.7 here. Does it still fail for you? It might have been a temporary bug in another package somewhere in the dependency tree. Try running `yarn upgrade` again.

**Comment by Waaflee** [comment]
I got and update of node.js to v12.9.1 and that seemed to fix it, guess was the combination of my outdated version with the newer release of gridsome.

**Comment by balain** [comment]
I just encountered this issue after installing axios. After removing the node_modules and running `npm i` again, the problem persisted. Reinstalling @babel/core and cache-loader fixed the issue for me.
