### ISSUE TITLE
createSchema not working

### ISSUE THREAD

**Issue by u12206050** [gridsome/gridsome#649]
## Description

Can't get a simple schema to work without non-understandable errors.

### Steps to reproduce

Define an example schema in `gridsome.server.js`:
```
api.createSchema(({ addSchema, graphql }) => {
    addSchema(new graphql.GraphQLSchema({
      query: new graphql.GraphQLObjectType({
        name: 'Example',
        fields: {
          id: graphql.GraphQLString,
          name: graphql.GraphQLString,
          mockData: graphql.GraphQLString,
          source: graphql.GraphQLString
        }
      })
    }))
  })
```

### Expected result

Should now have an extra graphql query available in explorer called `Example`

### Actual result

Just get console errors:

```
Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: The type of Query.id must be Output Type but got: undefined.

The type of Query.name must be Output Type but got: undefined.

The type of Query.mockData must be Output Type but got: undefined.

The type of Query.source must be Output Type but got: undefined.
    at assertValidSchema (./node_modules/graphql/type/validate.js:71:11)
    at validate (./node_modules/graphql/validation/validate.js:54:35)
    at module.exports (./node_modules/gridsome/lib/plugins/vue-components/lib/validate.js:4:10)
    at Object.module.exports (./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:25:20)
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.6.9
- @gridsome/cli version: 0.2.1

For Tooling issues:
- Node version: 10.1

**Comment by hjvedvik** [comment]
The options you pass to `GraphQLObjectType` isn't valid according to the [docs](https://graphql.org/graphql-js/type/#examples). Each field must be an object with a `type` property :)

**Comment by u12206050** [comment]
Ah, was wondering where the documentation was :) Thanks
