### ISSUE TITLE
Cannot run after update

### ISSUE THREAD

**Issue by matt88120** [gridsome/gridsome#662]
## Description

After updating to Gridsome 0.7.1, cannot run develop or build. 

Error after "yarn develop" & "yarn build"
TypeError: Cannot set property 'extensions' of undefined
    at processInferredFields (../node_modules/gridsome/lib/graphql/nodes/index.js:138:26)
    at createFields (../node_modules/gridsome/lib/graphql/nodes/index.js:109:3)
    at createNodesSchema (../node_modules/gridsome/lib/graphql/nodes/index.js:28:5)
    at createSchema (../node_modules/gridsome/lib/graphql/createSchema.js:59:3)
    at Schema.buildSchema (../node_modules/gridsome/lib/app/Schema.js:28:28)
    at Plugins.createSchema (../node_modules/gridsome/lib/app/Plugins.js:93:22)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
error Command failed with exit code 1.

**Comment by tomtev** [comment]
@matt88120 Is it possible to try your repo?

**Comment by matt88120** [comment]
Of course.

**Comment by hjvedvik** [comment]
I was able to reproduce the error if I had an object field which was empty on every node. Should be fixed in the next release :)

**Comment by hjvedvik** [comment]
Fixed in version 0.7.2. Re-open if you are still experiencing this issue.
