### ISSUE TITLE
JisonLexerError thrown by postcss-calc during build

### ISSUE THREAD

**Issue by rich-choy** [gridsome/gridsome#680]
## Description

**Disclaimer**
I don't know if this is an actual bug, or if I'm doing something terribly wrong. Please forgive me if it's the latter.

**The problem**
I have a project whose Vue components use SCSS variables inside the `<style>` tag. For example:

`Page.vue`
```
<template>
   <main class="page"><slot/></main>
</template>

<style lang="scss">
@import '~/scss/_variables';
main.page {
  position: relative;
  margin-top: $navbar-height + $navbar-padding-vertical * 2;
  z-index: 0;
  min-height: calc(100vh - ($navbar-height + $navbar-padding-vertical * 2));
}
</style>
```

There are no problems with this when I browse on the local Webpack dev server brought up by `gridsome develop`. When I run `gridsome build`, however, the NodeJS build process terminates abnormally.

The problem originates on the line containing `calc`.

### Steps to reproduce

Delete the contents of the project `dist` folder.

Add the following snippet into any Vue component that is rendered at build time:

```
<style lang="scss">
$navbar-height: 50px;                                                                                                                               
$navbar-padding-vertical: 20px;
main.page {
  position: relative;
  margin-top: $navbar-height + $navbar-padding-vertical * 2;
  z-index: 0;
  min-height: calc(100vh - ($navbar-height + $navbar-padding-vertical * 2));
}
</style>
```

Then execute:
```
npm run build
```

### Expected result

Build artifacts appear in the `dist` folder.

### Actual result

Build artifacts do not appear in the `dist` folder. Instead, the build process exits abnormally with the following message on standard output:
```
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100vh - ($navbar-height + $navbar-padding-vertical * 2)
^...........^
    at /project/assets/css/0.styles.afacec5e.css:27:55
    at Object.parseError (/project/node_modules/postcss-calc/dist/parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (/project/node_modules/postcss-calc/dist/parser.js:2297:44)
    at Object.lexer_next [as next] (/project/node_modules/postcss-calc/dist/parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (/project/node_modules/postcss-calc/dist/parser.js:3367:18)
    at fastLex (/project/node_modules/postcss-calc/dist/parser.js:1567:27)
    at Parser.parse (/project/node_modules/postcss-calc/dist/parser.js:1641:30)
    at /project/node_modules/postcss-calc/dist/lib/transform.js:30:30
    at walk (/project/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/project/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/project/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/project/node_modules/postcss-calc/dist/lib/transform.js:59:100)
    at /project/node_modules/postcss-calc/dist/index.js:25:51
    at /project/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/project/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/project/node_modules/postcss/lib/container.js:131:17)
    at /project/node_modules/postcss/lib/container.js:148:24
```

### Environment

<pre><code>
Libs:

- @gridsome/cli v0.2.2
- gridsome v0.6.9
 
For Tooling issues:
- Node version: v11.10.0
- Platform: Linux ce0d126f7986 5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
</code></pre>

**Comment by hjvedvik** [comment]
Try with this syntax for the variables which are inside `calc()` instead:

```
calc(100vh - (#{$navbar-height + $navbar-padding-vertical} * 2));
```

**Comment by rich-choy** [comment]
It builds! :D

Thank you so much!!!
