### ISSUE TITLE
Global filters broke after upgrading to 0.7.5

### ISSUE THREAD

**Issue by lesaff** [gridsome/gridsome#710]
## Description
I have a set of global vue filters on `plugins/filters.js` that I call in `gridsome.config.js`. This works fine up to `0.6.9`. Once upgraded to `0.7.5` it won't compile anymore and threw an error

### Expected result
It should compile

### Actual result
Error message 
```
Gridsome v0.7.5

Initializing plugins...
/Users/rudy/Sites/###REDACTED####/src/plugins/filters.js:1
import Vue from 'vue'
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Plugins.initialize (/Users/rudy/Sites/###REDACTED####/node_modules/gridsome/lib/app/Plugins.js:45:11)
```

### Environment

<pre><code>
Libs:
- gridsome version: 0.7.5
- @gridsome/cli version: 0.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.3  
- Platform:  Mac 

Others:

</code></pre>

**Comment by hjvedvik** [comment]
Are you using `src/plugins/filters.js` as a plugin in `gridsome.config.js`? Then that file will be executed in a Node.js context. You can add global Vue filters in the `src/main.js` file instead.

**Comment by lesaff** [comment]
@hjvedvik yes I am. It was working fine with `0.6.9`. Any particular changes in `0.7.x` that break it?
