### ISSUE TITLE
Error: Variable "$id" of non-null type "ID!" must not be null

### ISSUE THREAD

**Issue by jlsyspeople** [gridsome/gridsome#742]
Gridsome works like a charm - with no errors at all, when it comes to executing `gridsome develop` on a source plugin, that I'm developing at the moment.

But running `gridsome build` on the very same setup throws the following error, which prevents any docs from being generated and saved in `/dist`:

```
GraphQL request:24:12

An error occurred while executing page-query for src\pages\Snow.vue

An error occurred while executing page-query for src\pages\Note.vue

An error occurred while executing page-query for src\pages\Know.vue


Error: Variable "$id" of non-null type "ID!" must not be null.

GraphQL request:24:12
23 |
24 | query Snow($id: ID!) {
   |            ^
25 |   snow(id: $id) {
    at throwError (C:\Users\JanLarsen\Documents\nodejs\gridsome_0_7_7\snowheadless\node_modules\gridsome\lib\app\build\executeQueries.js:21:13)
    at pMap.concurrency (C:\Users\JanLarsen\Documents\nodejs\gridsome_0_7_7\snowheadless\node_modules\gridsome\lib\app\build\executeQueries.js:49:9)
```

The setup includes 3 data sources (1 markdown and 2 REST APIs).

The ids from API consists of 32 alpha-numeric characters. The markdown-ids origin from `  "@gridsome/source-filesystem": "^0.6.0"`, which I've not tampered with at all.

Fixes with no result so far:
1. `query Snow($id: ID!)` changed to `query Snow($id: String!)`
2. `id.toString()` in plugin
3. `id` converted to pure numbers - incl. `parseInt`

The finish line seems so close! What am I missing here?

Setup:
- Gridsome v. 0.7.7
- Node.js v. 12.11.1
- Firefox v. 69
- Windows 10

Thanks all the way across Skagerak for an awesome tool for multi-source publishing the Vue-way.

**Comment by hjvedvik** [comment]
It looks like you have variables in a `page-query` for a page in `src/pages`, but components in that folder are not receiving any variables. Do you have a template defined for `src/pages/Snow.vue`?

**Comment by jlsyspeople** [comment]
Thnx for the quick response, which was spot on.

Single-record templates should certainly reside in the `/templates`-folder. When they do that, `gridsome build` works fine.

Strange, though, that I managed to run a complete website with `gridsome develop` - without any template... Apparently the template-reference in `gridsome.config.js` `component: './src/pages/Snow.vue'` was accepted by `gridsome develop`.
