### ISSUE TITLE
ClientOnly 

### ISSUE THREAD

**Issue by alivefromupstairs** [gridsome/gridsome#764]
`gridsome build` with `<ClientOnly>` as instructed in the docs, skips this component using `vue-awesome-swiper` and places a `<!---->` in the dist/index.html.   

### Steps to reproduce
**demo:** https://github.com/alivefromupstairs/gridsome-ssr-broken

**important part:**
```vue
<template>
  <ClientOnly>
    <swiper :options="swiperOption">
      <swiper-slide>
        <g-image class="image" src="~/assets/img1.jpg" />
      </swiper-slide>
      <swiper-slide>
        <g-image class="image" src="~/assets/img2.jpg" />
      </swiper-slide>
      <swiper-slide>
        <g-image class="image" src="~/assets/img3.jpg" />
      </swiper-slide>
      <swiper-slide>
        <g-image class="image" src="~/assets/img4.jpg" />
      </swiper-slide>
      <swiper-slide>
        <g-image class="image" src="~/assets/img5.jpg" />
      </swiper-slide>
    </swiper>
  </ClientOnly>
</template>

<script>
export default {
  metaInfo: {
    title: "Hello, world!"
  },
  components: {
    swiper: () =>
      import("vue-awesome-swiper")
        .then(m => m.swiper)
        .catch(),
    swiperSlide: () =>
      import("vue-awesome-swiper")
        .then(m => m.swiperSlide)
        .catch()
  },
  data() {
    return {
      swiperOption: {
        slidesPerView: "auto",
        centeredSlides: true,
        spaceBetween: 20,
        grabCursor: true,
        autoplay: {
          delay: 5000
        },
        mousewheel: {
          invert: false
        }
      }
    };
  }
};
</script>
```

also, if I place `ClientOnly` inside the component not the page `index.vue` I get an error:
```yml
(node:15972) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__esModule' of undefined
    at Re (D:\Projects\cireur.ma\node_modules\vue\dist\vue.runtime.common.prod.js:6:24223)
    at D:\Projects\cireur.ma\node_modules\vue\dist\vue.runtime.common.prod.js:6:21188
    at D:\Projects\cireur.ma\node_modules\vue\dist\vue.runtime.common.prod.js:6:2394
(node:15972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)    
(node:15972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
### Environment of my actual project
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.8
    gridsome-plugin-pug: ^0.0.3 => 0.0.3

**Comment by courcelan** [comment]
This may seem weird, but since you have `<swiper-slide>` and `<g-image>`, have you tried `<client-only>`? I'm not sure you are able to mix and match styles.

If that doesn't work, because I can't remember my issues with it. Try this instead:

```
data () {
    return {
        ...
        isClient: process.isClient,
        ...
    }
}

<template>
    <template v-if="isClient">
        <!-- ...swiper code... -->
    </template>
</template>
```

`ClientOnly` is basically a wrapper around `process.isClient`, so you can use that instead. Its what I use for a carousel that needs to be loaded only in the client.

**Comment by alivefromupstairs** [comment]
@courcelan That did not solve it, unfortunately . also, kebab-case and PascalCase are interchangeable in vue, and if memory served me right, kebab-case is the recommended one for templating and PascalCase for vue files and importing.

**Comment by courcelan** [comment]
@alivefromupstairs right, thats why I was wondering about `<ClientOnly>` in your template as by convention, I'd expect `<client-only>`.

In terms of `<client-only>` not working, have you tried with some simple content to see if its actually the Gridsome code thats not working rather than the Swiper? 

Another thing: https://github.com/surmon-china/vue-awesome-swiper/issues/563
 Maybe try that instead:

```javascript
  components: {
    swiper: () =>
      import("vue-awesome-swiper/src")
        .then(m => m.swiper)
        .catch(),
    swiperSlide: () =>
      import("vue-awesome-swiper/src")
        .then(m => m.swiperSlide)
        .catch()
  },
```

**Comment by hjvedvik** [comment]
@alivefromupstairs The `<ClientOnly>` component is meant to leave a `<!---->` in the generated markup because the components inside it will only be rendered in the browser. But having it as a root component for a page will cause trouble because Vue needs a DOM element to mount the app. Using a `<div>` (with `<ClientOnly>` inside) as root element instead should work better :)

Gridsome should probably have pages wrapped in another element to avoid issues like this.

**Comment by alivefromupstairs** [comment]
@hjvedvik they have an example on SSR with Nuxt https://github.com/surmon-china/vue-awesome-swiper/#ssr but I couldn't get it to work properly with Gridsome yet. once I do, I'll post the solution and close the issue.

**Comment by jsappme** [comment]
any update on this issue, i am having the same issue integrating it with gridsome

**Comment by giddens9527** [comment]
any update on this issue, i am having the same issue integrating it with gridsome
