### ISSUE TITLE
Gridsome build ignores browser field of node module

### ISSUE THREAD

**Issue by arnoson** [gridsome/gridsome#781]
## Description

I'm using paper.js with gridsome. `gridsome develop` works fine, but `gridsome build` crashes with the following error:

```
Error: Can't resolve 'jsdom/lib/jsdom/living/generated/utils' in '/Users/arnoson/Development/gridsome-paper/node_modules/paper/dist/node'
    at doResolve (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/Resolver.js:209:21)
    at hook.callAsync (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn4 (eval at create (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at resolver.doResolve (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40)
    at hook.callAsync (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn2 (eval at create (/Users/arnoson/Development/gridsome-paper/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
```
Looking inside paper.js [package.json](https://github.com/paperjs/paper.js/blob/aa9dc86e7bc210bb7e4e0215bd34240e93636462/package.json#L34-L41) there is `browser` field that disables the library that is causing the error, so it seems that gridsome ignores this field.
``` json
"browser": {
  "canvas": false,
  "jsdom": false,
  "jsdom/lib/jsdom/living/generated/utils": false,
  "source-map-support": false,
  "./dist/node/self.js": false,
  "./dist/node/extend.js": false
},
```

### Steps to reproduce
Create a new gridsome project.
```
gridsome create gridsome-paper
```
Install paper.js
```
npm install paper
```
Import paper.js somewhere
``` javascript
import paper from 'paper'
```
[Here](https://github.com/arnoson/gridsome-paper) is a demo project that renders a red circle with paper.js in the index.vue page.

### Environment
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     L9600  @ 2.13GHz
  Binaries:
    Node: 11.8.0 - ~/.nvm/versions/node/v11.8.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v11.8.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 70.0
    Safari: 13.0.2
  npmPackages:
    gridsome: ^0.7.0 => 0.7.9 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

**Comment by casderooij** [comment]
This issue can be solved by adding a webpack IgnorePlugin inside the `gridsome.config.js` file.

```javascript
const webpack = require('webpack');

module.exports = {
  siteName: 'gridsome-paper',
  plugins: [],
  chainWebpack: config => {
    config.plugin().use(new webpack.IgnorePlugin(/jsdom/));
  },
};
```
