### ISSUE TITLE
Gridsome Sitemap Plugin throwing "path" argument error

### ISSUE THREAD

**Issue by liambarr** [gridsome/gridsome#793]
## Description

I'm not sure what I'm missing, it seems to match the example given. However when I try to build the project I'm thrown with error:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### My gridsome.config.js file looks like:

```
// This is where project configuration and installed plugin options are located.
// Learn more: https://gridsome.org/docs/config

module.exports = {
  siteName: "Portfolio",
  siteUrl: `mysiteurl`,
  host: "0.0.0.0",
  titleTemplate: "%s",
  siteDescription: "Site description",
  plugins: [
    {
      use: "@gridsome/source-filesystem",
      options: {
        path: "projects/**/*.md",
        typeName: "ProjectPost",
        resolveAbsolutePaths: true,
        remark: {
          externalLinksTarget: "_blank",
          externalLinksRel: ["nofollow", "noopener", "noreferrer"],
          
        }
      }
    },
    {
      use: "@gridsome/source-filesystem",
      options: {
        path: "journal/**/*.md",
        typeName: "JournalPost",
        resolveAbsolutePaths: true,
        remark: {
          externalLinksTarget: "_blank",
          externalLinksRel: ["nofollow", "noopener", "noreferrer"]
        }
      }
    },
    {
      use: '@gridsome/plugin-sitemap',
      options: {
        cacheTime: 600000, // default
        config: {
          '/projects/*': {
            changefreq: 'weekly',
            priority: 0.7
          },
          '/journal/*': {
            changefreq: 'monthly',
            priority: 0.5
          }
        }
      }
    }
  ],
  transformers: {
    remark: {
      plugins: ["@gridsome/remark-prismjs",'remark-toc']
    }
  }
};
```

I feel like I'm missing something so simple, I just can't find it

**Comment by hjvedvik** [comment]
Which version of Gridsome and the sitemap plugin do you use? I might help to update to the latest version of both :)

**Comment by liambarr** [comment]
> Which version of Gridsome and the sitemap plugin do you use? I might help to update to the latest version of both :)

I feel so stupid right now. Thanks so much!

**Comment by liambarr** [comment]
> Which version of Gridsome and the sitemap plugin do you use? I might help to update to the latest version of both :)

I feel so stupid right now. Thanks so much! Gridsome needed an update

**Comment by cyupa** [comment]
I'm having the same issue:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.isAbsolute (path.js:1144:5)
    at resolvePluginEntries (/Volumes/Data/Projects/Personal/bughound/userdesk-marketing/node_modules/gridsome/lib/app/loadConfig.js:398:19)
    at plugins.map (/Volumes/Data/Projects/Personal/bughound/userdesk-marketing/node_modules/gridsome/lib/app/loadConfig.js:310:21)
    at Array.map (<anonymous>)
    at normalizePlugins (/Volumes/Data/Projects/Personal/bughound/userdesk-marketing/node_modules/gridsome/lib/app/loadConfig.js:303:18)
    at module.exports (/Volumes/Data/Projects/Personal/bughound/userdesk-marketing/node_modules/gridsome/lib/app/loadConfig.js:76:20)
    at new App (/Volumes/Data/Projects/Personal/bughound/userdesk-marketing/node_modules/gridsome/lib/app/App.js:23:42)
    at module.exports (/Volumes/Data/Projects/Personal/bughound/userdesk-marketing/node_modules/gridsome/lib/app/index.js:10:20)
    at module.exports (/Volumes/Data/Projects/Personal/bughound/userdesk-marketing/node_modules/gridsome/lib/develop.js:20:21)
```



```
  "dependencies": {
    "@gridsome/plugin-google-analytics": "^0.1.0",
    "@gridsome/plugin-sitemap": "^0.2.3",
    "@gridsome/source-filesystem": "^0.6.2",
    "@gridsome/transformer-remark": "^0.5.0",
    "@noxify/gridsome-remark-classes": "^1.0.0",
    "@noxify/gridsome-remark-table-align": "^1.0.0",
    "@tailwindcss/ui": "^0.1.3",
    "gridsome": "^0.7.13",
    "gridsome-plugin-remark-prismjs-all": "^0.3.5",
    "gridsome-source-static-meta": "^1.0.1",
    "lodash": "^4.17.15",
    "pluralize": "^8.0.0",
    "tailwindcss": "^1.2.0",
    "tailwindcss-gradients": "^3.0.0",
    "tailwindcss-tables": "^0.4.0",
    "typeface-inter": "^3.12.0",
    "v-tooltip": "^2.0.3"
  },
```

```
    [
      {
        use: '@gridsome/plugin-sitemap',
        options: {
          cacheTime: 600000, // default
          exclude: ['/pricing'],
          config: {
            '/blog/*': {
              changefreq: 'weekly',
              priority: 0.5
            },
            '/*': {
              changefreq: 'monthly',
              priority: 0.7
            }
          }
        }
      }
    ],
```
