### ISSUE TITLE
Using vue-remark and transformer-remark in the same project produces RemarkHeadingLevels error

### ISSUE THREAD

**Issue by macguirerintoul** [gridsome/gridsome#815]
## Description

I'm trying to use both `vue-remark` (for more complex 'project' content that uses Vue components) and `transformer-remark` (for articles, because it includes things like `timeToRead`) in the same project, but it's producing an error.

### Steps to reproduce

[Repo (use `development` branch)](https://github.com/macguirerintoul/macguire.me/tree/development)

1. Run `gridsome develop`

### Expected result

The site should start up

### Actual result

```
Initializing plugins...
Load sources - 0.12s
Error: Schema must contain uniquely named types but contains multiple types named "RemarkHeadingLevels".
    at typeMapReducer (/Users/mtr/dev/macguire.me/node_modules/graphql/type/schema.js:262:13)
    at Array.reduce (<anonymous>)
    at typeMapReducer (/Users/mtr/dev/macguire.me/node_modules/graphql/type/schema.js:285:34)
    at typeMapReducer (/Users/mtr/dev/macguire.me/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/Users/mtr/dev/macguire.me/node_modules/graphql/type/schema.js:145:28)
    at SchemaComposer.buildSchema (/Users/mtr/dev/macguire.me/node_modules/graphql-compose/lib/SchemaComposer.js:131:12)
    at Schema.buildSchema (/Users/mtr/dev/macguire.me/node_modules/gridsome/lib/app/Schema.js:35:35)
    at Plugins.createSchema (/Users/mtr/dev/macguire.me/node_modules/gridsome/lib/app/Plugins.js:94:22)
```

### Environment
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0.3
    Safari: 11.1.2
  npmPackages:
    @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.0
    @gridsome/source-filesystem: ^0.6.0 => 0.6.2
    @gridsome/transformer-remark: ^0.3.0 => 0.3.4
    @gridsome/vue-remark: ^0.1.4 => 0.1.8
    gridsome: ^0.7.10 => 0.7.10
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

**Comment by prionator** [comment]
We're also seeing this!

**Comment by hjvedvik** [comment]
It might be caused by two different versions of `@gridsome/transformer-remark` in the dependency tree. I'll see if I can do something about it.

**Comment by rolbr** [comment]
I've rolled back my repo and incrementally upgraded dependencies and this error pops back up as soon as I upgrade `@gridsome/vue-remark from 0.1.7 to 0.1.8`

    "dependencies": {
      ...
      "@gridsome/transformer-remark": "^0.3.4",
      "@gridsome/vue-remark": "0.1.8",
      "gridsome": "^0.7.11",
      "gridsome-plugin-remark-shiki": "^0.3.0",
      ...
    },

after the upgrade to 0.1.8

    $ yarn list @gridsome/transformer-remark
    ├─ @gridsome/transformer-remark@0.3.4
    └─ @gridsome/vue-remark@0.1.8   
       └─ @gridsome/transformer-remark@0.4.0

after the downgrade to 0.1.7

    $ yarn upgrade @gridsome/vue-remark@0.1.7
    $ yarn list @gridsome/transformer-remark
    └─ @gridsome/transformer-remark@0.3.4

After the downgrade running `gridsome develop` is working fine again.

I'd say @hjvedvik is on the right track! 🥳

**Comment by distinctperspective** [comment]
$ gridsome build
Gridsome v0.7.11

Initializing plugins...
Load sources - 0.08s
Error: Schema must contain uniquely named types but contains multiple types named "RemarkHeadingLevels".
    at typeMapReducer (C:\Users\dthre\Documents\Github\gridsome-portfolio-starter\node_modules\graphql\type\schema.js:262:13)
    at Array.reduce (<anonymous>)
    at typeMapReducer (C:\Users\dthre\Documents\Github\gridsome-portfolio-starter\node_modules\graphql\type\schema.js:285:34)
    at typeMapReducer (C:\Users\dthre\Documents\Github\gridsome-portfolio-starter\node_modules\graphql\type\schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (C:\Users\dthre\Documents\Github\gridsome-portfolio-starter\node_modules\graphql\type\schema.js:145:28)
    at SchemaComposer.buildSchema (C:\Users\dthre\Documents\Github\gridsome-portfolio-starter\node_modules\graphql-compose\lib\SchemaComposer.js:133:12)
    at Schema.buildSchema (C:\Users\dthre\Documents\Github\gridsome-portfolio-starter\node_modules\gridsome\lib\app\Schema.js:35:35)
    at Plugins.createSchema (C:\Users\dthre\Documents\Github\gridsome-portfolio-starter\node_modules\gridsome\lib\app\Plugins.js:94:22)

**Comment by marcodeluca** [comment]
Any updates? I'm getting this error as well. Saw this https://github.com/drehimself/gridsome-portfolio-starter/pull/69 but I'm one version up from that - Gridsome v0.7.13 - and this error persists. Also saw a suggestion about installing with yarn vs npm, but that caused more problems:)

**Comment by convenientstop** [comment]
@marcodeluca, just had this issue myself, and I bumped `@gridsome/transformer-remark` to `^0.5.0` and that fixed it for me. Might be another version issue for you as well, so I would just run yarn/npm updates for your dependencies.

**Comment by cco3** [comment]
I believe this can be closed.
