### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by kjugi** [gridsome/gridsome#820]
## Summary
Add the ability to easily tests accord of our projects based on gridsome. If we are able to create such tests maybe it's worth to describe it in docs? As I can see in this repo you are actually testing some of the example projects.

I know the difference between unit and e2e tests. I'm most interested in unit tests for now.

### Basic example
The base example can be found [here](https://github.com/gridsome/gridsome/tree/master/gridsome/lib/__tests__) and some docs help in gatsby [here](https://www.gatsbyjs.org/docs/unit-testing/)

### Motivation
I just want to test my app based on gridsome and don't know how to start b/c some base guide from vue-test-utils docs and my experience with the test is not enough to create such tests.

**Comment by nick-wireless** [comment]
I experimented with: 'vue add @vue/unit-jest', which seemed to work, however I note the example test was set to the starter kit of Vue CLI vs the Gridsome starter kit.

**Comment by MarcelloTheArcane** [comment]
@nick-wireless I just tried this and got the following error:

```
 ERROR  TypeError: Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at add (/usr/local/lib/node_modules/@vue/cli/lib/add.js:23:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by sebj54** [comment]
Here is how I made it work with Jest:

First install modules (some of these are already installed with Gridsome) : 

```
npm install --save-dev jest vue-jest babel-core babel-jest @vue/test-utils
```

Create a `jest.config.js` in the root directory:

```js
/**
 * @see https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-unit-jest/presets/default
 */
module.exports = {
    moduleFileExtensions: [
        'js',
        'jsx',
        'json',
        'vue',
    ],
    transform: {
        '^.+\\.vue$': require.resolve('vue-jest'),
        '^.+\\.jsx?$': require.resolve('babel-jest'),
    },
    transformIgnorePatterns: ['/node_modules/'],
    moduleNameMapper: {
        '^~/(.*)$': '<rootDir>/src/$1',
    },
    testMatch: [
        '**/tests/unit/**/*.spec.[jt]s?(x)',
        '**/__tests__/*.[jt]s?(x)',
    ],
}
```

Also create a `babel.config.js` file in the root directory:

```js
module.exports = {
    presets: ['@babel/preset-env'],
}
```

Add a test script in `package.json`:

```json
{
  "scripts": {
    ...
    "test": "jest"
  }
}
```

Finally, create your unit test, for example: `./tests/unit/hello.spec.js`

```js
import { shallowMount } from '@vue/test-utils'
import HelloWorld from '../HelloWorld.vue'

describe('HelloWorld.vue', () => {
  test('renders props.msg when passed', () => {
    const msg = 'new message'
    const wrapper = shallowMount(HelloWorld, {
      propsData: { msg }
    })
    expect(wrapper.text()).toMatch(msg)
  })
})
```

Then execute your test with `npm test`.
