### ISSUE TITLE
Gridsome Build failing on GitHub Actions and CircleCI

### ISSUE THREAD

**Issue by Microflash** [gridsome/gridsome#843]
## Description

When `gridsome build` is run on a Linux container, it fails while resolving paths (which is done through `enhanced-resolve` as I can see from the logs). The same build passes when built locally.

### Steps to reproduce

Use [this commit](https://github.com/Microflash/microflash.github.io/commit/dd511dbeef4051f604a13681b8f8969534adff2c) and build it with GitHub Actions or CircleCI.

### Expected result

The build should be successful.

### Actual result

The build fails while resolving paths with the following error:

```sh
$ gridsome build
Gridsome v0.7.11

Initializing plugins...
Load sources - 0.07s
Create GraphQL schema - 0.05s
Create pages and templates - 0.04s
Generate temporary code - 0.01s
Bootstrap finish - 0.68s

Error: Can't resolve '~/components/PostCard' in '/home/circleci/repo/src/pages'
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:657:1)
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/AliasPlugin.js:67:43
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/circleci/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/circleci/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

### Environment

```sh
System:
  OS: Linux 4.15 Debian GNU/Linux 10 (buster) 10 (buster)
  CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
Binaries:
  Node: 12.13.1 - /tmp/yarn--1575049297810-0.667054669572319/node
  Yarn: 1.19.1 - /tmp/yarn--1575049297810-0.667054669572319/yarn
  npm: 6.12.1 - /usr/local/bin/npm
npmPackages:
  @gridsome/plugin-google-analytics: ^0.1.0 => 0.1.0 
  @gridsome/plugin-sitemap: ^0.2.3 => 0.2.3 
  @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
  @gridsome/transformer-remark: ^0.4.0 => 0.4.0 
  gridsome: ^0.7.11 => 0.7.11 
  gridsome-plugin-feed: ^1.0.2 => 1.0.2 
  gridsome-plugin-remark-shiki: ^0.3.0 => 0.3.0 
```

**Comment by Microflash** [comment]
I found what was the problem. Windows does not care about the file name cases and hence was able to resolve the file name `Postcard` but Linux wasn't. I renamed the component file and things went green.
