### ISSUE TITLE
<g-image> never loading on netlify

### ISSUE THREAD

**Issue by brettwray** [gridsome/gridsome#845]
## Description

Using <g-image> I'm finding that the images are not ever fully resolving, ie the loading class is not removed so the blurry placeholder images are served.

This works fine locally, it also works fine when using netlify-dev to serve the site locally, but once it is on the netlify instance the images do not resolve. There are no errors in the netlify build logs.

### Steps to reproduce

Link to project on Netlify: https://pedantic-lichterman-bb733f.netlify.com/

Using <g-image> without immediate="true" results in the placeholder remaining on the image and the correct image never fully loading.

### Expected result

The blur applied as a placeholder should be removed when the image is in the viewport.

### Actual result

The blur is never removed and the image is not loaded.

### Environment
(Gridsome info is an unknown command)

  "dependencies": {
    "@gridsome/source-wordpress": "^0.4.3",
    "buefy": "^0.8.8",
    "eslint-plugin-gridsome": "^1.3.2",
    "gridsome": "^0.7.11",
    "gridsome-helper-json": "^1.0.3",
    "lazysizes": "^5.2.0-beta1",
    "typeface-open-sans": "0.0.75",
    "typeface-rubik": "0.0.72"
  },
  "devDependencies": {
    "@mdi/font": "^4.5.95",
    "axios": "^0.19.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.0",
    "style-resources-loader": "^1.2.1",
    "vuex": "^3.1.1",
    "webpack-node-externals": "^1.7.2"
  }

**Comment by brettwray** [comment]
To add to this a little bit, I've tested this by deploying to Zeit Now and everything renders just fine. 

https://floorcleanerfred-baph7ldb3.now.sh/

Additionally, only on Netlify live servers I'm getting an error in the console, this does not happen locally or on Zeit.

`Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:40737)
    at p (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:53348)
    at d (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:53085)
    at h (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:53434)
    at O (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:56778)
    at O (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:56713)
    at o.__patch__ (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:57136)
    at o.t._update (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:34436)
    at o.i (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:64454)
    at pn.get (https://pedantic-lichterman-bb733f.netlify.com/assets/js/app.4fb7282d.js:7:26695)`

**Comment by hjvedvik** [comment]
It seems to work fine on Netlify now :) Did you find out what was causing it? Netlify Asset optimization maybe?

**Comment by brettwray** [comment]
Whoops! I should have marked this as closed.

It took a while to figure out, I even tested a different vue static site generator just to see. The issue ended up being the contact form, it was not configured correctly and netlify injects a hidden input into the contact forms that have the netlify attribute. Because it was not configured correctly that error was being thrown because the hidden input that netlify adds could not be appended.
