### ISSUE TITLE
Can't Import File into Gridsome-Server.js

### ISSUE THREAD

**Issue by moshemo** [gridsome/gridsome#848]
## Description

I am trying to import a `js` file into the `gridsome-server.js` file.  However, no matter what format I use (`require` or `import`) I get an error message.

### Steps to reproduce

I have created a file called `firebase.js` which contains the following code:

```
import firebase from 'firebase/app'
import 'firebase/firestore'

const config = {
  apiKey: '[APIKEY],
  authDomain: '[AUTHDOMAIN],
  databaseURL: '[DATABASEURL],
  projectId: '[PROJECTID],
  storageBucket: '[STORAGEBUCKET],
  messagingSenderId: '[MESSAGINGSENDERID],
  appId: '[APPID]'
}

firebase.initializeApp(config)

const db = firebase.firestore()

export default db
```

I then try to import that file into `gridsome-server.js`:  `const db = require('./src/config/firebase')`

Doing so gives me the following error (see below.

I also try a couple of variations (which also give me errors)

* `import db from...`
* `import { db } `from...`
* Changing the export in `firebase.js` to a named export: `export const db...`

### Expected result

`gridsome develop` would run properly without any errors and the `firebase.js` file would be imported into `gridsome-server.js`.

### Actual result

If I use the `CommonJS require` syntax, I get the following error when I do `gridsome run`:

```
Initializing plugins...
SyntaxError: gridsome.server.js: Unexpected identifier (1:12)

> 1 | const db = require('./src/config/firebase')
    |            ^
  2 |
  3 | module.exports = function(api) {
  4 |   api.loadSource(({ addCollection }) => {
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I use the `es6 import` syntax, then I get a different error:

```
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Plugins.initialize (C:\code\tutorials\vue\gridsome\vuetify-gridsome\node_modules\gridsome\lib\app\Plugins.js:45:11)
    at App.init (C:\code\tutorials\vue\gridsome\vuetify-gridsome\node_modules\gridsome\lib\app\App.js:120:18)
    at App.bootstrap (C:\code\tutorials\vue\gridsome\vuetify-gridsome\node_modules\gridsome\lib\app\App.js:49:16)
    at module.exports (C:\code\tutorials\vue\gridsome\vuetify-gridsome\node_modules\gridsome\lib\app\index.js:12:18)
    at module.exports (C:\code\tutorials\vue\gridsome\vuetify-gridsome\node_modules\gridsome\lib\develop.js:20:21)
    at C:\code\tutorials\vue\gridsome\vuetify-gridsome\node_modules\gridsome\index.js:44:12
    at Command.program.command.description.option.option.action.args (C:\code\tutorials\vue\gridsome\vuetify-gridsome\node_modules\gridsome\index.js:13:44)
    at Command.listener (C:\code\tutorials\vue\gridsome\vuetify-gridsome\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:198:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Except that one time it is called an `Unexpected identifier` and the other an `Unexpected token` depending on whether I used a default or named export.

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
  Binaries:
    Node: 12.13.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.17.3 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.12.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.1.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.10

**Comment by moshemo** [comment]
Here is the answer (makes sure to note the comments):
