### ISSUE TITLE
Error after install of gridsome-source-mysql

### ISSUE THREAD

**Issue by tmrwltd** [gridsome/gridsome#855]
## Description

I try to install the gridsome-source-mysql plugin, but get an error after run gridsome

### Steps to reproduce

Install from the Terminal in VSC with the command "npm install gridsome-source-mysql --save"

### Expected result

What should happen?

### Actual result

gridsome develop
Gridsome v0.7.11

Initializing plugins...
O:\code\vue\node_modules\gridsome-source-mysql\index.js:174
          await pMap(Q.images, async imgField => {
          ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Plugins.initialize (O:\code\vue\node_modules\gridsome\lib\app\Plugins.js:45:11)
    at App.init (O:\code\vue\node_modules\gridsome\lib\app\App.js:120:18)
    at App.bootstrap (O:\code\vue\node_modules\gridsome\lib\app\App.js:49:16)
    at module.exports (O:\code\vue\node_modules\gridsome\lib\app\index.js:12:18)
    at module.exports (O:\code\vue\node_modules\gridsome\lib\develop.js:20:21)
    at O:\code\vue\node_modules\gridsome\index.js:44:12
    at Command.<anonymous> (O:\code\vue\node_modules\gridsome\index.js:13:44)
    at Command.listener (C:\Users\torst\AppData\Local\Yarn\Data\global\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (C:\Users\torst\AppData\Local\Yarn\Data\global\node_modules\commander\index.js:651:12)

### Environment

 System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.11
    gridsome-plugin-pwa: ^0.0.10 => 0.0.10
    gridsome-plugin-robots-txt: ^1.0.2 => 1.0.2
    gridsome-source-mysql: ^1.5.3 => 1.5.3

**Comment by hjvedvik** [comment]
This should probably be fixed by the author of `gridsome-source-mysql` instead. I see you've already opened an issue at https://github.com/u12206050/gridsome-source-mysql/issues/1 :)
