### ISSUE TITLE
Update @tryghost/content-api to support Ghost v3

### ISSUE THREAD

**Issue by emilol** [gridsome/gridsome#867]
## Summary

Ghost v3 has released, and with it a new minor version `1.4` of `@tryghost/content-api` [that supports v3](https://github.com/TryGhost/Ghost-SDK/commit/3c63ad14ce7fec513e5d0d0fe3a9bdbc41330ca0#diff-16f5ae3bee46d87f9e83ba96c384ab73R3):

```diff
// @tryghost/content-api
- const supportedVersions = ['v2', 'canary'];
+ const supportedVersions = ['v2', 'v3', 'canary'];
```

Currently `source-ghost` is on 1.3. When suppling a version option of 'v3', it fails with the error: 

```cmd
$ gridsome develop
Gridsome v0.7.8

Initializing plugins...
Error: GhostContentAPI Config Invalid: @tryghost/content-api does not support the supplied version
    at GhostContentAPI (C:\Code\Personal\my-website\node_modules\@gridsome\source-ghost\node_modules\@tryghost\content-api\cjs\content-api.js:25:15)
    at new GhostContentAPI (C:\Code\Personal\my-website\node_modules\@gridsome\source-ghost\node_modules\@tryghost\content-api\cjs\content-api.js:18:16)
    at new GhostSource (C:\Code\Personal\my-website\node_modules\@gridsome\source-ghost\index.js:26:23)
    at Plugins.initialize (C:\Code\Personal\my-website\node_modules\gridsome\lib\app\Plugins.js:61:11)
    at App.init (C:\Code\Personal\my-website\node_modules\gridsome\lib\app\App.js:118:18)
    at App.bootstrap (C:\Code\Personal\my-website\node_modules\gridsome\lib\app\App.js:47:16)
    at module.exports (C:\Code\Personal\my-website\node_modules\gridsome\lib\app\index.js:12:18)
    at module.exports (C:\Code\Personal\my-website\node_modules\gridsome\lib\develop.js:19:21)
    at C:\Code\Personal\my-website\node_modules\gridsome\index.js:44:12
    at Command.program.command.description.option.option.action.args (C:\Code\Personal\my-website\node_modules\gridsome\index.js:13:44)
    at Command.listener (C:\Code\Personal\my-website\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (C:\Code\Personal\my-website\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Code\Personal\my-website\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Code\Personal\my-website\node_modules\@gridsome\cli\bin\gridsome.js:79:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Motivation

Updating `@gridsome/source-ghost` to the latest release will allow gridsome users to pull content from v3 ghost blogs.

### Basic example

```diff
// @gridsome/source-ghost
-    "@tryghost/content-api": "^1.2.2",
+    "@tryghost/content-api": "^1.3.4",
```

Would allow:

```
// gridsome.config.js

module.exports = {
  plugins: [
    {
      use: '@gridsome/source-ghost',
      options: {
        typeName: 'Ghost',
        baseUrl: 'http://localhost:2368',
        ...
        version: 'v3'  <--- currently causes the above error
      }
    }
  ],
}
```

**Comment by emilol** [comment]
Thanks for the merge! How long will it take to get this up on npm? Do you need me to bump the package version, or is there a build process for this?
