### ISSUE TITLE
Resolution error on build

### ISSUE THREAD

**Issue by Berkmann18** [gridsome/gridsome#878]
## Description

`gridsome develop` leads to this:
```
Error: Can't resolve 'core-js/modules/es6.array.filter' in '/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/gridsome/app'
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/maxie/GDrive/RHUL/y5/CS4821/FullUnit_1920_MaximilianBerkmann/spirit-cartel/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
```

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).
1. Have `@gridsome/remark-prismjs@0.3.0`, `gridsome-source-firestore@1.1.1` installed like in https://github.com/RHUL-CS-Projects/FullUnit_1920_MaximilianBerkmann/tree/dev/spirit-cartel (it's private but I can try to provide access if needed)
2. Try to run `npm run build` (i.e. `gridsome build`)
3. Watch the CLI

### Expected result

The build suceed

### Actual result

See output above.

### Environment

```
  System:
    OS: Linux 5.4 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Firefox: 71.0 (missing Opera 65.0, Chrome, Vivaldi and Brave)
  npmPackages:
    @gridsome/remark-prismjs: ^0.3.0 => 0.3.0 
    @gridsome/transformer-remark: ^0.4.0 => 0.4.0 
    gridsome: ^0.7.11 => 0.7.11 
    gridsome-source-firestore: ^1.1.1 => 1.1.1 
  npmGlobalPackages:
    @gridsome/cli: 0.3.1
```

**Comment by Berkmann18** [comment]
https://github.com/brunocodutra/webapp-webpack-plugin/issues/72#issuecomment-479233871 seems to help with this issue (even tho it requires installing an _unmaintained_ version of `core-js`).
Doing this lead to another error:
```
TypeError: Object(...) is not a function
    at Object.110 (src/storage.js:4:26)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.116 (assets/js/page--src--templates--page-vue.ba7f553b.js:80:14)
    at __webpack_require__ (webpack/bootstrap:25:0)
```
Re-installing node packages doesn't help (including deleting the `package-lock.json`).

I've also tried solutions on https://github.com/gatsbyjs/gatsby/issues/7862 (since gatsby seems to be equally affected by the changes in Babel).
