### ISSUE TITLE
Cannot read property 'args' of undefined at calcTotalPages on build (taxonomy paginated)

### ISSUE THREAD

**Issue by vdilly** [gridsome/gridsome#899]
## Description

Error when trying to `gridsome develop` when it comes to paginated taxonomy :
```
TypeError: Cannot read property 'args' of undefined
    at calcTotalPages (C:\www\rabbit_gridsome\node_modules\gridsome\lib\app\build\createRenderQueue.js:40:42)       
    at createRenderQueue (C:\www\rabbit_gridsome\node_modules\gridsome\lib\app\build\createRenderQueue.js:20:28)    
    at module.exports (C:\www\rabbit_gridsome\node_modules\gridsome\lib\build.js:24:17)
```

### Steps to reproduce

From the gridsome wordpress starter I buildt this sample project :
https://github.com/vdilly/gridsome-taxonomy-issue

Clone the project, npm install inside.

Following the docs for [paginated taxonomy](https://gridsome.org/docs/pagination/#paginated-taxonomy-pages), I set a simple query on Wordpress Tags in Index.vue ([take a look at the commit](https://github.com/vdilly/gridsome-taxonomy-issue/commit/f0ef9e757311291eeb344005d1acfb7f6883805a))

Now try to `gridsome develop` and  `gridsome build` the project.

### Expected result

Should work fine on both commands.

### Actual result

Works fine with `gridsome develop` , fail on `gridsome build`

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  Binaries:
    Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gridsome: ^0.7.0 => 0.7.12

**Comment by ahsath** [comment]
Any news? I'm having the same issue, I talked about on this on discord

**Comment by Dzeganovsky** [comment]
Get the same problem.
