### ISSUE TITLE
Error processing images on using gitlab ci and node with alpine 

### ISSUE THREAD

**Issue by ebertti** [gridsome/gridsome#930]
## Description

Error processing images on using gitlab ci and node with alpine 

### Steps to reproduce

In .gitlab-ci.yml

using image: `image: node:12.14.1-alpine3.11`
add this package: `apk -v --update util-linux` to work `lscpu` command
after run: `yarn build`

### Expected result

Build all the files

### Actual result

```
Processing images (20 images) - 0% Error: Failed to process image uploads/example.jpg. write EPIPE
at pMap.concurrency (/builds/path/node_modules/gridsome/lib/workers/image-processor.js:113:13)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Job failed: exit code 1
```

### Environment

`$ gridsome info`

```
  System:
    OS: Linux 4.19 Alpine Linux
    CPU: (1) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
  Binaries:
    Node: 12.14.1 - /tmp/yarn--1578597320922-0.4357794108324313/node
    Yarn: 1.21.1 - /tmp/yarn--1578597320922-0.4357794108324313/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  npmPackages:
    @gridsome/remark-prismjs: 0.3.0 => 0.3.0 
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2 
    @gridsome/transformer-remark: ^0.4.0 => 0.4.0 
    gridsome: ^0.7.11 => 0.7.12 
```

**Comment by eagleera** [comment]
did you figure it out how to solve it?

**Comment by bartvollebregt** [comment]
Having the same issue.

Here's part of my Gitlab yml:

```
build:gridsome:
    image: node:13-alpine3.11
    stage: build
    before_script:
        - apk add -U util-linux
        - apk add --no-cache git
        - apk add yarn
        - yarn install
    script:
        - yarn build
    artifacts:
        paths:
            - dist

```

**Comment by borisdiakur** [comment]
Switched to `node:13-buster` and the issue was resolved.

**Comment by bartvollebregt** [comment]
> Switched to `node:13-buster` and the issue was resolved.

That's what I did as well for now but it's not really a solution.
Debian is a much larger container than Alpine.

**Comment by pmochine** [comment]
@bartvollebregt Wow it took me some hours. But finally, I have managed everything one needs for gridsome. 

Just use: `image: kujin1000/gridsome-docker:12`

One simple gitlab-ci.xml:

```
image: kujin1000/gridsome-docker:12

production:
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  environment:
    name: production
  only:
    - master
```

And doing other stuff as well. But with this docker file you can use ssh as well.

**Comment by itsnotsaved** [comment]
Hello everyone,
I thought to use https://github.com/gridsome/gridsome.org for a hobby project but i couldn't deploy it to gitlab pages using this guide https://gridsome.org/docs/deploy-to-gitlab/
The gridsome.config.js code seems different, i don't understand how to follow the 2nd step, "2. Set outputDir in gridsome.config.js to 'public'." https://github.com/gridsome/gridsome.org/blob/master/gridsome.config.js

I already deployed it blindly with this gridsome-ci.yml and failed
```
image: node:10.15.0

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    # Optional: this gzips all files, so GitLab can serve compressed assets.
    - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - master
```

```
[0KRunning with gitlab-runner 16.3.0~beta.108.g2b6048b4 (2b6048b4)[0;m
[0K  on green-3.saas-linux-small-amd64.runners-manager.gitlab.com/default Jhc_Jxvh, system ID: s_0e6850b2bce1[0;m
[0K  feature flags: FF_USE_IMPROVED_URL_MASKING:true, FF_RESOLVE_FULL_TLS_CHAIN:false[0;m
section_start:1693895398:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m[0;m
[0KUsing Docker executor with image node:10.15.0 ...[0;m
[0KPulling docker image node:10.15.0 ...[0;m
[0KUsing docker image sha256:b826d251321b21e7c97be6deb759cc1144e19313e2f117e8aa8c864c73729153 for node:10.15.0 with digest node@sha256:c9a51b7f2f3774f39058bb436ed62d66f415f32b9386e5c35c3fb4854722ed84 ...[0;m
section_end:1693895416:prepare_executor
[0Ksection_start:1693895416:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-jhcjxvh-project-49071060-concurrent-0 via runner-jhcjxvh-s-l-s-amd64-1693895355-db2a5474...
section_end:1693895421:prepare_script
[0Ksection_start:1693895421:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Initialized empty Git repository in /builds/itsnotsaved/gridsome-1/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out 0307663c as detached HEAD (ref is master)...[0;m

[32;1mSkipping Git submodules setup[0;m
[32;1m$ git remote set-url origin "${CI_REPOSITORY_URL}"[0;m
section_end:1693895423:get_sources
[0Ksection_start:1693895423:restore_cache
[0K[0K[36;1mRestoring cache[0;m[0;m
[32;1mChecking cache for default-protected...[0;m
[0;33mWARNING: file does not exist                      [0;m 
[0;33mFailed to extract cache[0;m
section_end:1693895424:restore_cache
[0Ksection_start:1693895424:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:b826d251321b21e7c97be6deb759cc1144e19313e2f117e8aa8c864c73729153 for node:10.15.0 with digest node@sha256:c9a51b7f2f3774f39058bb436ed62d66f415f32b9386e5c35c3fb4854722ed84 ...[0;m
[32;1m$ npm install[0;m
npm WARN deprecated docsearch.js@2.6.3: This package has been deprecated and is no longer maintained. Please use @docsearch/js.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated express-graphql@0.9.0: This package is no longer maintained. We recommend using `graphql-http` instead. Please consult the migration document https://github.com/graphql/graphql-http#migrating-express-grpahql.
npm WARN deprecated algoliasearch-helper@2.28.1: 3.7.3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated vue-analytics@5.22.1: Sorry but vue-analytics is no longer maintained. I would suggest you switch to vue-gtag, with love, the guy who made the package.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm WARN deprecated trim@0.0.1: Use String.prototype.trim() instead
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated puppeteer@2.1.1: < 19.4.0 is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> sharp@0.25.4 install /builds/itsnotsaved/gridsome-1/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz

> puppeteer@2.1.1 install /builds/itsnotsaved/gridsome-1/node_modules/puppeteer
> node install.js


Chromium downloaded to /builds/itsnotsaved/gridsome-1/node_modules/puppeteer/.local-chromium/linux-722234

> core-js@3.32.1 postinstall /builds/itsnotsaved/gridsome-1/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> preact@8.5.3 postinstall /builds/itsnotsaved/gridsome-1/node_modules/preact
> node -e "console.log('\u001b[35m\u001b[1mLove Preact? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/preact/donate\u001b[0m')"

[35m[1mLove Preact? You can now donate to our open collective:[22m[39m
 > [34mhttps://opencollective.com/preact/donate[0m

> cwebp-bin@5.1.0 postinstall /builds/itsnotsaved/gridsome-1/node_modules/cwebp-bin
> node lib/install.js

  ⚠ Command failed: /builds/itsnotsaved/gridsome-1/node_modules/cwebp-bin/vendor/cwebp -version
/builds/itsnotsaved/gridsome-1/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory


  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully

> mozjpeg@6.0.1 postinstall /builds/itsnotsaved/gridsome-1/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> pngquant-bin@5.0.2 postinstall /builds/itsnotsaved/gridsome-1/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/sass/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN sass-loader@10.4.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@10.4.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@16.7.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.9 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.9 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

added 2051 packages from 894 contributors and audited 2056 packages in 82.017s
found 40 vulnerabilities (1 low, 13 moderate, 21 high, 5 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
[32;1m$ npm run build[0;m

> gridsome.org@1.0.0 build /builds/itsnotsaved/gridsome-1
> gridsome build

Gridsome v0.7.23

Initializing plugins...
Load sources - 0.9s
Create GraphQL schema - 0.13s
Create pages and templates - 0.09s
Generate temporary code - 0.06s
Bootstrap finish - 2.15s
Compiling assets...
ModuleError: Module Error (from ./node_modules/sass-loader/dist/cjs.js):
globalThis is not defined
    at Object.emitError (/builds/itsnotsaved/gridsome-1/node_modules/webpack/lib/NormalModule.js:173:6)
    at getSassImplementation (/builds/itsnotsaved/gridsome-1/node_modules/sass-loader/dist/utils.js:60:21)
    at Object.loader (/builds/itsnotsaved/gridsome-1/node_modules/sass-loader/dist/index.js:35:59)
    at LOADER_EXECUTION (/builds/itsnotsaved/gridsome-1/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/builds/itsnotsaved/gridsome-1/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/builds/itsnotsaved/gridsome-1/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/builds/itsnotsaved/gridsome-1/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /builds/itsnotsaved/gridsome-1/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/builds/itsnotsaved/gridsome-1/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at writeFn (/builds/itsnotsaved/gridsome-1/node_modules/cache-loader/dist/index.js:118:7)
    at /builds/itsnotsaved/gridsome-1/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqWrap.oncomplete (fs.js:141:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gridsome.org@1.0.0 build: `gridsome build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gridsome.org@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-09-05T06_32_27_440Z-debug.log
section_end:1693895547:step_script
[0Ksection_start:1693895547:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1693895548:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```
