### ISSUE TITLE
Vuetify / FontAwesome Build Error

### ISSUE THREAD

**Issue by nabeelaejaz** [gridsome/gridsome#981]
Hi, I am using vuetify with gridsome. For Icons I am using Fontawesome 5. During build I am getting this error. Kindly help:

```
G:\sanaulla-launch\node_modules\@fortawesome\fontawesome-free\css\all.css:5
.fa,
^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at G:\sanaulla-launch\node_modules\vue-server-renderer\build.prod.js:1:77673
    at Object.<anonymous> (webpack:/external "@fortawesome/fontawesome-free/css/all.css":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (assets/js/app.e2373e88.js:43487:16)
```

**Comment by jornhymcfly** [comment]
What was the solution for this?
